### PR TITLE
TabsContainer: do not restart animation if there is already one executing with the same end value, fixes #1952

### LINKED ISSUE #1952: AppTab crashes on Android
### Describe the bug:
Nil animation pointer

### To Reproduce:
Steps to reproduce the behaviour:
1. Open fyne_demo
2. Go to Containers -> AppTabs
3. Click various tabs

### Stacktrace
```
02-12 15:15:59.871 25633     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
02-12 15:15:59.871 25633     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6e4c363178]
02-12 15:15:59.871 25633     0 E Go      : 
02-12 15:15:59.871 25633     0 E Go      : goroutine 25 [running]:
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/animation.newAnim(0x0, 0x6e40800000)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/animation/animation.go:19 +0x38
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/animation.(*Runner).Start(0x4000308000, 0x0)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/animation/runner.go:22 +0x60
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/driver/gomobile.(*mobileDriver).StartAnimation(0x4000300050, 0x0)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/gomobile/animation.go:6 +0x2c
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2.(*Animation).Start(0x0)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/animation.go:58 +0x48
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/container.(*baseTabsRenderer).moveIndicator(0x40000ea6c0, 0x41e8000000000000, 0x4080000042d00000, 0x4042040001)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/container/tabs.go:306 +0x1e4
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/container.(*appTabsRenderer).updateIndicator(0x40000ea6c0)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/container/apptabs.go:396 +0xd0
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/container.(*appTabsRenderer).Layout(0x40000ea6c0, 0x43f5800043b00000)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/container/apptabs.go:271 +0xb0
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/driver/gomobile.updateLayout(0x6e4c5011e0, 0x40001e0630)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/gomobile/canvas.go:553 +0x108
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/driver/gomobile.(*mobileCanvas).ensureMinSize.func1(0x6e4c501060, 0x40002a4e70, 0x6e4c501ea0, 0x40001e0480)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/gomobile/canvas.go:209 +0x98
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/driver.walkObjectTree(0x6e4c501060, 0x40002a4e70, 0x40001e0400, 0x6e4c501ea0, 0x40001e0480, 0x4308000040800000, 0x0, 0x4f0000004f000000, 0x0, 0x40002e7e20, ...)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/util.go:197 +0x228
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/util.go:176
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/driver.walkObjectTree(0x6e4c501ea0, 0x40001e0480, 0x40001e0600, 0x6e4c5011e0, 0x40001e0630, 0x42ce000040800000, 0x0, 0x4f0000004f000000, 0x0, 0x40002e7e20, ...)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/util.go:190 +0x2d4
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/util.go:176
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/driver.walkObjectTree(0x6e4c5011e0, 0x40001e0630, 0x4001c26b00, 0x6e4c500d60, 0x4001c26b00, 0x4278000040800000, 0x0, 0x4f0000004f000000, 0x0, 0x40002e7e20, ...)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/util.go:190 +0x2d4
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/util.go:176
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/driver.walkObjectTree(0x6e4c500d60, 0x4001c26b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4f0000004f000000, 0x0, 0x40002e7e20, ...)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/util.go:190 +0x2d4
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree(0x6e4c500d60, 0x4001c26b00, 0x0, 0x40002e7e20, 0x0)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/util.go:134 +0x70
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/driver/gomobile.(*mobileCanvas).walkTree(0x4001c0e100, 0x0, 0x40002e7e20)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/gomobile/canvas.go:532 +0x3c
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/driver/gomobile.(*mobileCanvas).ensureMinSize(0x4001c0e100)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/gomobile/canvas.go:213 +0x58
02-12 15:15:59.871 25633     0 E Go      : fyne.io/fyne/v2/internal/driver/gomobile.(*mobileDriver).Run.func1(0x6e4c500b20, 0x6e4c9fc0e0)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/gomobile/driver.go:175 +0x244
02-12 15:15:59.871 25633     0 E Go      : github.com/fyne-io/mobile/app.mainUI.func1(0x40003c8120)
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/pkg/mod/github.com/fyne-io/mobile@v0.1.2/app/android.go:392 +0x44
02-12 15:15:59.871 25633     0 E Go      : created by github.com/fyne-io/mobile/app.mainUI
02-12 15:15:59.871 25633     0 E Go      : 	/Users/stuartscott/Documents/Projects/Go/pkg/mod/github.com/fyne-io/mobile@v0.1.2/app/android.go:391 +0x78
--------- beginning of crash
02-12 15:15:59.872 25633 25661 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 25661 (fyne.demo), pid 25633 (fyne.demo)
02-12 15:15:59.919 25672 25672 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
02-12 15:15:59.919   923   923 I tombstoned: received crash request for pid 25661
02-12 15:15:59.921 25672 25672 I crash_dump64: performing dump of process 25633 (target tid = 25661)
02-12 15:15:59.936 25672 25672 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-12 15:15:59.936 25672 25672 F DEBUG   : Build fingerprint: 'google/walleye/walleye:11/RP1A.201005.004.A1/6934943:user/release-keys'
02-12 15:15:59.936 25672 25672 F DEBUG   : Revision: 'MP1'
02-12 15:15:59.937 25672 25672 F DEBUG   : ABI: 'arm64'
02-12 15:15:59.937 25672 25672 F DEBUG   : Timestamp: 2021-02-12 15:15:59-0800
02-12 15:15:59.937 25672 25672 F DEBUG   : pid: 25633, tid: 25661, name: fyne.demo  >>> fyne.demo <<<
02-12 15:15:59.937 25672 25672 F DEBUG   : uid: 10250
02-12 15:15:59.937 25672 25672 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-12 15:15:59.938 25672 25672 F DEBUG   :     x0  0000000000000000  x1  000000000000643d  x2  0000000000000006  x3  0000000000000008
02-12 15:15:59.938 25672 25672 F DEBUG   :     x4  0000000000000001  x5  0000006e4c3c8c5b  x6  000000000000003f  x7  0000000000000030
02-12 15:15:59.938 25672 25672 F DEBUG   :     x8  0000000000000083  x9  000000000000006c  x10 0000000000000000  x11 0000000006be87cc
02-12 15:15:59.938 25672 25672 F DEBUG   :     x12 00000000341555ad  x13 0000000000000018  x14 00001d33d93280ec  x15 0033da14ad03306a
02-12 15:15:59.938 25672 25672 F DEBUG   :     x16 0000000006be87cc  x17 0000006e4c175800  x18 0000006e23730000  x19 0000000000006421
02-12 15:15:59.938 25672 25672 F DEBUG   :     x20 0000006e240466d0  x21 0000004000042c00  x22 0000000000000001  x23 0000000000000000
02-12 15:15:59.938 25672 25672 F DEBUG   :     x24 0000000000000000  x25 0000000000000000  x26 0000000000000000  x27 0000000000000010
02-12 15:15:59.938 25672 25672 F DEBUG   :     x28 0000004000182a80  x29 0000000000000000
02-12 15:15:59.938 25672 25672 F DEBUG   :     lr  0000006e4c15b420  sp  00000040002e74f0  pc  0000006e4c176558  pst 0000000080000000
02-12 15:15:59.939 25672 25672 F DEBUG   : backtrace:
02-12 15:15:59.939 25672 25672 F DEBUG   :       #00 pc 0000000000220558  /data/app/~~TJ1cqTYnM67Z5g7sdLBgaw==/fyne.demo-QNi3TsUSoHqfGzC_CXnPNQ==/lib/arm64/libfyne.so (runtime.raise+40)
02-12 15:16:00.346   923   923 E tombstoned: Tombstone written to: /data/tombstones/tombstone_21
02-12 15:16:00.350  1427 25675 W ActivityTaskManager:   Force finishing activity fyne.demo/org.golang.app.GoNativeActivity
```

### PR DESCRIPTION
**Pull request by fpabl0**
### Description:

Fixes #1952 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by stuartmscott — COMMENTED** [review]
Confirmed this fixes the animation crash and slowness. Thank you Pablo!! 🥇 

I wonder if the position and size animations should be considered separately, as it will currently only skip animations if both are equal to the last request. @andydotxyz thoughts?

**Comment by andydotxyz** [comment]
> I wonder if the position and size animations should be considered separately

I would have thought that they need to both run together for the correct effect.
If one end result changes we probably want to re-start both or the timing could get offset.

File: container/tabs.go [hunk 1]
```diff
@@ -278,14 +293,13 @@ func (r *baseTabsRenderer) moveIndicator(pos fyne.Position, siz fyne.Size, anima
 		r.sizeAnimation = nil
 	}
 
-	r.indicator.Show()
-	if r.indicator.Position().IsZero() {
-		r.indicator.Move(pos)
-		r.indicator.Resize(siz)
-		r.indicator.Refresh()
+	if r.indicator.Position().Subtract(pos).IsZero() && r.indicator.Size().Subtract(siz).IsZero() {
```
Comment (andydotxyz) [inline container/tabs.go:296]: Is this part of the fix as well, or is it an optimisation?
If I read it correctly this is saying, "if we are starting a new animation, that does not have the same ending state as the current one, but starts at the same place, return" - It seems like we could accidentally not start an animation that should be started in this case..?

Comment (fpabl0) [reply container/tabs.go:296]: Oh my mistake, that line is not needed (it was part of my first try to solve the crash). I will delete it.

Comment (fpabl0) [reply container/tabs.go]: Removed useless condition. Done.

**Review by andydotxyz — APPROVED** [review]

**Comment by andydotxyz** [comment]
@stuartmscott do you want to re-review before this is merged?

**Comment by fpabl0** [comment]
Yes @stuartmscott could you double check this please?

File: container/tabs.go [hunk 2]
```diff
@@ -269,6 +272,18 @@ func (r *baseTabsRenderer) minSize(t baseTabs) fyne.Size {
...
+		r.indicator.Move(pos)
+		r.indicator.Resize(siz)
+		r.indicator.Refresh()
+		return
+	}
+
+	if r.lastIndicatorPos.Subtract(pos).IsZero() && r.lastIndicatorSize.Subtract(siz).IsZero() {
+		return
+	}
+
```
Comment (stuartmscott) [inline container/tabs.go:286]: Are you sure these early-exit conditions should be before stopping any previous animations?

**Review by stuartmscott — COMMENTED** [review]
Overall looks good, just one question below

File: container/tabs.go (hunk 2 above)
Comment (fpabl0) [reply container/tabs.go:286]: I think, it is needed, otherwise it will start animations as before even if there are others running with the same end state 🤔

Comment (stuartmscott) [reply container/tabs.go:286]: Oh yes I agree they are needed, I'm just wondering if they should come after these;
```go
	if r.positionAnimation != nil {
		r.positionAnimation.Stop()
		r.positionAnimation = nil
	}
	if r.sizeAnimation != nil {
		r.sizeAnimation.Stop()
		r.sizeAnimation = nil
	}
```
So that even if we exit early, we still stop any existing animations

Comment (fpabl0) [reply container/tabs.go:286]: The thing is that if we put that after that conditions, the current animation will stop and it is not going to reach its end state

Comment (stuartmscott) [reply container/tabs.go:286]: Do we want the current animations to reach their end state if we have explicitly moved & resized the indicator?
```go
		r.indicator.Move(pos)
		r.indicator.Resize(siz)
```

Comment (stuartmscott) [reply container/tabs.go:286]: The original code was;
```go
	if r.positionAnimation != nil {
		r.positionAnimation.Stop()
		r.positionAnimation = nil
	}
	if r.sizeAnimation != nil {
		r.sizeAnimation.Stop()
		r.sizeAnimation = nil
	}

	r.indicator.Show()
	if r.indicator.Position().IsZero() {
		r.indicator.Move(pos)
		r.indicator.Resize(siz)
		r.indicator.Refresh()
		return
	}
```
I don't mind it getting changed, but I want to make sure there isn't a possibility that the indicator is correctly moved & resized, but a previous animation is still running and overwrites the correct values with wrong values.

Comment (fpabl0) [reply container/tabs.go:286]: Sorry, I don't understand. You mean this part:
```go
r.indicator.Show()
	if r.indicator.Position().IsZero() {
		r.indicator.Move(pos)
		r.indicator.Resize(siz)
		r.indicator.Refresh()
		return
	}
```
should go in a different place?

Comment (fpabl0) [reply container/tabs.go:286]: > a possibility that the indicator is correctly moved & resized, but a previous animation is still running and overwrites the correct values with wrong values.

Hmm, Indicator will be moved and resized correctly, no previous animation can overwrites them with wrong values because it will only happens if lastIndicatorPos and Siz have changed, and if they have changed, then we stop animations if they are not nil 🤔

Comment (fpabl0) [reply container/tabs.go:286]: However, I wonder if a mutex is needed to guarantee that lastValues are not written simultaneously, what do you think?

Comment (stuartmscott) [reply container/tabs.go:286]: I mean like this;
```go
	if r.lastIndicatorPos.Subtract(pos).IsZero() && r.lastIndicatorSize.Subtract(siz).IsZero() {
		return
	}

	if r.positionAnimation != nil {
		r.positionAnimation.Stop()
		r.positionAnimation = nil
	}
	if r.sizeAnimation != nil {
		r.sizeAnimation.Stop()
		r.sizeAnimation = nil
	}

	r.indicator.Show()
	if r.indicator.Position().IsZero() {
		r.indicator.Move(pos)
		r.indicator.Resize(siz)
		r.indicator.Refresh()
		return
	}
```

Comment (fpabl0) [reply container/tabs.go:286]: Yes, you are write that should be below, I will update it :)

Comment (stuartmscott) [reply container/tabs.go:286]: Cool!

> I wonder if a mutex is needed to guarantee that lastValues are not written simultaneously

Yes, I think you maybe right.

Comment (fpabl0) [reply container/tabs.go:286]: Ok, I will add them and then test :)

Comment (fpabl0) [reply container/tabs.go]: Done.

**Comment by fpabl0** [comment]
@stuartmscott updated, please check :)

**Review by stuartmscott — APPROVED** [review]
Perfect, thanks @fpabl0
