### PR TITLE
Fix moving of folder/listable content

### LINKED ISSUE #5493: storage.Move() fails to move directories
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

$path is just the path of the folder/directory

On Linux:
write $path: copy_file_range: is a directory

On Windows:
read $path: Incorrect function.

### How to reproduce

When trying to use the move function on a directory/folder, I get the following error listed above

### Screenshots

The code below results with RootURI looking like this on Linux
Image

### Example code

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/storage"
)

func main() {
	fyneApp := app.NewWithID("MoveFailTestCode")

	path, err := storage.Child(fyneApp.Storage().RootURI(), "Folder")
	fmt.Println(err)

	exists, err := storage.Exists(path)
	fmt.Println(err)

	if !exists {
		err := storage.CreateListable(path)

		if err != nil {
			fmt.Println(err)
		}
	}

	newPath, err := storage.Child(fyneApp.Storage().RootURI(), "RenamedFolder")
	fmt.Println(err)

	err = storage.Move(path, newPath)
	fmt.Println(err)
}
```

### Fyne version

2.5.4

### Go compiler version

1.23.4

### Operating system and version

Linux OpenSuse Tumbleweed && Windows 10

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #5493

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/repository/file.go [hunk 1]
```diff
@@ -301,6 +301,15 @@ func (r *FileRepository) Copy(source, destination fyne.URI) error {
...
+		err := os.Rename(source.Path(), destination.Path())
+		if err == nil {
+			return nil
+		}
+		// fallthrough to slow move
+	}
+
 	// NOTE: as far as I can tell, golang does not have an optimized Move
 	// function - everything I can find on the 'net suggests doing more
 	// or less the equivalent of GenericMove(), hence why that is used.
```
Comment (Jacalz) [inline internal/repository/file.go:315]: Does the above change not invalidate this comment? I think it can be removed. I also kind of don't like that it says "golang" lol so that motivates me more to remove it :)

**Review by Jacalz — CHANGES_REQUESTED** [review]
Thanks. Looks great. I think there just is a comment that no longer applies with these changes.

File: internal/repository/file.go (hunk 1 above)
Comment (Jacalz) [reply internal/repository/file.go:315]: Is it not possible to use the same `os.Rename` function for files?

Comment (andydotxyz) [reply internal/repository/file.go:315]: It might be - I was only looking at folders.

Whatever we have to leave the slow path in as well because any Move (/Rename) can fail due to filesystem traversal or cross-volume issues.

Comment (Jacalz) [reply internal/repository/file.go:315]: Alright. Lets add a fast path for regular files as a followup

**Review by Jacalz — APPROVED** [review]

File: internal/repository/file.go (hunk 1 above)
Comment (Jacalz) [reply internal/repository/file.go:315]: Opened https://github.com/fyne-io/fyne/issues/5517
