### PR TITLE
richtext: underline all wrapped hyperlink segments on hover

### LINKED ISSUE #6226: A wrapped hyperlink displays as separate hyperlinks
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

https://github.com/fyne-io/fyne/issues/3393 introduced wrapping support for Hyperlinks in RichText. There is still a behavioral issue whereby hovering one of the wrapped segments only underlines that segment. All should underline in unison to show that it is the same hyperlink.

### How to reproduce

Run example code from https://github.com/fyne-io/fyne/issues/3393 and hover one of the wrapped segments of the link.

### Screenshots

_No response_

### Example code

in https://github.com/fyne-io/fyne/issues/3393

### Fyne version

develop

### Go compiler version

any

### Operating system and version

any

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dweymouth**
### Description:

When a HyperlinkSegment wraps across multiple rows, each row gets its own Hyperlink widget instance. Hovering one now propagates the hovered state to all sibling instances so the underline appears across the full link, not just the segment under the cursor.

Siblings are linked inline during textRenderer.Refresh using the existing visualCache: reuse equals the current visual's cache offset and the count of prior row visuals, so earlier instances are fetched at offsets 0..reuse-1 and wired into an all-to-all sibling list with no extra allocations per refresh.

Fixes #6226

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: widget/richtext.go [hunk 1]
```diff
@@ -736,8 +736,20 @@ func (r *textRenderer) Refresh() {
...
+				// cached at successive offsets for the same segment. reuse is both
+				// this visual's cache offset and the count of prior row visuals, so
+				// the earlier ones sit at offsets 0..reuse-1 and can be fetched
+				// directly from the cache to build the all-to-all sibling list.
+				hl.siblings = hl.siblings[:0]
+				for prev := 0; prev < reuse; prev++ {
+					prevHL := r.obj.cachedSegmentVisual(hlSeg, prev).(*fyne.Container).Objects[0].(*Hyperlink)
+					prevHL.siblings = append(prevHL.siblings, hl)
+					hl.siblings = append(hl.siblings, prevHL)
+				}
```
[the remark this answers is not in the document]
Comment (dweymouth) [reply widget/richtext.go]: `n` is expected to be pretty small for all reasonable real-world cases. Not sure it's worth worrying about

File: widget/richtext.go [hunk 2]
```diff
@@ -736,8 +736,20 @@ func (r *textRenderer) Refresh() {
 			if isText {
 				obj.(*canvas.Text).Text = txt
 			} else if isHyperlink {
-				obj.(*fyne.Container).Objects[0].(*Hyperlink).Text = txt
-				obj.(*fyne.Container).Objects[0].(*Hyperlink).Refresh()
+				hl := obj.(*fyne.Container).Objects[0].(*Hyperlink)
+				hl.Text = txt
+				// A wrapping hyperlink produces one Hyperlink widget per row, each
```
Comment (andydotxyz) [inline widget/richtext.go]: This block of comment goes against the idea of self-explanatory code.
Either it isn't needed because the code is clear or the code itself should be made more readable.

I wonder if a method call `associateSiblings` or similar should be sufficient?

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Thanks for catching and fixing this.
Can you address the wall of text comment so it's cleaner code?

File: widget/richtext.go (hunk 2 above)
Comment (dweymouth) [reply widget/richtext.go]: I simplified the comment. Hopefully this is better. Side note -- I found the `cachedSegmentVisual` stuff in the RichText code hard to understand, partially because the names don't seem very descriptive to me. I wonder if there are better names for `cachedSegmentVisual` and `reuse`

Comment (andydotxyz) [reply widget/richtext.go]: Hmm, by leaving this comment (albeit smaller than before) are you saying that there is no way this code could be refactored to be self-describing?

I understand that variables could be better elsewhere - but was `associateSiblings` not helpful? In general I am trying to stick with the idea that a comment line describing what is being done is harder to read (and maintain) than a function call with that name...

**Review by andydotxyz — APPROVED** [review]
Great thanks
