### PR TITLE
Mouse handling optimization

### LINKED ISSUE #5815: Two textgrids inside NewHSplit are considerably laggy
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When I have two textgrids inside a HSplit container, dragging the splitter from left to right causes noticeable lag.

### How to reproduce

1. Run example code
2. Drag split back and forth.
3. Observe considerable lagginess when dragging.

### Screenshots

_No response_

### Example code

```go
package main

import (
        "fyne.io/fyne/v2"
        "fyne.io/fyne/v2/app"
        "fyne.io/fyne/v2/container"
        "fyne.io/fyne/v2/widget"
)

func main() {
        a := app.New()
        w := a.NewWindow("Test")
        w.Resize(fyne.NewSize(800, 800))

        grid1 := widget.NewTextGrid()
        grid2 := widget.NewTextGrid()

        w.SetContent(container.NewHSplit(grid1, grid2))
        w.ShowAndRun()
}
```

### Fyne version

develop

### Go compiler version

1.24.4

### Operating system and version

Gentoo

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by redawl**
### Description:

Since glfw gives us mouse position every time the callback is called, we can just save the position, and only call `processMouseMoved` right before we draw each frame. This can make a huge difference when mouse movement events are coming in at a faster rate than the frame rate. ~Same optimization for window resize events.~

There might be other input events where a similar optimization is possible, this is just a start.

Fixes #5815, #3374 ~possibly #1114?~. 
~Also drastically improves resizing for https://github.com/fyne-io/solitaire :)~

_Note: Tests for `mouseMoved` had to be updated, since they expected `processMouseMoved` to be called internally. I added a helper method for tests that fulfills that assumption._

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by redawl** [comment]
Hmm, maybe the flaky tests are real this time? I don't see any races in a real application though

**Comment by Jacalz** [comment]
Hmm, maybe. More likely a race in our test framework than your code, or rather this surfaces those issues more clearly. I think you best bet is looking at those failing tests and seeing if there is any code that runs directly in the test function and not on main. Remember, Go executes each test in its own goroutine so they are not running on the main thread by default like a regular app.

File: internal/driver/glfw/window_test.go [hunk 1]
```diff
@@ -247,8 +247,7 @@ func TestWindow_Cursor(t *testing.T) {
 	w.SetContent(container.NewVBox(e, h, b))
 	repaintWindow(w)
 	ensureCanvasSize(t, w, fyne.NewSize(72, 123))
-
-	w.mouseMoved(w.viewport, 10, float64(e.Position().Y+10))
+	w.moveMouse(10, float64(e.Position().Y+10))
```
Comment (Jacalz) [inline internal/driver/glfw/window_test.go]: I suppose lines like this may be the culprit.

Comment (redawl) [reply internal/driver/glfw/window_test.go]: It seems that putting the necessary codeblocks in `runOnMain` is causing test runtime to exceed 10 minutes. If anyone has time to look into fixing the unit tests races I would be grateful. Otherwise, I'll keep poking at it

Comment (andydotxyz) [reply internal/driver/glfw/window_test.go]: Exceeding the deadline normally means a deadlock. Which indicates that the `runOnMain` was calling something else that is `runOnMain` inside it. Note that the "safeCanvas" type and others are attempting to automatically wrap so it's not always needed where it appears it might be.

Hopefully that is a clue. I might get a chance to look tomorrow.

Comment (redawl) [reply internal/driver/glfw/window_test.go]: Boom! Tests are passing. 
I realized that the previous code was creating a MouseEvent every frame, when there was no mouse movement. This was what was causing the races, since the main thread was reading and writing to shared state much more often than before.

I still have a little more to cleanup, mostly related to variable names for the w.*Updated checks, and still need to verify wasm is working.

**Comment by dweymouth** [comment]
Should this be done for other GLFW calls as well (eg scroll, window resizing?)

Though this general approach does open up the discussion topic of whether we want to tie user input events with the frame rate as a general strategy, or relay input events as fast as possible but optimize elsewhere to avoid doing too many unnecessary calculations. Apps that use mouse/scroll/etc events for something else other than manipulating objects on screen (e.g. possibly games, audio or CAD apps, possibly more) may view being limited to 60hz input events as somewhat of a limitation, but maybe it's worth it for simplicity?

**Comment by redawl** [comment]
> Should this be done for other GLFW calls as well (eg scroll, window resizing?)

Yeah, we'll want to do this for all GLFW events. I just wanted to get started with these two as a proof of concept :)

> Though this general approach does open up the discussion topic of whether we want to tie user input events with the frame rate as a general strategy, or relay input events as fast as possible but optimize elsewhere to avoid doing too many unnecessary calculations. Apps that use mouse/scroll/etc events for something else other than manipulating objects on screen (e.g. possibly games, audio or CAD apps, possibly more) may view being limited to 60hz input events as somewhat of a limitation, but maybe it's worth it for simplicity?

Events in GLFW aren't guaranteed to be handled as they come in anyway:
https://www.glfw.org/docs/3.3/group__window.html#ga37bd57223967b4211d60ca1a0bf3c832

Most of the time, events are tied to the rate that `glfw.PollEvents` is called, which in our case is once per frame.

**Comment by redawl** [comment]
Unfortunately, the resize optimization doesn't work on Windows and macOS platforms, because `glfw.PollEvents` blocks while the user is resizing the window, causing the event loop to stall, and it never gets to `processResized`. 

I have updated the PR description to reflect this.
