### PR TITLE
Do not append entryContentRenderer's objects in the selection slice, fixes #1983

### LINKED ISSUE #1983: Various interface conversion panics when selecting text in a widget.Entry
### Describe the bug:
Occasionally when selecting text in a multi-line widget.Entry, one of these panics occur:

```
panic: interface conversion: fyne.CanvasObject is *widget.textProvider, not *canvas.Rectangle

goroutine 12 [running]:
fyne.io/fyne/v2/widget.(*entryContentRenderer).Refresh(0xc000067260)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/entry.go:1333 +0x493
fyne.io/fyne/v2/widget.(*entryRenderer).Refresh(0xc000024680)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/entry.go:1193 +0x35c
fyne.io/fyne/v2/widget.(*BaseWidget).Refresh(0xc0002be480)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/widget.go:139 +0x5c
fyne.io/fyne/v2/widget.(*BaseWidget).setFieldsAndRefresh(0xc0002be480, 0xc00004cef0)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/widget.go:165 +0x7e
fyne.io/fyne/v2/widget.(*Entry).updateMousePointer(0xc0002be480, 0xc000209340, 0xc000546400)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/entry.go:1036 +0x97
fyne.io/fyne/v2/widget.(*Entry).Dragged(0xc0002be480, 0xc000209340)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/entry.go:245 +0x45
fyne.io/fyne/v2/widget.(*entryContent).Dragged(0xc0000704b0, 0xc000209340)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/entry.go:1253 +0x39
fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseMoved.func4()
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/window.go:667 +0x38
fyne.io/fyne/v2/internal/driver/glfw.(*window).runEventQueue(0xc00014a1c0)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/window.go:1242 +0x7a
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/window.go:1266 +0x10d
```

and:

```
panic: interface conversion: fyne.CanvasObject is *widget.textProvider, not *canvas.Rectangle

goroutine 25 [running]:
fyne.io/fyne/v2/widget.(*entryContentRenderer).Refresh(0xc0000b7200)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/entry.go:1333 +0x493
fyne.io/fyne/v2/widget.(*entryRenderer).Refresh(0xc0000cc600)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/entry.go:1193 +0x35c
fyne.io/fyne/v2/widget.(*BaseWidget).Refresh(0xc000083200)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/widget.go:139 +0x5c
fyne.io/fyne/v2/widget.(*BaseWidget).setFieldsAndRefresh(0xc000083200, 0xc00004cef0)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/widget.go:165 +0x7e
fyne.io/fyne/v2/widget.(*Entry).updateMousePointer(0xc000083200, 0xc0004e0c60, 0xc000620300)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/entry.go:1036 +0x97
fyne.io/fyne/v2/widget.(*Entry).Dragged(0xc000083200, 0xc0004e0c60)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/entry.go:245 +0x45
fyne.io/fyne/v2/widget.(*entryContent).Dragged(0xc0000b8460, 0xc0004e0c60)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/entry.go:1253 +0x39
fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseMoved.func4()
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/window.go:667 +0x38
fyne.io/fyne/v2/internal/driver/glfw.(*window).runEventQueue(0xc0000fe1c0)
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/window.go:1242 +0x7a
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        .../go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/window.go:1266 +0x10d
```

### To Reproduce:
This is about a 90% reproduction for me:

1. Create a widget.Entry configured with `Wrapping = fyne.TextWrapWord` and `MultiLine = true`
2. Add sufficient text that the widget scrolls
3. Mouse down to start selecting the first line of text and drag the cursor down to select the rest, forcing the widget to scroll
4. After selecting down to the bottom, move the cursor back up to start deselecting some of the bottom text

After step 3 the selection seems to get a bit laggy, or ignores the cursor for a bit, and then when it starts again in step 4 fyne panics.

### Screenshots:
Peek 2021-02-20 00-08

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

var (
	input = widget.NewEntry()
	output = widget.NewEntry()
)

func main() {
	seeker := app.New()
	window := seeker.NewWindow("Seeker")
	window.Resize(fyne.Size{Width: 800, Height: 300})
	window.SetContent(container.NewGridWithColumns(2, leftColumn()))
	input.Wrapping = fyne.TextWrapWord
	input.MultiLine = true
	output.MultiLine = true
	output.Disable()

	input.SetText("Hello,\nthis\nis\na\ntest\nFoo\nbar\nbaz\nline\nline\nline")

	window.Show()
	seeker.Run()
}

func leftColumn() *fyne.Container {
	return container.NewGridWithColumns(1,
		container.NewBorder(
			widget.NewLabel("Input:"),
			nil,
			nil,
			nil,
			input,
		),
		container.NewBorder(
			widget.NewLabel("Output:"),
			nil,
			nil,
			nil,
			container.NewMax(output),
		),
	)
}
```

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** Arch (up-to-date as of 2020-02-20)
 - **Go version:** 1.15.8
 - **Fyne version:** `fyne.io/fyne/v2 v2.0.0 h1:TfsS3bNq5663BpXsoz1OfzyjcaMqqOf9usI8ZKkw4IE=`

### PR DESCRIPTION
**Pull request by fpabl0**
### Description:

Fixes #1983 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: widget/entry.go [hunk 1]
```diff
@@ -1296,7 +1296,8 @@ func (r *entryContentRenderer) Objects() []fyne.CanvasObject {
 	defer r.content.entry.propertyLock.RUnlock()
 	// Objects are generated dynamically force selection rectangles to appear underneath the text
 	if r.content.entry.selecting {
-		return append(r.selection, r.objects...)
+		objs := append([]fyne.CanvasObject(nil), r.selection...)
```
Comment (Jacalz) [inline widget/entry.go:1299]: You should be able to do `[]fyne.CanvasObject{}` instead of `[]fyne.CanvasObject(nil)`.

**Review by Jacalz — CHANGES_REQUESTED** [review]

File: widget/entry.go [hunk 2]
```diff
@@ -1296,7 +1296,8 @@ func (r *entryContentRenderer) Objects() []fyne.CanvasObject {
...
+		return append(objs, r.objects...)
```
Comment (andydotxyz) [inline widget/entry.go:1300]: The title indicates that the fix was to not append the objects, but this change looks like rearranged code that does the same thing?...

File: widget/entry.go (hunk 1 above)
Comment (fpabl0) [reply widget/entry.go:1299]: Yes, that's right, but I think `[]fyne.CanvasObject(nil)` is more performant because it does not allocate any memory at first time (`append` will create a new slice either with []fyne.CanvasObject{} or []fyne.CanvasObject(nil), however in the first one you have already allocated space that won't be useful)

File: widget/entry.go (hunk 2 above)
Comment (fpabl0) [reply widget/entry.go:1300]: Well, that's not true. `append` does not always generate a new slice. It only creates a new slice if the current slice does not have enough capacity, otherwise it writes it.

Comment (andydotxyz) [reply widget/entry.go:1300]: I am a little unsure - if we are adding all of the `r.selection` and `r.objects` to a new slice is that not the same result as appending one to the other.
It will no longer be able to re-use the same memory as before, but without it there should not be phantom elements randomly added due to memory re-use...

Comment (fpabl0) [reply widget/entry.go:1300]: > I am a little unsure - if we are adding all of the r.selection and r.objects to a new slice is that not the same result as appending one to the other.

The underlying memory array is modified if we append one to the other.

> It will no longer be able to re-use the same memory as before, but without it there should not be phantom elements randomly added due to memory re-use...

Yes, that is idea and as far as I see, it is the easiest way. Other way is adding synchronization but maybe it would be less performant due to the timing with locks and unlocks.

Comment (Jacalz) [reply widget/entry.go:1300]: > > I am a little unsure - if we are adding all of the r.selection and r.objects to a new slice is that not the same result as appending one to the other.
> 
> 
> 
> The underlying memory array is modified if we append one to the other.
> 

I am not so sure that's correct. Appending something returns a new slice, not updates the old one, as far as I know. That's the whole reason why you do `slice = append(slice, stuff...)`.

Comment (fpabl0) [reply widget/entry.go:1300]: > Appending something returns a new slice, not updates the old one, as far as I know.

That's not the way `append` function works, you can try it:
https://play.golang.org/p/60hb6o4c_kW

> That's the whole reason why you do slice = append(slice, stuff...).

The main reason of doing it is to avoid resizing the slice (if it has enough capacity) or to do have a new one but just because you need more capacity.

Comment (Jacalz) [reply widget/entry.go:1300]: Interesting. You learn something new every day 🙂

Comment (fpabl0) [reply widget/entry.go:1300]: Yes, that was crazy for me too when I learned it two years ago 😅. But in that way, `append` is more efficient. Indeed to be more efficient this part:
```go
objs := append([]fyne.CanvasObject(nil), r.selection...)
return append(objs, r.objects...)
```
could be written like this:
```go
objs := make([]fyne.CanvasObject, 0, len(r.selection) + len(r.objects))
objs = append(objs, r.selection...)
return append(objs, r.objects...)
```
In that way, Objects() will not create slices with more capacity than we want. And `objs` slice is just the same first one not a new one.

Comment (andydotxyz) [reply widget/entry.go:1300]: I would support that change, it seems clearer.

Comment (andydotxyz) [reply widget/entry.go:1300]: p.s. mind blown! you may find this mistake in other places as I (and may be others) did not realise)

Comment (fpabl0) [reply widget/entry.go:1300]: > I would support that change, it seems clearer.

Got it. Will update.

> you may find this mistake in other places as I (and may be others) did not realise)

I see, it is not entirely a mistake if you don't mind the integrity of the slice, so we can just wait if anything fails then it should be fixed, if not I think that should be ok (memory re-used) :)

Comment (fpabl0) [reply widget/entry.go:1301]: done

File: widget/entry.go (hunk 1 above)
Comment (fpabl0) [reply widget/entry.go]: resolved in favor of the last change using `make`.

**Review by andydotxyz — APPROVED** [review]

**Review by Jacalz — APPROVED** [review]
