### PR TITLE
Fix #3459 by changing srcdir to it's absolute path

### LINKED ISSUE #3459: cmd/fyne package can't find FyneApp.toml when -src option has given
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I am trying to build project with fyne cmd but I get an error:
`Missing application icon at "cmd\myapp\Icon.png"`

My project structure is like this:
```
root
--cmd
----myapp
------assets
--------icon.png
------main.go
--pkg
--FyneApp.toml
--Makefile
```

FyneApp.toml
```
Website = "https://www.example.com"

[Details]
  Icon = "cmd/myapp/assets/icon.png"
  Name = "myapp"
  ID = "com.myapp.app"
  Version = "0.1.0"
  Build = 50
```

I am running this command in the root but it doesn't work and gives the error:
`fyne package -release -os windows -src cmd/myapp`

I tried moving icon to cmd/myapp/Icon.png but it also doesn't work

Moving FyneApp.toml to cmd/myapp and running command `fyne package -release -os windows` in cmd/myapp works so I think the problem happens only with -src option

What I want is fyne should look FyneApp.toml in cwd and load it from there so I can put FyneApp.toml to root and run fyne package in root

### How to reproduce

1. Create a project with same structure like above
2. Run `fyne package -release -os windows -src cmd/myapp` in root

### Screenshots

_No response_

### Example code

_No response_

### Fyne version

2.2.3

### Go compiler version

1.19.1

### Operating system

Windows

### Operating system version

11

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hismailbulut**
### Description:

Using relative paths with os.Chdir brokes joined file paths, to prevent this we can just use absolute filepaths without changing anything other

Fixes #3459 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style and have Since: line.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Updated the vendor folder (using `go mod vendor`).
- [ ] Check for binary size increases when importing new modules.

### CODE REVIEW

File: cmd/fyne/internal/commands/build.go [hunk 1]
```diff
@@ -90,6 +90,13 @@ func Build() *cli.Command {
 // Build parse the tags and start building
 func (b *Builder) Build() error {
 	if b.srcdir != "" {
+		// Use absolute srcdir
```
Comment (andydotxyz) [inline cmd/fyne/internal/commands/build.go:93]: It would be better to check and correct `srcdir` earlier so that it is consistent (validate etc can also use this).
Build will not always be called so later stages will not have this correction run.
It may also avoid the duplication in the PR.

**Review by andydotxyz — CHANGES_REQUESTED** [review]
I'd rather not mutate the configuration during the build phase, this seems prone to complications.

File: cmd/fyne/internal/commands/build.go (hunk 1 above)
Comment (hismailbulut) [reply cmd/fyne/internal/commands/build.go:93]: Builder.Build function is the first thing called when user starts fyne build and only called by this command. I don't see anywhere earlier than this. Other commands just calls underlying build function. Thats why I have to add it to Package.validate because it seems release and install commands also calling it and we don't need to add another correction for them.

Comment (Bluebugs) [reply cmd/fyne/internal/commands/build.go:93]: Yes, we do have `fyne build` command that try to mimick the `go build` command.

Comment (andydotxyz) [reply cmd/fyne/internal/commands/build.go:93]: > Builder.Build function is the first thing called when user starts fyne build and only called by this command. I don't see anywhere earlier than this. Other commands just calls underlying build function

What I meant is that this may not be called. If the exe specified already exists then it won't try to build.

File: cmd/fyne/internal/util/file.go [hunk 2]
```diff
@@ -39,6 +39,31 @@ func EnsureSubDir(parent, name string) string {
 	return path
 }
 
+// EnsureAbsPath returns the absolute path of the given file if it is not already absolute
+func EnsureAbsPath(path string) string {
+	if !filepath.IsAbs(path) {
```
Comment (andydotxyz) [inline cmd/fyne/internal/util/file.go:44]: We prefer to exit early when we can instead of having method contents indented in long ifs.
i.e.
```go
if file path.IsAbs(path) {
    return path
}
```

File: cmd/fyne/internal/util/file.go [hunk 3]
```diff
@@ -39,6 +39,31 @@ func EnsureSubDir(parent, name string) string {
...
+			return abs
+		}
+	}
+	return path
+}
+
+// MakePathRelative joins root with path if path is not absolute and exists in root
+// both root and path must non-empty, otherwise path will be returned
+func MakePathRelative(root, path string) string {
+	if root != "" && path != "" && !filepath.IsAbs(path) {
```
Comment (andydotxyz) [inline cmd/fyne/internal/util/file.go:58]: As above, the inverse of this check is a chance to return early, then the rest of the method at the top-level is the purpose of the code

File: cmd/fyne/internal/util/file.go [hunk 4]
```diff
@@ -39,6 +39,31 @@ func EnsureSubDir(parent, name string) string {
...
+		} else {
+			return abs
+		}
+	}
+	return path
+}
+
+// MakePathRelative joins root with path if path is not absolute and exists in root
+// both root and path must non-empty, otherwise path will be returned
+func MakePathRelative(root, path string) string {
```
Comment (andydotxyz) [inline cmd/fyne/internal/util/file.go:57]: This name seems misleading - the path returned is absolute.
Perhaps you meant `MakePathRelativeTo`?

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Thanks, this reads cleanly - just some comments about style

**Review by andydotxyz — APPROVED** [review]
Thanks
