### PR TITLE
Actually handle Key Repeat in TypedKey and TypedShortcut

### LINKED ISSUE #165: Delete/Backspace key repeat cycle not working
I'm not sure if I'm missing something, but pressing the delete key (Mac) without releasing does not delete text the on demo forms. It only deletes the first character before the cursor and stops. One has to press, release and press for continuous deletion

### PR DESCRIPTION
**Pull request by andydotxyz**
TypedRune already does this.
Fixes #165

### CODE REVIEW

File: driver/gl/window.go [hunk 1]
```diff
@@ -686,7 +686,7 @@ func (w *window) keyPressed(viewport *glfw.Window, key glfw.Key, scancode int, a
 		} else if w.canvas.onKeyDown != nil {
 			go w.canvas.onKeyDown(keyEvent)
 		}
-	} else { // ignore key up / repeat in core events
+	} else if action == glfw.Release { // ignore key up in core events
 		if action == glfw.Release {
```
Comment (lucor) [inline driver/gl/window.go]: Maybe duplicatation code type?
Apart that LGTM
