### PR TITLE
Start fixing scrolling containing entries

### LINKED ISSUE #1939: Entry without scrollable content prevents scrolling of outside scroller
### Describe the bug:

An empty (or just not with enough content to scroll) will prevent the scrolling of an external scroller even though there is nothing to scroll within it.

### To Reproduce:
1. Make the window large enough that it can be scrolled.
2. Move the mouse to be over the label.
3. Scroll and notice that it works as expected.
4. Move the mouse to be over the entry.
5. Scroll and notice that it does not scroll.

### Screenshots:

scolling-not-in-entry

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Entry scroll")

	w.SetContent(container.NewScroll(
		container.NewVBox(
			widget.NewEntry(),
			widget.NewLabel("Scroll on me!"),
		),
	),
	)

	w.ShowAndRun()
}
```

### Device (please complete the following information):
- **OS:**  Linux
- **Version:**  5.10.12
- **Go version:** 1.15.7
- **Fyne version:** 2.0.0

### PR DESCRIPTION
**Pull request by andydotxyz**
When setting up an entry do not expose a scroll container unless multiline or scrolling is specified.
This is the best we can do until a future version of event handling that can reflect on object state not existance.

Fixes #1939

TODO
- [x] Reconfigure if the wrap type changes

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: widget/entry.go [hunk 1]
```diff
@@ -158,13 +158,21 @@ func (e *Entry) CreateRenderer() fyne.WidgetRenderer {
 	// initialise
 	e.textProvider()
 	e.placeholderProvider()
+	scrolling := e.Wrapping != fyne.TextWrapOff
```
Comment (Jacalz) [inline widget/entry.go:161]: Couldn't this just be moved into the if statement on line 169?

**Review by Jacalz — COMMENTED** [review]
This is working as expected. Thank you very much :+1: 
I know that this is a draft, I just popped in a little comment while at it :sweat_smile:

**Comment by andydotxyz** [comment]
I don't know if it is useful, but I was playing with this code to test the changing state :) 
```go
func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	e1 := widget.NewEntry()
	e1.Wrapping = fyne.TextWrapOff
	e2 := widget.NewEntry()
	e2.Wrapping = fyne.TextWrapOff
	e3 := widget.NewEntry()
	e3.Wrapping = fyne.TextWrapOff

	off := true
	w.SetContent(container.NewVBox(container.NewScroll(
		container.NewVBox(e1, e2, e3),
	),
	widget.NewButton("Scroll", func() {
		if off {
			e2.Wrapping = fyne.TextTruncate
		} else {
			e2.Wrapping = fyne.TextWrapOff
		}
		off = !off
		e2.Refresh()
	}),
	))

	w.ShowAndRun()
}
```

**Review by Jacalz — APPROVED** [review]
