### PR TITLE
fix entry undo and redo don't trigger OnChanged

### LINKED ISSUE #5710: Entry OnChanged does not get triggered on undo and redo
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When using a entry input, the OnChanged does not gets triggered when Undo and redo is done.

### How to reproduce

In the Fyne App for Entry widget, write some content
used CTRL+Z for undo, and see the OnChanged not getting triggered.
Similarly for CTRL+Y for redo the OnChanged for Entry does not gets triggered.

### Screenshots

_No response_

### Example code

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Text Grid")

	entry := widget.NewEntry()
	entry.OnChanged = func(v string) {
		fmt.Println(v)
	}

	w.SetContent(entry)

	w.Resize(fyne.NewSize(400, 400))

	w.ShowAndRun()
}

```

### Fyne version

2.6.0

### Go compiler version

1.24

### Operating system and version

Windows 11

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mbaklor**
### Description:
using undo and redo on an entry widget didn't trigger OnChanged, so I added a call to the callback in both methods.

Fixes #5710 

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: widget/entry.go [hunk 1]
```diff
@@ -426,6 +426,10 @@ func (e *Entry) Redo() {
 	e.updateText(newText, false)
 	e.CursorRow, e.CursorColumn = e.rowColFromTextPos(pos)
 	e.syncSelectable()
+	cb := e.OnChanged
```
Comment (andydotxyz) [inline widget/entry.go:429]: This could be simplified:

```go
	if cb := e.OnChanged; cb != nil {
```

File: widget/entry.go [hunk 2]
```diff
@@ -426,6 +426,10 @@ func (e *Entry) Redo() {
...
+	if cb != nil {
+		cb(newText) // We know that the text has changed.
```
Comment (andydotxyz) [inline widget/entry.go:431]: Avoid comments unless it is required and cannot be communicated through cleaner code - this seems self-evident so no need

File: widget/entry.go (hunk 1 above)
Comment (mbaklor) [reply widget/entry.go:429]: this is fair but I wanted to keep it in line with the other places we call the callback, I'll fix when I get home, we can remove the whole `cb := ` at this point since we no longer have to mutex lock

File: widget/entry.go (hunk 2 above)
Comment (mbaklor) [reply widget/entry.go:431]: oops I was sure I removed them that's my bad, I'll fix when I get home 😅

File: widget/entry.go (hunk 1 above)
Comment (andydotxyz) [reply widget/entry.go:429]: I did do that check to make sure it wasn't suitably matching - but in the other cases the callback was taken a long time before the callback. Perhaps they do indeed all need fixed with the mutex changes, not sure.

**Comment by mbaklor** [comment]
Fixed the stylistic things, no need to copy the callback now that there isn't a mutex lock, and removed the comment that I accidentally yanked from elsewhere

**Review by andydotxyz — APPROVED** [review]
Thanks!
