### PR TITLE
Full race condition fixes

### LINKED ISSUE #506: Massive data race detect!!
**Describe the bug**
Im compile my soft with option -race. After start im loock in console 23 event data race

**Device (please complete the following information):**
 - OS: Ubuntu Linux
 - Version 18.04 LTS
 - Go version 1.13.1
 - Fyne version: last stable, public download from github.

### PR DESCRIPTION
**Pull request by andydotxyz**
### Description:

This will conclude by turning on race checking in our tests again :).

- [x] Add utility to BaseWidget to provide safe property access
- [x] Fix race conditions in our codebase :) (this one will be 100% in this PR 😄)
- [ ] Re-enable race checking in the traivs config

Fixes #506 

### Checklist:

- [x] Tests included. <- well, current tests with "-race" added
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.
- [x] Public APIs match existing style.

This PR will fix the race conditions in `widget` package.

### CODE REVIEW

**Comment by andydotxyz** [comment]
OK, this PR now shows the proposed approach to widget safety.
It took the count to below 100 races (from around 200) in the widget package by just fixing BaseWidget.
Further commits will resolve the widget specific issues.

File: internal/widget/base.go [hunk 1]
```diff
@@ -10,34 +12,72 @@ type base struct {
...
+func (b *base) readFields(f func()) {
+	b.propertyLock.RLock()
+	defer b.propertyLock.RUnlock()
+
+	f()
+}
+
+// SetFieldsAndRefresh helps to make changes to a widget that should be followed by a refresh.
+// This method is a guaranteed thread-safe way of directly manipulating widget fields.
+func (b *base) setFieldsAndRefresh(w fyne.Widget, f func()) {
```
Comment (stuartmscott) [inline internal/widget/base.go:45]: nit: the name ordering doesn't match parameter ordering.
```suggestion
func (b *base) setFieldsAndRefresh(f func(), w fyne.Widget) {
```

File: widget/widget.go [hunk 2]
```diff
@@ -13,51 +15,95 @@ type BaseWidget struct {
...
+}
+
+// SetFieldsAndRefresh helps to make changes to a widget that should be followed by a refresh.
+// This method is a guaranteed thread-safe way of directly manipulating widget fields.
+func (w *BaseWidget) SetFieldsAndRefresh(f func()) {
+	w.propertyLock.Lock()
+	f()
+	w.propertyLock.Unlock()
+
+	w.Refresh()
```
Comment (stuartmscott) [inline widget/widget.go:49]: What if the basewidget has been extended?
```suggestion
	if w.impl == nil {
		w.Refresh()
	} else {
		w.impl.Refresh()
	}
```

File: internal/widget/base.go [hunk 3]
```diff
@@ -10,34 +12,72 @@ type base struct {
...
 
 func (b *base) hide(w fyne.Widget) {
-	if b.hidden {
+	if !b.Visible() {
 		return
 	}
 
+	b.propertyLock.Lock()
 	b.hidden = true
+	b.propertyLock.Unlock()
```
Comment (stuartmscott) [inline internal/widget/base.go:80]: Use setFieldsAndRefresh(f func(){...}, nil) for consistency

File: internal/widget/base.go [hunk 4]
```diff
@@ -60,11 +100,17 @@ func (b *base) refresh(w fyne.Widget) {
...
+	b.readFields(func() {
+		baseSize = b.size
+	})
+	if baseSize == size {
 		return
 	}
 
+	b.propertyLock.Lock()
 	b.size = size
+	b.propertyLock.Unlock()
```
Comment (stuartmscott) [inline internal/widget/base.go:113]: Use setFieldsAndRefresh(f func(){...}, nil) for consistency

File: widget/widget.go [hunk 5]
```diff
@@ -13,51 +15,95 @@ type BaseWidget struct {
...
 
-	impl fyne.Widget
+	impl         fyne.Widget
+	propertyLock sync.RWMutex
 }
 
 // ExtendBaseWidget is used by an extending widget to make use of BaseWidget functionality.
 func (w *BaseWidget) ExtendBaseWidget(wid fyne.Widget) {
+	w.propertyLock.Lock()
+	defer w.propertyLock.Unlock()
```
Comment (stuartmscott) [inline widget/widget.go:25]: Use SetFieldsAndRefresh(f func(){...}) for consistency

File: widget/widget.go [hunk 6]
```diff
@@ -13,51 +15,95 @@ type BaseWidget struct {
...
+	f()
+	w.propertyLock.Unlock()
+
+	w.Refresh()
+}
+
 // Size gets the current size of this widget.
 func (w *BaseWidget) Size() fyne.Size {
+	w.propertyLock.RLock()
+	defer w.propertyLock.RUnlock()
```
Comment (stuartmscott) [inline widget/widget.go:55]: Use ReadFields(f func(){...}) for consistency

File: widget/widget.go [hunk 7]
```diff
@@ -13,51 +15,95 @@ type BaseWidget struct {
...
 		return
 	}
-	cache.Renderer(w.impl).Layout(size)
+	cache.Renderer(impl).Layout(size)
 }
 
 // Position gets the current position of this widget, relative to its parent.
 func (w *BaseWidget) Position() fyne.Position {
+	w.propertyLock.RLock()
+	defer w.propertyLock.RUnlock()
```
Comment (stuartmscott) [inline widget/widget.go:86]: Use the helper methods to avoid lock/unlock

File: internal/widget/base.go (hunk 3 above)
Comment (andydotxyz) [reply internal/widget/base.go:80]: This is diferent. We don't actually refresh widget on hide - just the canvas refresh expressed below.

File: internal/widget/base.go (hunk 4 above)
Comment (andydotxyz) [reply internal/widget/base.go:113]: But we are laying out not refreshing as a result of resize

File: widget/widget.go (hunk 5 above)
Comment (andydotxyz) [reply widget/widget.go:25]: But we do not need to refresh

File: widget/widget.go (hunk 2 above)
Comment (andydotxyz) [reply widget/widget.go:49]: I don't think that's how Refresh lookup works - the extended object might provide the Refresh call, and if not then basewidget will do the lookup.

File: widget/widget.go (hunk 6 above)
Comment (andydotxyz) [reply widget/widget.go:55]: Yes, the return here meant that it would double the number of variables.
I'm thinking about a ReadAndReturn(func()) interface{} helper for these situations

File: widget/widget.go (hunk 7 above)
Comment (andydotxyz) [reply widget/widget.go:86]: As above

File: widget/widget.go (hunk 2 above)
Comment (stuartmscott) [reply widget/widget.go:49]: If impl does not define Refresh, then BaseWidget.Refresh will call Refresh on the impl's Renderer.
If impl does define Refresh, this will still call Refresh on the impl's Renderer

File: internal/widget/base.go (hunk 3 above)
Comment (stuartmscott) [reply internal/widget/base.go:80]: Hence the nil - you already have a nil check in setFieldsAndRefresh

File: internal/widget/base.go (hunk 4 above)
Comment (stuartmscott) [reply internal/widget/base.go:113]: Again the nil means you're not refreshing. You could also define setFields(func()) if you don't like passing nil

File: widget/widget.go (hunk 2 above)
Comment (andydotxyz) [reply widget/widget.go:49]: Ah yes I see your point, thanks :)

File: widget/widget.go (hunk 6 above)
Comment (stuartmscott) [reply widget/widget.go:55]: Not sure about that - the type cast may be uglier than extra variables

File: internal/widget/base.go (hunk 3 above)
Comment (andydotxyz) [reply internal/widget/base.go:80]: Oh i missed that. The nil check was really safety rather than a feature I thought should be added. using a "nil" special value is generally an anti-pattern so I would prefer an additional method over telling people to pass nil

File: widget/widget.go (hunk 6 above)
Comment (andydotxyz) [reply widget/widget.go:55]: Possible. I was going to play with it and see

File: widget/widget.go (hunk 5 above)
Comment (stuartmscott) [reply widget/widget.go:25]: Define SetFields(func()) which SetFieldsAndRefresh(func(), fyne.Widget) uses

**Comment by andydotxyz** [comment]
I have reverted the .travis update because the widget race conditions are not completely fixed.
They all pass on my computer but under other setups some are present.
The complete solution is around more safety in renderers (as you can see in #979 )
We can't merge the full solution in 1.3 without risking consumer apps locking up.
I think this PR takes it as far as possible. But we could also consider reverting the widget changes if we are concerned.

File: widget/entry.go [hunk 8]
```diff
@@ -95,17 +93,20 @@ func (e *Entry) CreateRenderer() fyne.WidgetRenderer {
 	cursor := canvas.NewRectangle(theme.FocusColor())
 	cursor.Hide()
 
-	objects := []fyne.CanvasObject{line, e.placeholderProvider(), e.textProvider(), cursor}
+	var objects []fyne.CanvasObject
+	e.SetFields(func() {
```
Comment (stuartmscott) [inline widget/entry.go:97]: Why do you need the Write lock to read line, e.placeholderProvider, e.textProvider, and cursor?

File: widget/entry.go [hunk 9]
```diff
@@ -170,35 +170,41 @@ func (e *Entry) Enable() { // TODO remove this override after ReadOnly is remove
 
 // ExtendBaseWidget is used by an extending widget to make use of BaseWidget functionality.
 func (e *Entry) ExtendBaseWidget(wid fyne.Widget) {
```
Comment (stuartmscott) [inline widget/entry.go:172]: Note: this function has slightly different behaviour now, before it would only call registerShortcut() if e.BaseWidget.impl was nil. Now it calls registerShortcut() every time. Tho I don't think that is an issue based on how ShortcutHandler is implemented - it will just replace the old shortcuts with the identical new ones.

File: widget/entry.go [hunk 10]
```diff
@@ -296,25 +312,26 @@ func (e *Entry) SetReadOnly(ro bool) {
...
-		e.Refresh()
-	} else {
-		provider := e.textProvider()
+		e.SetFieldsAndRefresh(func() {
+			e.CursorColumn = 0
+			e.CursorRow = 0
+		})
+		return
+	}
+	provider := e.textProvider()
```
Comment (stuartmscott) [inline widget/entry.go:325]: Would it be safer to move this inside SetFields so it is called while holding the lock?

File: widget/entry.go [hunk 11]
```diff
@@ -378,124 +395,131 @@ func (e *Entry) TypedKey(key *fyne.KeyEvent) {
...
+		e.SetFields(func() {
+			provider.insertAt(e.cursorTextPos(), []rune("\n"))
+			e.CursorColumn = 0
+			e.CursorRow++
+		})
 	case fyne.KeyUp:
-		if !e.MultiLine {
+		if e.GetField(func() interface{} {
+			return !e.MultiLine
+		}).(bool) {
```
Comment (stuartmscott) [inline widget/entry.go:431]: This is repeated a few times, perhaps add "func (e *Entry) IsMultiline() bool" ?

File: widget/entry.go [hunk 12]
```diff
@@ -378,124 +395,131 @@ func (e *Entry) TypedKey(key *fyne.KeyEvent) {
 
 	switch key.Name {
 	case fyne.KeyBackspace:
-		e.RLock()
-		isEmpty := provider.len() == 0 || (e.CursorColumn == 0 && e.CursorRow == 0)
-		e.RUnlock()
+		isEmpty := e.GetField(func() interface{} {
+			return provider.len() == 0 || (e.CursorColumn == 0 && e.CursorRow == 0)
```
Comment (stuartmscott) [inline widget/entry.go:399]: Apparently I can't comment on lines that haven't changed, but on line 387, is it safe to get the textProvider without read lock?

File: widget/entry.go [hunk 13]
```diff
@@ -818,15 +837,9 @@ func (e *Entry) textProvider() *textProvider {
...
-	defer e.Unlock()
-	if e.text != nil {
-		return e.text
-	}
-
 	text := newTextProvider(e.Text, e)
-	text.ExtendBaseWidget(&text)
-	e.text = &text
+	text.ExtendBaseWidget(text)
+	e.text = text
```
Comment (stuartmscott) [inline widget/entry.go:842]: Is this safe? Shouldn't this and placeholderProvider() be set with SetFields?

File: widget/entry.go [hunk 14]
```diff
@@ -849,47 +862,51 @@ func (e *Entry) textWrap() fyne.TextWrap {
...
-	if changed && e.OnChanged != nil {
-		e.OnChanged(text)
-	}
+	var callback func(string)
+	e.SetFieldsAndRefresh(func() {
+		changed := e.Text != text
+		e.Text = text
 
-	e.Refresh()
+		if changed && e.OnChanged != nil {
```
Comment (stuartmscott) [inline widget/entry.go:902]: Nil check not needed here, it is already checked at 907
```suggestion
		if changed {
```

File: widget/widget.go [hunk 15]
```diff
@@ -13,51 +15,108 @@ type BaseWidget struct {
...
+func (w *BaseWidget) ReadFields(f func()) {
+	w.propertyLock.RLock()
+	defer w.propertyLock.RUnlock()
+
+	f()
+}
 
-	w.impl = wid
+// GetField provides a guaranteed thread safe way to access fields and return a value.
+func (w *BaseWidget) GetField(f func() interface{}) interface{} {
```
Comment (stuartmscott) [inline widget/widget.go:42]: Nice

**Comment by andydotxyz** [comment]
I will come back to this in detail tomorrow. However the answer to many questions is "textProvider is special, we cannot lock in some places we want to - so instead we have to ensure the calling method is locking on it's behalf". I'm sure I missed some.

File: widget/entry.go (hunk 8 above)
Comment (andydotxyz) [reply widget/entry.go:97]: You don't this was just a shorthand to encapsulate a read, then possible write, then more reads. I can break it out into separate areas but the code will get rather ugly.

File: widget/entry.go (hunk 9 above)
Comment (andydotxyz) [reply widget/entry.go:172]: That is a good point. This takes a bit of thinking but I think overall I should change how baseimpl is locked. In this instance the method may be called a lot so the write lock is probably a bad idea if not truly required.

File: widget/entry.go (hunk 11 above)
Comment (andydotxyz) [reply widget/entry.go:431]: I'll just grab it at the top, seems seasier

File: widget/entry.go (hunk 13 above)
Comment (andydotxyz) [reply widget/entry.go:842]: This is called so frequently and also initiates other code if a new one is created that making it lock itself was too deadlocky - so I opted for it must be locked outside this method, which as you noted above I have missed a few. They are fixed now so this doesn't have to be.

**Comment by andydotxyz** [comment]
Thanks for that, all addressed and tests still passing (phew ;) )

File: widget/entry.go (hunk 13 above)
Comment (stuartmscott) [reply widget/entry.go:842]: `must be locked outside this method`

Read or Write lock?

File: widget/entry.go [hunk 16]
```diff
@@ -960,13 +977,22 @@ func (r *entryRenderer) Objects() []fyne.CanvasObject {
 
 // Refresh satisfies the fyne.WidgetRenderer interface.
 func (r *entryRenderer) Refresh() {
-	if r.entry.Text != string(r.entry.textProvider().buffer) {
-		r.entry.textProvider().SetText(r.entry.Text)
+	var provider, placeholder *textProvider
+	content := r.entry.GetField(func() interface{} {
+		provider = r.entry.textProvider()
```
Comment (stuartmscott) [inline widget/entry.go:982]: This could create the textProvider without holding a write lock

File: widget/text.go [hunk 17]
```diff
@@ -90,7 +103,7 @@ func (t *textProvider) updateRowBounds() {
 	textWrap := t.presenter.textWrap()
 	textStyle := t.presenter.textStyle()
 	textSize := theme.TextSize()
-	maxWidth := t.Size().Width - 2*theme.Padding()
+	maxWidth := t.size.Width - 2*theme.Padding()
```
Comment (stuartmscott) [inline widget/text.go:106]: The func doc should explain what lock callers must hold

File: widget/entry.go (hunk 16 above)
Comment (andydotxyz) [reply widget/entry.go:982]: are you sure? - textProvider() can write the field if there is no provider...

File: widget/text.go (hunk 17 above)
Comment (andydotxyz) [reply widget/text.go:106]: In this instance I thought it was clear - the method was an exported method so is safe (locked). As I am obtaining the lock I can access the field but not call the method that would deadlock.

File: widget/entry.go (hunk 16 above)
Comment (stuartmscott) [reply widget/entry.go:982]: But it would write the field while holding the read lock, but not the write lock

File: widget/text.go (hunk 17 above)
Comment (stuartmscott) [reply widget/text.go:106]: Yup, I mean updateRowBounds' doc should explain that callers hold lock

File: widget/entry.go (hunk 16 above)
Comment (andydotxyz) [reply widget/entry.go:982]: It is my understanding that if you have RWMutex.Lock() then nobody can .RLock() I don't think that Lock() is write-only

File: widget/text.go (hunk 17 above)
Comment (andydotxyz) [reply widget/text.go:106]: Thanks. This is an ongoing discussion about documentation that I don't think has been resolved yet.

**Comment by toaster** [comment]
Sorry for being so late to the party.
IMO methods like `GetField`, `ReadFields`, `SetFields` and `SetFieldsAndRefresh` are hard to understand. Especially they don’t relieve the developer of the burden to think about thread safety.
So, why do it this complicated way?
Why not simply provide the lock to the developer?
Why is
```go
func (t *textProvider) setText(text string) {
	t.SetFields(func() {
		t.buffer = []rune(text)
		t.updateRowBounds()
	})

	t.refreshTextRenderer()
}
```
better than
```go
func (t *textProvider) SetText(text string) {
	t.Lock()
	defer t.Unlock()
	t.buffer = []rune(text)
	t.updateRowBounds()

	t.refreshTextRenderer()
}
```

Why is
```go
func (p *infProgressRenderer) isRunning() bool {
	return p.progress.GetField(func() interface{} {
		return p.running
	}).(bool)
}
```
better than
```go
func (p *infProgressRenderer) isRunning() bool {
	t.RLock()
	defer t.RUnlock()
	return p.running
}
```

IMO the examples with the explicit lock/unlock are better to read and better to understand.

**Comment by andydotxyz** [comment]
The general concept was that for any lock it should be set in as few places as possible.
If it’s exposed to the user then a lock they forget to unlock will lock up the app, taking care of it with utility methods should help avoid that.

And it makes lock scope explicit. Defer works well if you want the lock for the whole method but in many places there are locks that must be cleared before a callback or other final items in the method...

**Comment by toaster** [comment]
Sorry, but I think the method solution is not elegant.
The methods don’t make a lock context explicit because they hide the fact that locking happens.
If I read the code which uses such a method, I am puzzled. I can’t see a lock but some kind of magic function and sometimes ugly casts.
If one wants to clarify lock context in a method where other stuff happens without the lock being in place, he should extract the locked part into a separate function. There `defer` can be used again. IMO this is much simpler and cleaner.

And I also don’t think that “forgetting to unlock a lock” is a problem that has to be solved by Fyne.

**Comment by andydotxyz** [comment]
I think there is one pattern to take into consideration (that led me down this path):
Update some fields and call refresh. The lock must be unlocked before refresh is called which makes for defer being unusable. So either:

```
wid.Lock()
wid.Thing = x
wid.Other = y
wid.Unlock()
wid.Refresh()
```
vs
```
wid.UpdateAndRefresh(func() {
    wid.Thing.x
    wid.Other = y
})
```

**Comment by toaster** [comment]
I don’t think the method is better here :).
If one doesn’t like the `Unlock` before the `Refresh` in the same method he can extract the update part:
```go
func (wid *MyWidget) updateThings(x, y …) {
  wid.Lock()
  defer wid.Unlock()
  wid.Thing = x
  wid.Other = y
}

…

  wid.updateThings(x, y)
  wid.Refresh()
```

**Comment by andydotxyz** [comment]
So in this instance it's better to expose the details and have developers implement the methods you think are not a good pattern?

**Comment by andydotxyz** [comment]
Updated in line with conversation last week. I kept an unexported setFieldsAndRefresh as it’s helpful.

File: widget/entry.go [hunk 18]
```diff
@@ -1136,10 +1171,9 @@ func (r *passwordRevealer) Cursor() desktop.Cursor {
 
 // Tapped satisfies the fyne.Tappable interface.
 func (r *passwordRevealer) Tapped(*fyne.PointEvent) {
-	r.entry.Lock()
-	r.entry.Password = !r.entry.Password
-	r.entry.Unlock()
-	r.Refresh()
+	r.entry.setFieldsAndRefresh(func() {
```
Comment (stuartmscott) [inline widget/entry.go:1174]: Should this refresh here, doesn't 1177 call Focus which calls Refresh?

Comment (andydotxyz) [reply widget/entry.go:1174]: Focus does not necessarily call refresh.
It might if the state has changed, but it's not part of the contract.
Here we are probably updating the display when we are already focused, so it's a driver detail whether or not the entry will refresh.

**Comment by andydotxyz** [comment]
Label conflict dismissed review sorry @stuartmscott

**Comment by andydotxyz** [comment]
Agreed, sorry. And now GitHub pull is not responding. Will come back to this shortly

**Comment by andydotxyz** [comment]
I used the GitHub merge tool and it somehow kept the old and the new line. This is not the first time it's happened either. I wonder if I'm not using that function correctly!

**Comment by andydotxyz** [comment]
Sigh, sorry, had to merge again, and it invalidated again sorry @stuartmscott
