### PR TITLE
Correct and expand locking from races2

### LINKED ISSUE #506: Massive data race detect!!
**Describe the bug**
Im compile my soft with option -race. After start im loock in console 23 event data race

**Device (please complete the following information):**
 - OS: Ubuntu Linux
 - Version 18.04 LTS
 - Go version 1.13.1
 - Fyne version: last stable, public download from github.

### PR DESCRIPTION
**Pull request by andydotxyz**
### Description:
Expunge more races

Fixes #506

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/driver/glfw/canvas.go [hunk 1]
```diff
@@ -162,29 +164,45 @@ func (c *glCanvas) Refresh(obj fyne.CanvasObject) {
 }
 
 func (c *glCanvas) Focus(obj fyne.Focusable) {
-	if c.focused != nil {
-		c.focused.FocusLost()
+	c.RLock()
```
Comment (stuartmscott) [inline internal/driver/glfw/canvas.go:167]: Could this be simplified to a single lock/unlock?

```go
c.Lock()
prev := c.focused
c.focused = obj
c.Unlock()

if prev != nil {
    prev.FocusLost()
}
if obj != nil {
    obj.FocusGained()
}
```
Ditto for Unfocus

Comment (andydotxyz) [reply internal/driver/glfw/canvas.go:167]: It could, but somehow it felt "right" to notify FocusLost before the new focus item was set... Maybe I was overly cautious?

Comment (stuartmscott) [reply internal/driver/glfw/canvas.go:167]: It is currently two lines longer than the suggestion, and besides that I don't think there is anything to be gained so let's keep it as is
