### PR TITLE
Fix undo/redo for multi byte runes

### LINKED ISSUE #5001: Typing Chinese characters in widget.Entry and perform undo/redo crashes the app.
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

widget.Entry undo/redo is not compatiable with Chinese characters. Undo/Redo crashes the app when dealing with multiple Chinese characters.

### How to reproduce

1. Create a text entry
2. Type random Chinese characters (for example, 测试) in the text entry
3. Call Undo()/Redo() or use the corresponding hotkey
4. Observe that the text entry transits into error states

//to crash the app
1. Create a text entry
2. Type random Chinese characters (for example, 测试) in the text entry
3. Select all and delete
4. Perform Undo() twice (ctrl + Z)
5. Observe that fyne crashes

### Screenshots

image
image
image

### Example code

Create text entry widget, type in Chinese characters, press ctrl + z, ctrl + y to perform undo and redo.

### Fyne version

2.5.0

### Go compiler version

1.22

### Operating system and version

Windows 10

### Additional Information

At: home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/internal/driver/glfw/driver_desktop.go:171
panic: runtime error: slice bounds out of range [4:2]

goroutine 11 [running]:
fyne.io/fyne/v2/widget.(*entryModifyAction).sub(...)
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/widget/entry.go:2316
fyne.io/fyne/v2/widget.(*entryModifyAction).Undo(0xc000f55ea0?, {0xc0053aadbe?, 0x7ff6a4a23872?})
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/widget/entry.go:2297 +0x90
fyne.io/fyne/v2/widget.(*entryUndoStack).Undo(0xc000d7fc08?, {0xc0053aadbe?, 0x7f0000c000f55ed8?})
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/widget/entry.go:2378 +0x4c
fyne.io/fyne/v2/widget.(*Entry).Undo(0xc000d7fc08)
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/widget/entry.go:787 +0x49
fyne.io/fyne/v2/widget.(*Entry).registerShortcut.func1({0xc000d7fc58?, 0x7ff6a5349920?})
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/widget/entry.go:1160 +0x17
fyne.io/fyne/v2.(*ShortcutHandler).TypedShortcut(0xc000d7fc58, {0x7ff6a55c8580, 0x7ff6a5b67b80})
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/shortcut.go:21 +0x6e
fyne.io/fyne/v2/widget.(*Entry).TypedShortcut(0xc0002eca20?, {0x7ff6a55c8580?, 0x7ff6a5b67b80?})
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/widget/entry.go:966 +0x25
fyne.io/fyne/v2/internal/driver/glfw.(*window).triggersShortcut.func1()
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/internal/driver/glfw/window.go:912 +0x24
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(...)
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/internal/driver/common/window.go:35
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1 in goroutine 1
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/internal/driver/glfw/window.go:997 +0x136
2024/07/18 00:06:27 exit status 2
exit status 1

### PR DESCRIPTION
**Pull request by NicolasPerrenoud**
### Description:
The position in entry is the index in a rune slice. But the implementation of the undo/redo use it as an index in a string. This works for runes that are 1 byte long. But It was broken for longer runes.

I fixed the implementation of undo/redo to index a rune slices instead of the string directly

Fixes #5001

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: widget/entry.go [hunk 1]
```diff
@@ -792,7 +790,7 @@ func (e *Entry) Undo() {
 	}
 	pos := modify.Position
 	if modify.Delete {
-		pos += len(modify.Text)
+		pos += len([]rune(modify.Text))
```
Comment (dweymouth) [inline widget/entry.go:793]: Here and anywhere else you want the length of a string in runes, it should be more efficient to use `utf8.RuneCountInString(modify.Text)` which avoids an allocation

**Review by dweymouth — CHANGES_REQUESTED** [review]
Looks good, thanks for looking into this! One comment for efficiency

**Review by andydotxyz — COMMENTED** [review]
Thanks so much for this excellent catch.
I wonder if it might be more efficient to store the `[]rune` instead of `string` in the undo action, and probably could change `deleteFromTo` to avoid the string conversion as well. Should reduce allocations.

**Comment by andydotxyz** [comment]
Please base pull requests off the `develop` branch, not `master`.

**Comment by NicolasPerrenoud** [comment]
Thank you for your feedback. I implemented your proposals. Also I fixed text replacement that had similar issue.

File: widget/entry.go [hunk 2]
```diff
@@ -2308,12 +2305,14 @@ func (i *entryModifyAction) Redo(s string) string {
 
 // Inserts Text
 func (i *entryModifyAction) add(s string) string {
```
Comment (dweymouth) [inline widget/entry.go:2307]: We have casting to strings that result in allocations here and in `sub` now. Would refactoring these to receive and return []rune result in fewer castings still?

Comment (andydotxyz) [reply widget/entry.go:2307]: It looks like that opens a can of worms. as the undo/redo stack passes it up and down, with the source being `Entry.Text` which is `string`. I agree it would be a good improvement but probably could be another PR.

**Review by andydotxyz — APPROVED** [review]
Looks good to me, I think we need @dweymouth OK as well so I dropped a comment in.
