### PR TITLE
Fix #828: tab container update handling

### LINKED ISSUE #828: develop: Broken layout of embedded TabContainer when using Append
Hello,

I noticed a regression with tabs using the develop branch (v1.2.4-0.20200406152143-ddca854edfa1 in go.mod).

Using the following example:

```go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	app := app.New()
	win := app.NewWindow("Window")
	win.SetMaster()

	tabs := widget.NewTabContainer()
	tabs.Append(
		widget.NewTabItem("Tab 1", widget.NewVBox(
			widget.NewRadio([]string{
				"A",
				"B",
				"C",
			}, nil),
			widget.NewTabContainer(
				widget.NewTabItem(
					"Test Inner 1-1",
					widget.NewVBox(widget.NewLabel("Test Inner 1-1")),
				),
				widget.NewTabItem(
					"Test Inner 1-2",
					widget.NewVBox(widget.NewLabel("Test Inner 1-2")),
				),
			),
		)),
	)
	tabs.Append(
		widget.NewTabItem("Tab 2", widget.NewVBox(
			widget.NewRadio([]string{
				"D",
				"E",
			}, nil),
			widget.NewTabContainer(
				widget.NewTabItem(
					"Test Inner 2-1",
					widget.NewVBox(widget.NewLabel("Test Inner 2-1")),
				),
				widget.NewTabItem(
					"Test Inner 2-2",
					widget.NewVBox(widget.NewLabel("Test Inner 2-2")),
				),
			),
		)),
	)

	win.SetContent(tabs)
	win.ShowAndRun()
}
```

The resulting windows looks like this:

fyne-develop-tab-issue

After clicking on one of the tabs, this gets fixed:

fyne-develop-tab-after-click

Note that the radio buttons don't appear correctly. This only seems to happen on Windows (at least the radio buttons were correct when I tried on ArchLinux).

The same code with Fyne 1.2.3:

fyne-1 2 3

However, when we add the tab items directly in `NewTabContainer` instead of using `Append`, the same issue doesn't happen (with both 1.2.3 and ed30d6786124c2c34e9d454076901df3e3830ca8):

```go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	app := app.New()
	win := app.NewWindow("Window")
	win.SetMaster()

	tabs := widget.NewTabContainer(
		widget.NewTabItem("Tab 1", widget.NewVBox(
			widget.NewRadio([]string{
				"A",
				"B",
				"C",
			}, nil),
			widget.NewTabContainer(
				widget.NewTabItem(
					"Test Inner 1-1",
					widget.NewVBox(widget.NewLabel("Test Inner 1-1")),
				),
				widget.NewTabItem(
					"Test Inner 1-2",
					widget.NewVBox(widget.NewLabel("Test Inner 1-2")),
				),
			),
		)),
		widget.NewTabItem("Tab 2", widget.NewVBox(
			widget.NewRadio([]string{
				"D",
				"E",
			}, nil),
			widget.NewTabContainer(
				widget.NewTabItem(
					"Test Inner 2-1",
					widget.NewVBox(widget.NewLabel("Test Inner 2-1")),
				),
				widget.NewTabItem(
					"Test Inner 2-2",
					widget.NewVBox(widget.NewLabel("Test Inner 2-2")),
				),
			),
		)),
	)

	win.SetContent(tabs)
	win.ShowAndRun()
}
```

### Device (please complete the following information):
 - OS: Windows
 - Version: 10
 - Go version: 1.14.1
 - Fyne version: ed30d6786124c2c34e9d454076901df3e3830ca8

### PR DESCRIPTION
**Pull request by toaster**
### Description:

This PR refactors the tab container widget’s update handling and fixes issues when adding/removing items to an existing tab container.
It also removes the tab container widget’s dependency from the renderer cache.
As a side-effect it introduces `TabContainer.SetItems` which might be used to replace the tab items completely.

Fixes #828

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style.

### CODE REVIEW

File: widget/tabcontainer.go [hunk 1]
```diff
@@ -349,34 +296,97 @@ func (r *tabContainerRenderer) Refresh() {
...
+		return false
+	}
+	if r.tabLoc != r.container.tabLocation {
+		return false
+	}
+	if len(r.objects) != len(r.container.Items) {
+		return false
+	}
+	for i, item := range r.container.Items {
+		if item.Content != r.objects[i] {
```
Comment (andydotxyz) [inline widget/tabcontainer.go:355]: What about if the tab text or icon changes?

File: widget/tabcontainer.go [hunk 2]
```diff
@@ -349,34 +296,97 @@ func (r *tabContainerRenderer) Refresh() {
...
+	r.tabLoc = r.container.tabLocation
+	var iconPos buttonIconPosition
+	if fyne.CurrentDevice().IsMobile() || r.container.tabLocation == TabLocationLeading || r.container.tabLocation == TabLocationTrailing {
+		iconPos = buttonIconTop
+	} else {
+		iconPos = buttonIconInline
+	}
+	var buttons, objects []fyne.CanvasObject
+	for i, item := range r.container.Items {
+		button := r.buildButton(item, iconPos)
```
Comment (andydotxyz) [inline widget/tabcontainer.go:376]: Is it not worth re-using the existing buttons, if there are enough?

File: widget/tabcontainer.go (hunk 1 above)
Comment (toaster) [reply widget/tabcontainer.go:355]: Okay, I’m not sure if this really is a use case but it can be done, so I’ll add a test for this.

File: widget/tabcontainer.go (hunk 2 above)
Comment (toaster) [reply widget/tabcontainer.go:376]: I don’t think so.
1. A tab container usually doesn’t have more than a couple of tabs.
2. Modifying the tab list probably doesn’t happen that often.
3. Checking if an item is reusable introduces a complexity with limited use (see 1. and 2.)

**Comment by toaster** [comment]
> It is more difficult to review the logic changes when the file has been re-ordered this much, but overall the code quality is higher, there are more tests, and test images are grouped by widget.

You didn’t reviewed all commits at once, didn’t you?
In retrospect I’d say I could have done the refactoring in smaller steps. I only wanted to refactor the tests to add a test for #828 and then it turned out that a lot of already tested cases were broken (visually) and then I fixed them :/.

File: widget/tabcontainer.go [hunk 3]
```diff
@@ -70,31 +70,16 @@ func NewTabItemWithIcon(text string, icon fyne.Resource, content fyne.CanvasObje
 
 // Append adds a new TabItem to the rightmost side of the tab panel
 func (c *TabContainer) Append(item *TabItem) {
-	r := cache.Renderer(c).(*tabContainerRenderer)
-	c.Items = append(c.Items, item)
-	r.objects = append(r.objects, item.Content)
-	r.tabBar.Objects = append(r.tabBar.Objects, c.makeButton(item))
-
+	c.SetItems(append(c.Items, item))
 	c.Refresh()
```
Comment (stuartmscott) [inline widget/tabcontainer.go:73]: SetItems already calls Refresh

**Comment by toaster** [comment]
@stuartmscott @andydotxyz I merged by hand and that dismissed the approvals, sorry.

**Comment by toaster** [comment]
Notable changes due to the merge:
- all tab container rendering tests had to be separated into mobile and desktop
- software painter now renders centred or right adjusted text correctly
