### PR TITLE
Remove incorrect early return from Rectangle.Resize

### LINKED ISSUE #6040: Low frame rate with animated rectangles on 2.7.x
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

There seems to have been a regression in animating sizes of rectangles between 2.6.x and 2.7.x

### How to reproduce

Run the example code on 2.6.x and 2.7.x. It runs the peak meter visualization from Supersonic with random peak data to demonstrate the differences in animation smoothness.

In my tests it gets good frame rate on 2.6.x all the way through 2.6.3 (last point release), and has bad frame rate on both 2.7.0 and 2.7.1

### Screenshots

_No response_

### Example code

```go
// The code starts:
package main

import (
	"fmt"
	"image/color"
	"math"
	"math/rand/v2"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

const (
	meterRangeDB       = 62
	rmsSmoothingFactor = 0.8
	peakHoldFrames     = 60

	noiseFloorDB = -96
)

type PeakMeter struct {
	widget.BaseWidget
	lPeak          float64
	rPeak          float64
	lRMS           float64
	rRMS           float64
	lPeakHold      float64
	rPeakHold      float64
	lPeakHoldFrame uint64
	rPeakHoldFrame uint64
	frameCounter   uint64
}

func NewPeakMeter() *PeakMeter {
	p := &PeakMeter{
		lPeak:     noiseFloorDB,
		rPeak:     noiseFloorDB,
		lRMS:      noiseFloorDB,
		rRMS:      noiseFloorDB,
		lPeakHold: noiseFloorDB,
		rPeakHold: noiseFloorDB,
	}
	p.ExtendBaseWidget(p)
	return p
}

// UpdatePeaks updates the peaks that are displayed in the meter.
// This function is expected to be called from a fyne.Animation callback,
// running at 60 Hz
func (p *PeakMeter) UpdatePeaks(lPeak, rPeak, lRMS, rRMS float64) {
	p.lPeak = lPeak
	p.rPeak = rPeak
	lRMS = math.Max(noiseFloorDB, lRMS)
	rRMS = math.Max(noiseFloorDB, rRMS)
	p.lRMS = rmsSmoothingFactor*p.lRMS + (1-rmsSmoothingFactor)*lRMS
	p.rRMS = rmsSmoothingFactor*p.rRMS + (1-rmsSmoothingFactor)*rRMS

	if lPeak > p.lPeakHold || p.frameCounter-p.lPeakHoldFrame > peakHoldFrames {
		p.lPeakHold = lPeak
		p.lPeakHoldFrame = p.frameCounter
	}
	if rPeak > p.rPeakHold || p.frameCounter-p.rPeakHoldFrame > peakHoldFrames {
		p.rPeakHold = rPeak
		p.rPeakHoldFrame = p.frameCounter
	}

	p.frameCounter++
	p.Refresh()
}

func (p *PeakMeter) CreateRenderer() fyne.WidgetRenderer {
	return newPeakMeterRenderer(p)
}

type peakMeterRenderer struct {
	p *PeakMeter

	lLabel        canvas.Text
	rLabel        canvas.Text
	lPeakRect     canvas.Rectangle
	rPeakRect     canvas.Rectangle
	lRMSRect      canvas.Rectangle
	rRMSRect      canvas.Rectangle
	lPeakHoldRect canvas.Rectangle
	rPeakHoldRect canvas.Rectangle

	rulerLines  []canvas.Rectangle
	rulerLabels []canvas.Text

	objects []fyne.CanvasObject

	fgColor   color.Color
	bgColor   color.Color
	ruleColor color.Color
}

func newPeakMeterRenderer(pm *PeakMeter) *peakMeterRenderer {
	p := &peakMeterRenderer{p: pm}
	p.lLabel.Text = "L"
	p.rLabel.Text = "R"
	numRules := int(math.Ceil(float64(meterRangeDB) / 10))
	p.rulerLines = make([]canvas.Rectangle, numRules)
	p.rulerLabels = make([]canvas.Text, numRules)
	x := 0
	for i := range p.rulerLabels {
		p.rulerLabels[i].Text = fmt.Sprintf("%d dB", x)
		p.rulerLabels[i].Resize(p.rulerLabels[i].MinSize())
		x -= 10
	}
	p.Layout(pm.Size())

	return p
}

func (l *peakMeterRenderer) MinSize() fyne.Size {
	return fyne.NewSize(275, 75)
}

func (l *peakMeterRenderer) Layout(size fyne.Size) {
	topSpacing := float32(5)
	lrLabelWidth := float32(20)
	overflowWidth := float32(10)
	ruleLabelHeight := float32(10)
	meterWidth := size.Width - lrLabelWidth - overflowWidth - topSpacing

	lPeakWidth := float32(math.Max(0, meterRangeDB+l.p.lPeak)/meterRangeDB) * meterWidth
	rPeakWidth := float32(math.Max(0, meterRangeDB+l.p.rPeak)/meterRangeDB) * meterWidth
	lRMSWidth := float32(math.Max(0, meterRangeDB+l.p.lRMS)/meterRangeDB) * meterWidth
	rRMSWidth := float32(math.Max(0, meterRangeDB+l.p.rRMS)/meterRangeDB) * meterWidth
	lPeakHoldPos := float32(math.Max(0, meterRangeDB+l.p.lPeakHold)/meterRangeDB) * meterWidth
	rPeakHoldPos := float32(math.Max(0, meterRangeDB+l.p.rPeakHold)/meterRangeDB) * meterWidth

	barSpacing := float32(2)
	barHeight := size.Height/2 - barSpacing - ruleLabelHeight

	labelMin := l.lLabel.MinSize()
	l.lLabel.Move(fyne.NewPos(4, (barHeight-labelMin.Height)/2+topSpacing))
	l.lLabel.Resize(l.lLabel.MinSize())
	l.rLabel.Move(fyne.NewPos(4, barHeight+barSpacing+topSpacing+(barHeight-labelMin.Height)/2))

	l.lPeakRect.Move(fyne.NewPos(lrLabelWidth, topSpacing))
	l.lPeakRect.Resize(fyne.NewSize(lPeakWidth, barHeight))
	l.rPeakRect.Move(fyne.NewPos(lrLabelWidth, barHeight+barSpacing+topSpacing))
	l.rPeakRect.Resize(fyne.NewSize(rPeakWidth, barHeight))
	l.lRMSRect.Move(fyne.NewPos(lrLabelWidth, topSpacing))
	l.lRMSRect.Resize(fyne.NewSize(lRMSWidth, barHeight))
	l.rRMSRect.Move(fyne.NewPos(lrLabelWidth, barHeight+barSpacing+topSpacing))
	l.rRMSRect.Resize(fyne.NewSize(rRMSWidth, barHeight))

	peakHoldWidth := theme.SeparatorThicknessSize() * 2
	l.lPeakHoldRect.Move(fyne.NewPos(lPeakHoldPos+lrLabelWidth, topSpacing))
	l.lPeakHoldRect.Resize(fyne.NewSize(peakHoldWidth, barHeight))
	l.rPeakHoldRect.Move(fyne.NewPos(rPeakHoldPos+lrLabelWidth, barHeight+barSpacing+topSpacing))
	l.rPeakHoldRect.Resize(fyne.NewSize(peakHoldWidth, barHeight))

	ruleWidth := peakHoldWidth * 0.667
	x := lrLabelWidth + meterWidth
	for i := range l.rulerLines {
		bottom := (barHeight + barSpacing) * 2
		l.rulerLines[i].Move(fyne.NewPos(x, topSpacing))
		l.rulerLines[i].Resize(fyne.NewSize(ruleWidth, bottom))
		l.rulerLabels[i].Move(fyne.NewPos(x-10, bottom+topSpacing))
		x -= meterWidth * (10 / float32(meterRangeDB))
	}
}

func (l *peakMeterRenderer) Refresh() {
	foreground := theme.ForegroundColor()
	background := theme.BackgroundColor()
	errC := theme.ErrorColor()
	c := color.NRGBAModel.Convert(theme.PrimaryColor()).(color.NRGBA)
	c.A = 128
	l.lLabel.Color = foreground
	l.rLabel.Color = foreground
	l.lLabel.TextSize = 16
	l.rLabel.TextSize = 16
	l.lLabel.TextStyle.Bold = true
	l.rLabel.TextStyle.Bold = true
	l.lPeakRect.FillColor = c
	l.rPeakRect.FillColor = c
	l.lRMSRect.FillColor = c
	l.rRMSRect.FillColor = c

	if l.p.lPeakHold >= -0.00001 {
		l.lPeakHoldRect.FillColor = errC
	} else {
		l.lPeakHoldRect.FillColor = foreground
	}
	if l.p.rPeakHold >= -0.00001 {
		l.rPeakHoldRect.FillColor = errC
	} else {
		l.rPeakHoldRect.FillColor = foreground
	}

	if foreground != l.fgColor || background != l.bgColor {
		l.ruleColor = BlendColors(foreground, background, 0.5)
		l.fgColor = foreground
		l.bgColor = background
	}
	for i := range l.rulerLines {
		l.rulerLines[i].FillColor = l.ruleColor
		l.rulerLabels[i].TextSize = 11
	}

	l.Layout(l.p.Size())
}

func (l *peakMeterRenderer) Objects() []fyne.CanvasObject {
	if l.objects == nil {
		l.objects = make([]fyne.CanvasObject, 0, 2*len(l.rulerLines)+8)
		for i := range l.rulerLines {
			l.objects = append(l.objects, &l.rulerLines[i], &l.rulerLabels[i])
		}
		l.objects = append(l.objects,
			&l.lLabel, &l.rLabel,
			&l.lPeakRect, &l.rPeakRect,
			&l.lRMSRect, &l.rRMSRect,
			&l.lPeakHoldRect, &l.rPeakHoldRect)
	}
	return l.objects
}

func (l *peakMeterRenderer) Destroy() {
}

func BlendColors(a, b color.Color, fractionA float64) color.Color {
	ra, ga, ba, aa := a.RGBA()
	rb, gb, bb, ab := b.RGBA()

	fractionB := 1 - fractionA
	rAvg := uint8(float64(ra/257)*fractionA + float64(rb/257)*fractionB)
	gAvg := uint8(float64(ga/257)*fractionA + float64(gb/257)*fractionB)
	bAvg := uint8(float64(ba/257)*fractionA + float64(bb/257)*fractionB)
	aAvg := uint8(float64(aa/257)*fractionA + float64(ab/257)*fractionB)
	return color.RGBA{R: rAvg, G: gAvg, B: bAvg, A: aAvg}
}

func main() {
	a := app.New()
	w := a.NewWindow("Peak Meter Test")
	pm := NewPeakMeter()
	w.SetContent(pm)

	lPeak := -10.0
	rPeak := -10.0
	lRMS := -25.0
	rRMS := -25.0
	fyne.NewAnimation(99999*time.Hour, func(_ float32) {
		lPeak += rand.NormFloat64()
		rPeak += rand.NormFloat64()
		lRMS += rand.NormFloat64()
		rRMS += rand.NormFloat64()
		pm.UpdatePeaks(lPeak, rPeak, lRMS, rRMS)
	}).Start()

	w.ShowAndRun()
}
```

### Fyne version

2.7.1

### Go compiler version

1.24

### Operating system and version

Windows 11, Mac

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dweymouth**
### Description:

Fixes #6040 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: canvas/rectangle.go [hunk 1]
```diff
@@ -80,10 +80,6 @@ func (r *Rectangle) Resize(s fyne.Size) {
 	}
 
 	r.baseObject.Resize(s)
-	if r.StrokeWidth == 0 {
```
Comment (andydotxyz) [inline canvas/rectangle.go:83]: Instead of removing this optimisation (which will mean we repaint rectangles that could avoid it) it should be fixed by adding `repaint(r)` before the `return`.

**Review by andydotxyz — DISMISSED** [review]
I have provided what should be a more optimal solution in comments.

If I was wrong then what is here is fine.

File: canvas/rectangle.go (hunk 1 above)
Comment (andydotxyz) [reply canvas/rectangle.go:83]: Repaint just signals we have made a change, but it does not invalidated caches or force a re-rasterisation.

It is also possible that all of rectangle could just use this path now that stroke drawing is in the shader too...

Comment (dweymouth) [reply canvas/rectangle.go:83]: I updated it so it all goes through the repaint path, but now that I think about it, for the software renderer, doesn't even a strokeless rectangle need a Refresh because it has cached CPU-drawn textures?

Comment (andydotxyz) [reply canvas/rectangle.go:83]: That is a very good question - but doesn't the software driver re-paint everything for each frame?

Comment (dweymouth) [reply canvas/rectangle.go:83]: I don't know, I'm not very familiar with the software driver. Just conceptually, I can see why Move would be just a repaint and resize a Refresh - unless for all drivers, rectangles are painted without a cached pixel texture every time.

Comment (andydotxyz) [reply canvas/rectangle.go:83]: Fair. I just thought the difference might matter given this was opened in response to a performance issue?

Comment (dweymouth) [reply canvas/rectangle.go:83]: It turned out to not be a performance issue -- it was the latent bug here masquerading as what I assumed was a performance issue. It was triggered when an optimization was added to Move making it a proper no-op when the requested position is the same as the current. My code was Resizeing and Moving the rectangles each frame, but most of the Moves were no-ops, which used to trigger a repaint but now (correctly) did not. But the Resize hit the StrokeWidth early return which stopped any repaint/refresh from being issued.

Comment (andydotxyz) [reply canvas/rectangle.go:83]: Ah yes of course I see, thanks. I guess that means the conclusion is to return to a `Refresh` call?

**Review by redawl — COMMENTED** [review]
Does this need to be fixed for Bezier curve too?

**Comment by dweymouth** [comment]
> Does this need to be fixed for Bezier curve too?

Good catch! Updated

**Review by redawl — APPROVED** [review]
