### PR TITLE
bugfixes for refreshing min sizes of components and the window

### LINKED ISSUE #264: window size does not grow if content's minSize gets bigger (aka “The minSize bug”)
If the minSize of the content of a window gets bigger than the window, the window does not grow.
Also it is possible to reducde the window's size to its former minSize after enlarging it manually.

### LINKED ISSUE #265: initial scaling wrong on external MacOS displays
When starting a fyne app on an external MacOS display (with another resolution than the internal one) the window is not scaled correctly until the first move of the window.

Side effect: on the first move the window gets rescaled and the effects of #264 are fixed (until the next minSize change).

### PR DESCRIPTION
**Pull request by toaster**
this fixes #264 
this removes the effects of and thus practically fixes #265, too

**update**: the effects of #265 are fixed, i.e. the scaling is right now. But because the initial computation of the window size is still wrong, the window is larger than necessary. However, it can be reduced to the actual minSize.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Is this the "minSize bug" fix? :)

I can see that it resolves the issue but the paint() function now has a few side effects. It is resizing, painting and also returning a declaration of size change.
I think it may be cleaner if split into "updateMinSize() bool" and "paint()" so they do less and have clearer responsibilities. Then loop would calculate size, update window if needed, then paint. This seems clearer and potentially more correct as we should then be painting into the correct canvas size.

**Comment by toaster** [comment]
* separated minSize adjustment and painting
* added a comment on the fixed issues

File: internal/driver/gl/window.go [hunk 1]
```diff
@@ -220,14 +220,12 @@ func (w *window) SetPadded(padded bool) {
...
+	runOnMain(w.resizeToContent)
 }
 
 func (w *window) resizeToContent() {
-	runOnMain(func() {
-		w.fitContent()
-		w.viewport.SetSize(w.screenSize(w.Canvas().Content().Size()))
-	})
+	w.fitContent()
+	w.viewport.SetSize(w.screenSize(w.Canvas().Content().Size()))
```
Comment (andydotxyz) [inline internal/driver/gl/window.go]: This must be run on the main thread. If we remove the safety within the method then it could be called incorrectly again.
I know you have reason for the change - but I'm not sure what?

Comment (toaster) [reply internal/driver/gl/window.go]: The loop already runs on the main thread and leaving the guard in the method didn't work.
I didn't figure out why.
