### PR TITLE
Bugfix: #675 - support scrollable menus

### LINKED ISSUE #675: Select widgets with many options overflow UI without scrolling
### Describe the bug:
If a select widget has more options than the window can handle, they overflow without any way to scroll and select items off screen.

### To Reproduce:
Build an app with the code below. 

### Screenshots:
Screen Shot 2020-02-13 at 1 19 00 AM

### Example code:
```go
	a := app.New()
	w := a.NewWindow("Test")
	form := &widget.Form{
		OnCancel: func() {
			fmt.Println("Cancelled")
		},
		OnSubmit: func() {
			fmt.Println("Submitted")
		},
	}
	s := []string{"1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23"}
	test := widget.NewSelect(s, func(string) {})
	form.Append("Test", test)

	w.SetContent(widget.NewVBox(
		form,
	))

	w.Resize(fyne.NewSize(800, 600))
	w.ShowAndRun()
```

### Device (please complete the following information):
 - OS: MacOS
 - Version: 10.15.3
 - Go version: 1.13
 - Fyne version: 1.2.2

### PR DESCRIPTION
**Pull request by toaster**
### Description:

This PR fixes #675 by providing support for scrollable menus.
It includes a lot of refactoring without change in behaviour (I hope ;)).

Fixes #675

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: widget/menu_desktop_test.go [hunk 1]
```diff
@@ -44,7 +44,7 @@ func TestMenu_Layout(t *testing.T) {
 		"normal": {
 			windowSize: fyne.NewSize(500, 300),
 			menuPos:    fyne.NewPos(10, 10),
-			wantImage:  "menu_layout_normal.png",
+			wantImage:  "menu/layout_normal.png",
```
Comment (stuartmscott) [inline widget/menu_desktop_test.go:47]: menu/desktop/layout_normal.png?

File: widget/menu_mobile_test.go [hunk 2]
```diff
@@ -44,7 +44,7 @@ func TestMenu_Layout(t *testing.T) {
 		"normal": {
 			windowSize: fyne.NewSize(500, 300),
 			menuPos:    fyne.NewPos(10, 10),
-			wantImage:  "menu_layout_normal.png",
+			wantImage:  "menu/layout_normal.png",
```
Comment (stuartmscott) [inline widget/menu_mobile_test.go:47]: menu/mobile/layout_normal.png?

File: widget/menu_desktop_test.go (hunk 1 above)
Comment (stuartmscott) [reply widget/menu_desktop_test.go:47]: Unless menu/desktop/layout_normal.png and menu/mobile/layout_normal.png should be the same?

File: internal/layout/box.go [hunk 3]
```diff
@@ -10,6 +10,7 @@ var _ fyne.Layout = (*Box)(nil)
 // Box is a box layout for stacking a number of child canvas objects horizontally or vertically.
 type Box struct {
 	Horizontal        bool
+	PadBeforeAndAfter bool
```
[the remark this answers is not in the document]
Comment (toaster) [reply internal/layout/box.go:13]: Learned a new word today :).
But it is not the right in this context. Interstitial padding is always added. This flag is for additional padding before or after the objects.

File: widget/menu_desktop_test.go (hunk 1 above)
Comment (toaster) [reply widget/menu_desktop_test.go:47]: Yes, they should. That’s why I put them into `menu/` not `menu/desktop` or `menu/mobile`.

File: internal/layout/box.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (andydotxyz) [reply internal/layout/box.go:13]: Can you expand on why this is needed please? If we were using the old popup style menus the padding would already be provided but that was removed.

[the remark this answers is not in the document]
Comment (andydotxyz) [reply internal/layout/box.go:13]: Oh wow I only just realised that this used to be layout/Box but now is internal/layout/Box.

I’m getting quite nervous about the number of things we are pulling into internal so that we can make changes that otherwise would add public APIs.

[the remark this answers is not in the document]
Comment (toaster) [reply internal/layout/box.go]: I reverted the layout change.

File: widget/menu_desktop_test.go (hunk 1 above)
Comment (andydotxyz) [reply widget/menu_desktop_test.go:50]: I don't understand why some of these menu tests are desktop specific, they don't seem to access desktop features or avoid mobile limitations?
To stuart's comment above if half of this is not a desktop test, perhaps it does not belong in a file ending in `_desktop_test`?
