### PR TITLE
Fix: DocTabItem update text doesn't update the underline select bar

### LINKED ISSUE #3106: DocTabItem update text doesn't update the underline select bar (graphic glitch)
### Describe the bug:
When modifiying the text of a TabItem with a longer text, the underline blue bar (tab select mark) length doen't update to cover the entire tabitem length, until the item is clicked.

### To Reproduce:
Run the code, and click the button

### Screenshots:
image
image

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("TEST")

	tab := container.NewDocTabs()
	tab.Append(&container.TabItem{
		Text: "Test",
		Content: container.NewCenter(
			widget.NewButton("Set Text", func() {
				tab.Items[0].Text = "Longer text to show the bug"
				tab.Refresh()
			}),
		),
	})

	w.SetContent(tab)

	w.Resize(fyne.NewSize(800, 500))
	w.CenterOnScreen()
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10.0.18363.2212
 - **Go version:** 1.18.2
 - **Fyne version:** 2.2.1

### PR DESCRIPTION
**Pull request by cedy**
### Description:

Fixes #3106

I had to change `dynamic_appended_and_removed.xml` expected size of rectangle indicator bar for tests to pass due to a new logic.

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: container/doctabs.go [hunk 1]
```diff
@@ -372,11 +372,17 @@ func (r *docTabsRenderer) updateIndicator(animate bool) {
 		if a := r.action; a != nil {
 			selectedPos = a.Position()
 			selectedSize = a.Size()
+			if a.MinSize().Width > selectedSize.Width {
+				selectedSize = a.MinSize()
+			}
```
Comment (Jacalz) [inline container/doctabs.go:377]: Should we perhaps do it like this instead? We avoid calling MinSize() twice and I suspect it protects us if the size changes between the two function calls. Applies to the other place as well.  
```suggestion
			minSize := a.MinSize()
			if minSize.Width > selectedSize.Width {
				selectedSize = minSize
			}
```

**Review by Jacalz — CHANGES_REQUESTED** [review]
Thanks for the fix. I just had a small suggestion :)

File: container/doctabs.go (hunk 1 above)
Comment (cedy) [reply container/doctabs.go]: 👍

**Review by andydotxyz — APPROVED** [review]
Nice thanks

**Comment by andydotxyz** [comment]
Am sure @Jacalz will like the changes too :)

**Review by Jacalz — APPROVED** [review]
> Am sure @Jacalz will like the changes too :)

Indeed. Sorry for the wait...

**Comment by Jacalz** [comment]
@andydotxyz Would you mind backporting to the release branch?
