### PR TITLE
Fix the slider min size to include the inner padding amount

### LINKED ISSUE #4714: Label and Slider not aligned in a FormItem
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When creating a FormItem with a Label and a Slider the alignement of the label and the slider does not look correct.

### How to reproduce

Create a FormItem with label and slice.

### Screenshots

image

### Example code

```
details := widget.NewForm(
		widget.NewFormItem("Title", widget.NewEntry()),
		widget.NewFormItem("Description", widget.NewMultiLineEntry()),
		widget.NewFormItem("Category", widget.NewSelect(
			[]string{"Home"},
			func(s string) {})),
		widget.NewFormItem("Priority", widget.NewRadioGroup(
			[]string{"Low", "Mid", "High"},
			func(s string) {})),
		widget.NewFormItem("Due", widget.NewEntry()),
		widget.NewFormItem("Completion", widget.NewSlider(0, 100))4,
	)
```

### Fyne version

fyne cli version: v2.4.4

### Go compiler version

go1.22.0 darwin/amd64

### Operating system and version

macOS Sonoma 14.3.1

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #4714

Screenshot 2024-04-19 at 09 57 42

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: widget/slider.go [hunk 1]
```diff
@@ -523,17 +523,18 @@ func (s *sliderRenderer) Layout(size fyne.Size) {
 
 // MinSize calculates the minimum size of a widget.
 func (s *sliderRenderer) MinSize() fyne.Size {
-	dia := s.slider.buttonDiameter(s.slider.Theme().Size(theme.SizeNameInlineIcon))
-	s1, s2 := minLongSide+dia, dia
+	th := s.slider.Theme()
+	pad := th.Size(theme.SizeNameInnerPadding)
+	dia := s.slider.buttonDiameter(th.Size(theme.SizeNameInlineIcon))
```
Comment (dweymouth) [inline widget/slider.go:528]: Switching the order of this and the line below it allows you to only invoke `th.Size(theme.SizeNameInlineIcon)` once and just pass the computed value to buttonDiameter

**Review by dweymouth — CHANGES_REQUESTED** [review]

File: widget/slider.go (hunk 1 above)
Comment (andydotxyz) [reply widget/slider.go]: Thanks for this, updated accordingly

**Review by dweymouth — APPROVED** [review]
