### PR TITLE
internal/driver/mobile: clear touchIDs at every touch end event

### LINKED ISSUE #2407: Runtime panic because out of touchID
### Describe the bug:

While debugging #2406 , a runtime panic crashes the app. Here is a stack trace:

```
panic: out of touchIDs

goroutine 1 [running, locked to thread]:
github.com/fyne-io/mobile/app.sendTouch(0x130127b98, 0x10404a2a0, 0x30127b98, 0x1)
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/app/darwin_ios.go:182 +0x184
github.com/fyne-io/mobile/app._Cfunc_runApp()
	_cgo_gotypes.go:201 +0x38
github.com/fyne-io/mobile/app.main(0x130114760)
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/app/darwin_ios.go:75 +0x58
github.com/fyne-io/mobile/app.Main(...)
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/app/app.go:21
fyne.io/fyne/v2/internal/driver/gomobile.(*mobileDriver).Run(0x13011b450)
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/driver.go:138 +0x64
fyne.io/fyne/v2/internal/driver/gomobile.(*window).ShowAndRun(0x104329ae0)
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/window.go:187 +0x3c
main.main()
	/Users/changkun/dev/changkun.de/fyne/iosrend/main.go:46 +0x2a0
```

It looks like sendTouch may happen concurrently. Adding an RWMutex would be a quick fix.

### To Reproduce:

1. run the reproducer in #2406 
2. keep clicking the button
3. if lucky, the problem occurs

### Device (please complete the following information):
 - **OS:** iOS 15
 - **Version:** beta 6
 - **Go version:** gotip based on CL 344969
 - **Fyne version:**  develop 83ca35d98be7cf401579c2f78b53dabd7aea250a

### PR DESCRIPTION
**Pull request by changkun**
### Description:

The pointer addresses of UITouch* are used as touchIDs, but they are only unique during a round of touch begin and touch end events. Only clear one touchID when touch.TypeEnd arrives can cause out of touchID panic. So, clear the entire touchIDs at every touch ends.

Fixes #2407 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/driver/mobile/app/darwin_ios.go [hunk 1]
```diff
@@ -195,9 +185,14 @@ func sendTouch(cTouch, cTouchType uintptr, x, y float32) {
 
 	t := touch.Type(cTouchType)
 	if t == touch.TypeEnd {
-		touchIDs[id] = 0
+		// Clear all touchIDs when touch ends. The UITouch pointers are unique
+		// at every multi-touch event. See:
+		// https://github.com/fyne-io/fyne/issues/2407
+		// https://developer.apple.com/documentation/uikit/touches_presses_and_gestures?language=objc
+		for idx := range touchIDs {
```
Comment (andydotxyz) [inline internal/driver/mobile/app/darwin_ios.go:192]: Wouldn't it be quicker to just set `touchIDs` to `nil`?

**Review by andydotxyz — COMMENTED** [review]
I wonder if you're certain it is safe to remove the mutex? It seems from an observer that these could still be called concurrently?

File: internal/driver/mobile/app/darwin_ios.go (hunk 1 above)
Comment (changkun) [reply internal/driver/mobile/app/darwin_ios.go:192]: - This involves compiler optimization (see https://github.com/golang/go/issues/5373).
- Set it to nil will cause memory allocation.

**Comment by changkun** [comment]
Yes, it is

> I wonder if you're certain it is safe to remove the mutex?

Yes, it is certain. the sendTouch is called from the OS's main thread, which does not occur concurrently.

> It seems from an observer that these could still be called concurrently?

The previous observer was wrong, as it did not fix the issue. The current fix suggests the correct fix to the cause of the panic.

**Comment by andydotxyz** [comment]
> Yes, it is certain. the sendTouch is called from the OS's main thread, which does not occur concurrently.

Ok, thanks. In future PR can you separate removal of unneeded code and the bug fix itself in different commits?

**Review by andydotxyz — APPROVED** [review]
Great thanks

**Comment by changkun** [comment]
>  In future PR can you separate removal of unneeded code and the bug fix itself in different commits?

No problem 👍
