### PR TITLE
systray: ensure title is not empty

### LINKED ISSUE #3678: tray can not be show on ubuntu 22.04
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Tray can not be show on ubuntu 22.04 and work well on windows 10.

### How to reproduce

1.go build
2.run it on the terminal `./exe`

### Screenshots

_No response_

### Example code

```go
aboutMenuItem := fyne.NewMenuItem("about", func() {
	aboutWindow := a.NewWindow("about")
	aboutWindow.SetContent(aboutContent)
	aboutWindow.Show()
})
menu = fyne.NewMenu("aaa", aboutMenuItem)
trayResouce, err := fyne.LoadResourceFromPath("icon.png")
if err != nil {
	log.Println(err)
	desk.SetSystemTrayIcon(defaultResouce)
} else {
	desk.SetSystemTrayIcon(trayResouce)
}
desk.SetSystemTrayMenu(menu)
```

### Fyne version

2.2.3

### Go compiler version

1.19.1

### Operating system and version

ubuntu 22.04

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lucor**
### Description:

Some desktop environments like the one provided by Ubuntu 22.04 requires the systray title to be not empty to be displayed. 
This commit ensure the title is always set trying to use the app name from metadata. If the app name is not set will fallback to the app ID

Fixes #3678

 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/driver/glfw/driver_desktop.go [hunk 1]
```diff
@@ -46,6 +46,12 @@ func (d *gLDriver) SetSystemTrayMenu(m *fyne.Menu) {
 				d.SetSystemTrayIcon(theme.BrokenImageIcon())
 			}
 
+			title := fyne.CurrentApp().Metadata().Name
+			if title == "" {
+				title = fyne.CurrentApp().UniqueID()
```
Comment (Jacalz) [inline internal/driver/glfw/driver_desktop.go:51]: The app lookup uses atomics to get the variable. Might be better to avoid doing so twice. 
```suggestion
			app := fyne.CurrentApp()
			title := app.Metadata().Name
			if title == "" {
				title = app.UniqueID()
```

Comment (lucor) [reply internal/driver/glfw/driver_desktop.go]: Good catch, thanks!
