### PR TITLE
Fixes #3507 window is max size at all times

### LINKED ISSUE #3507: regression since v2.2.3 - window is max size at all times
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Before (937991b51f4d951474b346075aae110d61ffc016)
image

After (2a54f832544fbfc8c4333023c69247b3871c83d3)
image

### How to reproduce

1. Install fyne, any version >= `fyne.io/fyne/v2 v2.2.2-rc3.0.20220706192957-2a54f832544f`, e.g. `v2.2.3`
2. Use code from example
3. Observe wonky height.
4. Height only can be corrected by switchig to richt-text tab and back to other tabs.
  - at this point resizing starts to work again

### Screenshots

_No response_

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {

	a := app.New()

	w := a.NewWindow("Issue")
	w.Resize(fyne.NewSize(740, 430))

	mainContainer :=
		container.NewAppTabs(
			container.NewTabItem("Something", widget.NewEntry()),
			container.NewTabItem("Attributions", newTabCredits()),
		)

	w.SetContent(mainContainer)
	w.CenterOnScreen()
	w.ShowAndRun()
}

func newTabCredits() fyne.CanvasObject {
	lbl := widget.NewRichTextFromMarkdown(`## cmd\gametts\Icon.png

Creative Commons License (2021)

"Text to speech" By Trevor Dsouza, IN

----
`)
	lbl.Wrapping = fyne.TextWrapWord
	return lbl
}
```

### Fyne version

2.2.3+

### Go compiler version

1.19.4

### Operating system

Windows

### Operating system version

Windows 11 22H2 Build 22621.963

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by alexballas**
### Description:
NewRichText seems to me missing some functionality. 
updateRowBounds needs to be followed by a Refresh.

Fixes #3507

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [ ] Tests all pass.

### CODE REVIEW

File: widget/richtext.go [hunk 1]
```diff
@@ -45,7 +45,10 @@ type RichText struct {
 func NewRichText(segments ...RichTextSegment) *RichText {
 	t := &RichText{Segments: segments}
 	t.Scroll = widget.ScrollNone
+	t.ExtendBaseWidget(t)
+	
 	t.updateRowBounds()
+	t.Refresh()
```
Comment (andydotxyz) [inline widget/richtext.go:51]: This is something to avoid as it will allocate a renderer immediately, it should not be needed for this fix.
Can this be resolved with a smaller scope change?

**Review by andydotxyz — CHANGES_REQUESTED** [review]

File: widget/richtext.go (hunk 1 above)
Comment (alexballas) [reply widget/richtext.go]: OK, I reverted those changes and proposed a small change inside lineBounds

**Comment by andydotxyz** [comment]
Thanks. I think the ExtendBaseWidget change was good though. Now there is a weird white space addition instead?

You'll need to figure what to do with the test failure too sorry.

**Comment by alexballas** [comment]
yes, I fixed the white space thing. Tests pass now

**Review by andydotxyz — APPROVED** [review]
Great thanks!
