### PR TITLE
Avoid multiple compilations for mobile mode

### LINKED ISSUE #4072: Android app crashing when opening second window
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Create an app with two windows, open the second one on an android device and the app will crash.

### How to reproduce

run code below, tap "Button" observe crash:

```
03-02 01:57:14.001 28015     0 E Go      : panic: failed to link OpenGL program; error code: 501
03-02 01:57:14.001 28015     0 E Go      : 
03-02 01:57:14.001 28015     0 E Go      : goroutine 14 [running]:
03-02 01:57:14.001 28015     0 E Go      : fyne.io/fyne/v2/internal/painter/gl.(*painter).createProgram(0x4000184ea0, {0x7c07756b7d?, 0x0?})
03-02 01:57:14.001 28015     0 E Go      :      /Users/andy/Code/Fyne/fyne/internal/painter/gl/painter.go:179 +0x594
03-02 01:57:14.001 28015     0 E Go      : fyne.io/fyne/v2/internal/painter/gl.(*painter).Init(0x4000184ea0)
03-02 01:57:14.001 28015     0 E Go      :      /Users/andy/Code/Fyne/fyne/internal/painter/gl/gl_gomobile.go:71 +0x144
03-02 01:57:14.001 28015     0 E Go      : fyne.io/fyne/v2/internal/driver/mobile.(*mobileDriver).handlePaint(0x4000400000, {0x80?}, {0x7c07d9eaf8, 0x4000326af0})
03-02 01:57:14.001 28015     0 E Go      :      /Users/andy/Code/Fyne/fyne/internal/driver/mobile/driver.go:250 +0x8c
03-02 01:57:14.001 28015     0 E Go      : fyne.io/fyne/v2/internal/driver/mobile.(*mobileDriver).Run.func1({0x7c07d9beb8?, 0x7c0873c560})
03-02 01:57:14.001 28015     0 E Go      :      /Users/andy/Code/Fyne/fyne/internal/driver/mobile/driver.go:188 +0x394
03-02 01:57:14.001 28015     0 E Go      : fyne.io/fyne/v2/internal/driver/mobile/app.mainUI.func1()
03-02 01:57:14.001 28015     0 E Go      :      /Users/andy/Code/Fyne/fyne/internal/driver/mobile/app/android.go:429 +0x48
03-02 01:57:14.001 28015     0 E Go      : created by fyne.io/fyne/v2/internal/driver/mobile/app.mainUI
03-02 01:57:14.001 28015     0 E Go      :      /Users/andy/Code/Fyne/fyne/internal/driver/mobile/app/android.go:428 +0x98
```

### Screenshots

_No response_

### Example code

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	application := app.NewWithID("testui")
	window1 := application.NewWindow("Window One")

	window1.SetContent(widget.NewButton("Button", func() {
		window2 := application.NewWindow("Window Two")
		window2.SetContent(widget.NewLabel("test"))
		window2.Show()
	}))
	window1.Show()
	application.Run()
}
```

### Fyne version

2.3.x, 2.2.x, develop

### Go compiler version

1.20.4

### Operating system and version

macOS M2

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #4072

FYI: I have not yet managed to confirm this is great on iPhone, only Android and the mobile simulator mode (am travelling with limited access to Apple's security tools).

### Checklist:

- [ ] Tests included. <- requires Android runtime
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/painter/gl/gl_gomobile.go [hunk 1]
```diff
@@ -68,10 +69,19 @@ func (p *painter) Init() {
...
+		programs[1] = p.createProgram("line_es")
+		programs[2] = p.createProgram("rectangle_es")
+		programs[3] = p.createProgram("round_rectangle_es")
+
+		compiled = programs
+	}
+	p.program = compiled[0]
+	p.lineProgram = compiled[0]
+	p.rectangleProgram = compiled[0]
+	p.roundRectangleProgram = compiled[0]
```
Comment (Jacalz) [inline internal/painter/gl/gl_gomobile.go:84]: We can create the slice in one go and use len() instead of checking for nil. It also seems like the code was wrong with how it used the slice indexes.
```suggestion
	if len(compiled) == 0 {
		compiled = []Program{
			p.createProgram("simple_es"),
			p.createProgram("line_es"),
			p.createProgram("rectangle_es"),
			p.createProgram("round_rectangle_es"),
		}
	}
	p.program = compiled[0]
	p.lineProgram = compiled[1]
	p.rectangleProgram = compiled[2]
	p.roundRectangleProgram = compiled[3]
```

**Review by Jacalz — CHANGES_REQUESTED** [review]
This compiles but causes a crash at runtime when using the mobile simulator (likely on actual hardware as well). I added a suggestion inline that makes it run correctly here but I can't say if it fixes the issue or not.

File: internal/painter/gl/gl_gomobile.go (hunk 1 above)
Comment (andydotxyz) [reply internal/painter/gl/gl_gomobile.go]: Goodness I have no idea how that happened - the tests all passed for me, I must have refactored before committing sorry.
I have pushed an update and see no crashes on mobile simulator or Android - does it now work for you as well?

Comment (Jacalz) [reply internal/painter/gl/gl_gomobile.go]: Yeah, it works now. Have you consider using the simplification that I suggested above?
```go
compiled = []Program{
			p.createProgram("simple_es"),
			p.createProgram("line_es"),
			p.createProgram("rectangle_es"),
			p.createProgram("round_rectangle_es"),
		}
```

Comment (andydotxyz) [reply internal/painter/gl/gl_gomobile.go]: Sorry I missed that somehow

**Review by Jacalz — COMMENTED** [review]
Thanks

**Review by Jacalz — APPROVED** [review]
Woops. Let's approve as well ;)

**Comment by andydotxyz** [comment]
Confirming iOS is working, so merging now :)
