### PR TITLE
Just resize/move, not refresh content, for Split.SetOffset

### LINKED ISSUE #5488: Split container refreshes full content when dragging to resize the split
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Split.SetOffset refreshes everything, when it should just move/resize things. This causes lagginess with fyne_demo and the efficient run loop PR (where input events are currently processed as fast as they arrive).

Related: #5456 

### How to reproduce

run fyne_demo on the efficient runloop branch, resize a split container

### Screenshots

_No response_

### Example code

n/a

### Fyne version

develop

### Go compiler version

n/a

### Operating system and version

all

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dweymouth**
### Description:

Split.SetOffset, which is also called by the divider when dragged, no longer refreshes content but just resizes/moves.

Fixes #5488 

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: container/split.go [hunk 1]
```diff
@@ -20,6 +20,11 @@ type Split struct {
 	Horizontal bool
 	Leading    fyne.CanvasObject
 	Trailing   fyne.CanvasObject
+
+	// to communicate to the renderer that the next refresh
+	// is just an offset update (ie a resize and move only)
+	// cleared by renderer in Refresh()
+	nextRefreshIsOffsetUpdate bool
```
Comment (Jacalz) [inline container/split.go:27]: This is a bit verbose. Wouldn’t something like `offsetUpdated` suffice?

Comment (dweymouth) [reply container/split.go]: Sounds fine. Updated :)

**Review by andydotxyz — APPROVED** [review]
Nice thanks!
