### PR TITLE
Markdown: Support links in headings

### LINKED ISSUE #5576: Markdown formatting removes links
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Formatting seems to break links inside of markdown, they also appear to have an extra space in front

### How to reproduce

Run the attached example code and notice the formatted code does not contain working links

### Screenshots

Image

### Example code

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("demo")

	md := `
# Header

## Sub header with a [link](https://fyne.io)

Regular text with a [link](https://fyne.io) works

**Bold doesn't work with a [link](https://fyne.io)**

*Italic doesn't work with a [link](https://fyne.io)*
`

	w.SetContent(widget.NewRichTextFromMarkdown(md))

	w.ShowAndRun()
}

```

### Fyne version

2.5.4

### Go compiler version

go1.23.6 linux/amd64

### Operating system and version

Arch Linux

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by MaxGyver83**
### Description:

image

#### Changes in this PR:

- `*ast.Heading` must be checked for `*ast.Text` and `*ast.Link` child nodes.
- Adjacent `*ast.Text` nodes need to be merged.
- `textRenderer.layoutRow`: `textSize` must be checked for every `Hyperlink`.
- HyperlinkSegments become inline and consist of at least two elements: header text + newline/paragraph.

Fixes #5576 (together with #6127, already merged)

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass (except data/binding for `-tags mobile`).

#### Where applicable:

- [x] Public APIs match existing style and have Since: line.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Looks good thanks - could you put a unit test in to demonstrate some of what the screenshot shows (prevents regression)

File: widget/richtext_objects.go [hunk 1]
```diff
@@ -117,6 +117,7 @@ type HyperlinkSegment struct {
 	OnTapped func() `json:"-"`
 
 	// Since 2.8
+	SizeName  fyne.ThemeSizeName // The theme name of the text size to use, if blank will be the standard text size
```
Comment (andydotxyz) [inline widget/richtext_objects.go]: This removes the Since from the previous TextStyle

Comment (MaxGyver83) [reply widget/richtext_objects.go]: OK, I thought this Since comment was valid for everything after it. Then, I need two Since comments!?

**Review by andydotxyz — COMMENTED** [review]
This is good thanks. Sorry I forgot one thing 1 - the new item should be added at the end in case someone had used the `&Hyperlink{fyne.TextAlignLeading, "Some text"...}` style construction - it goes against style but it can be done and would represent a break.

**Comment by MaxGyver83** [comment]
> This is good thanks. Sorry I forgot one thing 1 - the new item should be added at the end in case someone had used the `&Hyperlink{fyne.TextAlignLeading, "Some text"...}` style construction - it goes against style but it can be done and would represent a break.

I see. I moved `SizeName` to the end in commit 18db0ee.

**Review by andydotxyz — APPROVED** [review]
Great thanks!
