### PR TITLE
Adjust backspace handling so we ignore hardware key events during soft keyboard editing

### LINKED ISSUE #2774: Text entry widget backspace deletes two characters on Android
Possibly related issues: #1941, #165

### Describe the bug:

On Android, pressing backspace in an editable text entry widget deletes two characters.

### To Reproduce:

1. Clone [this github repository](https://github.com/xxxserxxx/fyneissue2)
2. Package for Android (`fyne package -os android`)
3. Push to an android device, install, and run
4. Select the text entry widget at the top of the screen
5. Enter some text (e.g., "abcdefg")
6. Press the keyboard's backspace (⌫) key

Two characters will be deleted. This happens from wherever in the string the cursor is, e.g. the end or the middle.

### Example code:

Sample code is in a [github repository](https://github.com/xxxserxxx/fyneissue). It is, essentially, a text entry widget with a list widget below. The text entry widget has an `OnSubmitted` lambda that prepends the text to the list.  The behavior happens without the `OnSubmitted` closure as well.

### Device (please complete the following information):

 - **OS:** Android
 - **Version:** Samsung One UI; Android 12. Built-in Samsung soft keyboard.
 - **Go version:** 1.17.7
 - **Fyne version:** v2.1.2

### PR DESCRIPTION
**Pull request by andydotxyz**
(More of a mystery is why those duplicate keys happen backwards!?)

Fixes #2774

### Checklist:

- [ ] Tests included. <- I cannot replicate on emulator or code
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/driver/mobile/device.go [hunk 1]
```diff
@@ -45,14 +47,14 @@ func (*device) HasKeyboard() bool {
 	return false
 }
 
-func (*device) ShowVirtualKeyboard() {
-	showVirtualKeyboard(mobile.DefaultKeyboard)
+func (dev *device) ShowVirtualKeyboard() {
```
Comment (Jacalz) [inline internal/driver/mobile/device.go:50]: Isn't single letter names for polymer receivers the standard/ideomatic way in Go?

**Review by Jacalz — COMMENTED** [review]
Looking good. Just a quick question inline.

File: internal/driver/mobile/device.go (hunk 1 above)
Comment (andydotxyz) [reply internal/driver/mobile/device.go:50]: I was just matching what was there. I can tidy that up on another PR - there is a conflict internally to do that refactor which I will get to the bottom of.
