### PR TITLE
Fix memory leak in RichText when replacing segments

### LINKED ISSUE #4723: RichText leaks memory when replacing segments
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Changing `RichText` content by invoking `RichText.ParseMarkdown` leads to linear growth of memory consumption. In the practical case I faced it took gigabytes of RAM in a couple of hours.

### How to reproduce

To reproduce — call `RichText.ParseMarkdown` many times with different content. Or just use the snippet I attached below.

### Screenshots

Memory growth (one line per second):
image

### Example code

```go
package main

import (
	"fmt"
	"runtime"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
	"github.com/google/uuid"
)

func main() {
	a := app.New()
	w := a.NewWindow("Fyne's RichText Memory Leak")
	w.Resize(fyne.NewSize(128, 128/1.618))
	rt := widget.NewRichText()
	go func() {
		var m runtime.MemStats
		for {
			time.Sleep(time.Second)
			// Force GC just to make measurements a bit more precise.
			runtime.GC()
			// Report memory consumption.
			runtime.ReadMemStats(&m)
			fmt.Printf(
				"Sys: %v MiB\tHeapAlloc: %v MiB\tTotalAlloc: %v MiB\tNumGC: %v\n",
				m.Sys/1024/1024, m.HeapAlloc/1024/1024, m.TotalAlloc/1024/1024, m.NumGC,
			)
		}
	}()
	go func() {
		for {
			rt.ParseMarkdown(uuid.NewString())
		}
	}()
	w.SetContent(rt)
	w.ShowAndRun()
}
```

### Fyne version

2.4.4

### Go compiler version

1.22.1

### Operating system and version

macOS Sonoma 14.4

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dweymouth**
### Description:
Clean out visualCache entries that are not currently needed on Refresh

Fixes #4723 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: widget/richtext.go [hunk 1]
```diff
@@ -225,6 +225,26 @@ func (t *RichText) cachedSegmentVisual(seg RichTextSegment, offset int) fyne.Can
...
+		found := false
+		for _, seg2 := range t.Segments {
+			if seg1 == seg2 {
+				found = true
+				break
+			}
+		}
+		if !found {
+			// cached segment is not currently in t.Segments, clear it
+			deletingSegs = append(deletingSegs, seg1)
```
Comment (Jacalz) [inline widget/richtext.go:240]: Does the map change order when we delete from ut? I wonder if we can just delete it directly instead of heap-allocating a slice on each refresh?

Comment (dweymouth) [reply widget/richtext.go:240]: It does look like it's *probably safe* but the actual spec isn't super explicit about it: https://stackoverflow.com/questions/56048259/is-it-safe-to-remove-dictionary-keys-while-iterating-over-it

Comment (dweymouth) [reply widget/richtext.go:243]: I added an early return condition so we will skip the allocation and iteration if we don't need to clean anything

File: widget/richtext.go [hunk 2]
```diff
@@ -225,6 +225,29 @@ func (t *RichText) cachedSegmentVisual(seg RichTextSegment, offset int) fyne.Can
 	return vis
 }
 
+func (t *RichText) cleanVisualCache() {
+	if len(t.visualCache) <= len(t.Segments) {
```
Comment (andydotxyz) [inline widget/richtext.go:229]: With this things may still leak once... is that OK?
(i.e. if you replace 1 or 2 or more with exactly the same number then it will expand to fit the new items, which will get removed later.
Probably a fair trade-off, just wanted to check

Comment (dweymouth) [reply widget/richtext.go:229]: I think so, what's important is that it is cleared eventually and there's an upper bound on the cache size

**Review by andydotxyz — APPROVED** [review]
Thanks. I think the clarification on the early escape marks this good.
