### PR TITLE
Make sure we scroll the correct offset when item heights are set

### LINKED ISSUE #3477: List with different item heights selection bug (blocker?)
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Selecting an item in a list with many (scroll active) items with differents heights makes the list scroll out of selected item view.

Must have something to do with item offset calculation (bet that the calculation is always assuming equal heights items).

### How to reproduce

A list with many different heights items, scroll somewhere to the middle of the list and select some item.

### Screenshots

_No response_

### Example code

```go
package main

import (
	"math/rand"
	"strings"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test")

	var data []string

	var lst *widget.List
	lst = widget.NewList(
		func() int {
			return len(data)
		},
		func() fyne.CanvasObject {
			return widget.NewLabel("")
		},
		func(id widget.ListItemID, co fyne.CanvasObject) {
			co.(*widget.Label).SetText(data[id])
		},
	)

	str := "a ligne of data\n"
	lbl := widget.NewLabel("")
	for i := 1; i <= 1000; i++ {
		data = append(data, strings.TrimSpace(strings.Repeat(str, rand.Intn(7)+1)))
		lbl.SetText(data[i-1])
		//lst.SetItemHeight(i-1, lbl.MinSize().Height)
	}

	w.SetContent(container.NewBorder(widget.NewLabel("Test"), nil, nil, nil, lst))
	w.Resize(fyne.NewSize(600, 400))
	w.CenterOnScreen()
	w.ShowAndRun()
}
```

### Fyne version

2.3.0-rc1

### Go compiler version

1.19.1

### Operating system

Windows

### Operating system version

10

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #3477

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: widget/list.go [hunk 1]
```diff
@@ -109,10 +109,21 @@ func (l *List) SetItemHeight(id ListItemID, height float32) {
...
 func (l *List) scrollTo(id ListItemID) {
-	if l.scroller == nil {
+	if l.scroller == nil{
 		return
 	}
-	y := (float32(id) * l.itemMin.Height) + (float32(id) * theme.Padding())
+
+	separatorThickness := theme.Padding()
+	y := float32(0)
+	for i := 0; i < id; i++ {
```
Comment (Bluebugs) [inline widget/list.go:118]: This will certainly impact the speed of scrollTo on large list as it as discussed in other case. Can you put the bypass logic in place here too for now?

**Review by Bluebugs — APPROVED** [review]
