### PR TITLE
Working around missing screen dimensions for Steam Deck

### LINKED ISSUE #4896: Incorrect scaling on Steam Deck screen
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Copying over from https://github.com/Jacalz/rymdport/issues/159, Fyne applications are entirely unusable on Steam Deck (maybe even other small screens?). This is really problematic because anyone using a Steam Deck and then installing something like Rymdport or Supersonic on Flathub will be very annoyed because the apps have stopped working.

### How to reproduce

1. Start any Fyne application on Steam Deck.
2. Notice that scaling makes it impossible to use the app.

### Screenshots

image
image

### Example code

Use Fyne demo or install Rymdport or Supersonic from Flathub.

### Fyne version

v2.4.5

### Go compiler version

1.22.3

### Operating system and version

SteamOS

### Additional Information

See https://github.com/Jacalz/rymdport/issues/159 for more information.

### PR DESCRIPTION
**Pull request by andydotxyz**
And maybe more?

Fixes #4896

Results in this (not the right DPI, but not unexpected given how other software looks)

Screenshot_20240709_095130

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/driver/glfw/window_desktop.go [hunk 1]
```diff
@@ -314,7 +314,10 @@ func (w *window) detectScale() float32 {
 		return 1.0
 	}
 
-	widthMm, _ := monitor.GetPhysicalSize()
+	widthMm, heightMm := monitor.GetPhysicalSize()
+	if widthMm == 60 && heightMm == 60 { // some sort of failure - mostly on Steam Deck
+		return 1
```
Comment (toaster) [inline internal/driver/glfw/window_desktop.go:319]: Nit: I think the `return 1` statements should look all the same. Either with or without `.0`. Personally, I would leave it out.

File: internal/driver/glfw/window_desktop.go [hunk 2]
```diff
@@ -314,7 +314,10 @@ func (w *window) detectScale() float32 {
 		return 1.0
 	}
 
-	widthMm, _ := monitor.GetPhysicalSize()
+	widthMm, heightMm := monitor.GetPhysicalSize()
+	if widthMm == 60 && heightMm == 60 { // some sort of failure - mostly on Steam Deck
```
Comment (toaster) [inline internal/driver/glfw/window_desktop.go:318]: Where does these `60` come from? AFAIU the GLFW source, it would return `0` if the monitor did not provide a number.
If these values are based on experience, the comment should explain this.

Comment (toaster) [reply internal/driver/glfw/window_desktop.go:318]: Also, this might result in a wrong scale for real-life 60mmx60mm displays with a huge DPI 😁.

**Review by toaster — CHANGES_REQUESTED** [review]
Just some small things:
- [ ] consolidate scale fallback values
- [ ] explain “failure screen dimensions”

File: internal/driver/glfw/window_desktop.go (hunk 2 above)
Comment (Jacalz) [inline internal/driver/glfw/window_desktop.go:318]: Should this be not be protected by a `runtime.GOOS == "linux"` check? Maybe even `!build.IsWayland` from what I understand of the issue?

Comment (andydotxyz) [reply internal/driver/glfw/window_desktop.go:318]: The Wayland check is above and it will exit early.
Linux specific... I guess so, updated

Comment (andydotxyz) [reply internal/driver/glfw/window_desktop.go]: That is true. If there was ever a 6cm square screen that we had to support. If that ever happens I will update this for sure!

**Review by toaster — APPROVED** [review]

File: internal/driver/glfw/window_desktop.go (hunk 2 above)
Comment (Jacalz) [reply internal/driver/glfw/window_desktop.go]: Good point :)
