### PR TITLE
Hide image in dialog background when not needed, saved CPU

### LINKED ISSUE #4574: High CPU use when showing CustomDialogs
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Showing a custom confirm dialog using `dialog.ShowCustomConfirm` uses high CPU while the dialog is displayed. After dismissing the dialog the CPU settles back down to normal.

### How to reproduce

Run the example code, with an Activity Monitor/Task Manager/etc window open, and click the button to show the custom confirm dialog

### Screenshots

_No response_

### Example code

```go
package main

import (
	"log"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Custom Confirm CPU bug")

	button := widget.NewButton("Show dialog", func() {
		dialog.ShowCustomConfirm("Custom confirm", "Confirm text", "Dismiss text",
			widget.NewLabel("Content"), func(b bool) {
				log.Printf("Confirm dismissed with value %v\n", b)
			}, myWindow)
	})
	myWindow.SetContent(container.NewCenter(button))
	myWindow.Resize(fyne.NewSize(400, 300))
	myWindow.ShowAndRun()
}
```

### Fyne version

2.4.3

### Go compiler version

go1.21.1

### Operating system and version

macOS Ventura M2

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #4574

### Checklist:

- [x] Tests included. <- existing graphical tests verify the look is unchanged
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: dialog/base.go [hunk 1]
```diff
@@ -108,8 +108,13 @@ func (d *dialog) hideWithResponse(resp bool) {
 func (d *dialog) create(buttons fyne.CanvasObject) {
 	label := widget.NewLabelWithStyle(d.title, fyne.TextAlignLeading, fyne.TextStyle{Bold: true})
 
+	image := &canvas.Image{Resource: d.icon}
```
Comment (dweymouth) [inline dialog/base.go:111]: If the dialog is immutable once created (ie if it doesn't have an image it will never have one), why not avoid adding the image entirely, or if it's easier code-wise, place a `layout.NewSpacer()` in place of the image in the container, as it's a less expensive object. That's what I often use as an "empty" canvas object.

Comment (andydotxyz) [reply dialog/base.go:111]: You're right it was a code complexity issue that led me to leave it there.
My concern is that by placing a spacer we have possibly different objects in that index - is a spacer much less expensive than a hidden image with nil content?

Comment (dweymouth) [reply dialog/base.go:111]: I checked `canvas.Image` implementation and the only reason I even bothered with the suggestion is that Resize on an image results in a Refresh: https://github.com/fyne-io/fyne/blob/master/canvas/image.go#L174

Comment (dweymouth) [reply dialog/base.go:111]: I am fine with merging this as-is though (but I didn't actually test it myself) and we could file an optimization ticket to the backlog if we want.

**Review by dweymouth — APPROVED** [review]

File: dialog/base.go (hunk 1 above)
Comment (andydotxyz) [reply dialog/base.go]: > I checked `canvas.Image` implementation and the only reason I even bothered with the suggestion is that Resize on an image results in a Refresh

You talked me into it thank :) spacer is actually OK - all tests and usages passing

**Review by dweymouth — APPROVED** [review]
nice one

**Comment by Jacalz** [comment]
Should we not make sure that the renderer doesn't render nil resources and get stuck in a rendering loop?
I agree that this is a good change but is it also not leaving the underlying issue unfixed?

**Comment by dweymouth** [comment]
> Should we not make sure that the renderer doesn't render nil resources and get stuck in a rendering loop? I agree that this is a good change but is it also not leaving the underlying issue unfixed?

There's a separate ticket tracking the underlying issue (which may be a harder fix), but I think this PR is still desirable even if the underlying issue were to be fixed, and this also allows us to fix it fast, which is a high-impact issue, whereas the underlying issue only impacts user code that shows an empty image.

**Comment by andydotxyz** [comment]
Yeah the change I proposed on the linked issue didn't really solve the underlying issue it just reduced it - as the not-drawing-nil-image didn't remove the loop completely. Something about image handling needs more time spent on it in the nil case as it didn't seem to "stick" that rendering an empty image was done when nothing was drawn.
