### PR TITLE
Fix crash in label with binding

### LINKED ISSUE #2125: Data binding with widget.List sometimes crash while scrolling
### Describe the bug:

Using data binding for a `widget.List` sometimes crash while scrolling. It seems to be a race condition. The error is:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x427a206]

goroutine 8 [running]:
fyne.io/fyne/v2/data/binding.(*stringFromFloat).Get(0x0, 0xc0002be508, 0xc000380290, 0xc0002be5b8, 0xc00033c800)
        .../fyne/data/binding/convert.go:109 +0x26
fyne.io/fyne/v2/widget.(*Label).Bind.func1()
        .../fyne/widget/label.go:59 +0x3c
fyne.io/fyne/v2/data/binding.(*listener).DataChanged(0xc001616728)
        .../fyne/data/binding/binding.go:55 +0x28
fyne.io/fyne/v2/data/binding.processItems()
        .../fyne/data/binding/queue.go:56 +0x94
created by fyne.io/fyne/v2/data/binding.init.0
        .../fyne/data/binding/queue.go:15 +0x35
exit status 2
```
### To Reproduce:
Steps to reproduce the behaviour:
1. Run fyne_demo
2. Click on the binding tutorial.
3. Try appending items and scrolling (sometimes it crashes)

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** 10.15.7 Catalina
 - **Go version:** 1.16.2
 - **Fyne version:** develop @ 23e0ed1

### PR DESCRIPTION
**Pull request by andydotxyz**
Moved to a different setup model where we don't recreate listeners all the time.
Fixes #2125

If this is a desirable change we could move other Bind/Unbind widget to match.

### Checklist:

- [ ] Tests included. <- race
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by fpabl0 — APPROVED** [review]
LGTM. I will try to explore the connected flag in other PR to see if it is viable :)

**Comment by fpabl0** [comment]
It seems that there is something more we have to do here, sometimes I got an error inside convert.go:

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x42541c6]

goroutine 8 [running]:
fyne.io/fyne/v2/data/binding.(*stringFromFloat).Get(0x0, 0xc000048f78, 0x42545fa, 0xc0003bcdd8, 0x40638e0)
        .../fyne/data/binding/convert.go:109 +0x26
fyne.io/fyne/v2/widget.(*Label).createListener.func1()
        .../fyne/widget/label.go:71 +0x45
fyne.io/fyne/v2/data/binding.(*listener).DataChanged(0xc00018e9c0)
        .../fyne/data/binding/binding.go:63 +0x2e
fyne.io/fyne/v2/data/binding.processItems()
        .../fyne/data/binding/queue.go:56 +0x94
created by fyne.io/fyne/v2/data/binding.init.0
        .../fyne/data/binding/queue.go:15 +0x35
exit status 2
```

**Comment by andydotxyz** [comment]
> It seems that there is something more we have to do here, sometimes I got an error inside convert.go:

Those line numbers don't mat this PR... do you have local changes?

**Comment by fpabl0** [comment]
Yes, but they are commented. I copied your changes and paste in a local branch. I will try to reproduce it, by cloning directly your branch, although I think it would be the same 🤔. I will investigate. However it seems that this PR is ok and this can be solved in a different one?

**Comment by fpabl0** [comment]
Ok, I have tested your branch without any change, this is the error trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x4254c46]

goroutine 8 [running]:
fyne.io/fyne/v2/data/binding.(*stringFromFloat).Get(0x0, 0xc0002b0508, 0xc00009a470, 0xc0002b05b8, 0x40643a0)
        /Users/pablofuentes/Desktop/fyne/data/binding/convert.go:109 +0x26
fyne.io/fyne/v2/widget.(*Label).createListener.func1()
        /Users/pablofuentes/Desktop/fyne/widget/label.go:118 +0x45
fyne.io/fyne/v2/data/binding.(*listener).DataChanged(0xc000338008)
        /Users/pablofuentes/Desktop/fyne/data/binding/binding.go:55 +0x28
fyne.io/fyne/v2/data/binding.processItems()
        /Users/pablofuentes/Desktop/fyne/data/binding/queue.go:56 +0x94
created by fyne.io/fyne/v2/data/binding.init.0
        /Users/pablofuentes/Desktop/fyne/data/binding/queue.go:15 +0x35
```

**Comment by fpabl0** [comment]
This is really weird, it seems that there is a chance that `s` could be nil here:
```go
func (s *stringFromFloat) Get() (string, error) {
	val, err := s.from.Get()
	if err != nil {
		return "", err
	}

	return fmt.Sprintf(s.format, val), nil
}
```

File: widget/label.go [hunk 1]
```diff
@@ -114,10 +103,31 @@ func (l *Label) Unbind() {
...
 	l.textSource = nil
 }
 
+func (l *Label) createListener() {
+	if l.textListener != nil {
+		return
+	}
+
+	l.textListener = binding.NewDataListener(func() {
+		if l.textSource == nil {
```
Comment (fpabl0) [inline widget/label.go:115]: It seems that this part should be written as:
```go
src := l.textSource
if src == nil {
    return
}
val, err := src.Get()
```
To nullify any chance to have a nil textSource when we actually call `Get()`.
This is because it seems that there is a little probability that textSource is nil when Go (internally) is converting the interface to its actual type? (I am supposing this, as that could be the only reason to explain this). Take a look this code:
https://play.golang.org/p/bqEsHGUYdfw

**Review by fpabl0 — CHANGES_REQUESTED** [review]
I have found something interesting that I didn't know before (probably it was logical but I hadn't realized it). Nil objects can call its methods without actually crashing the whole program:
https://play.golang.org/p/tOzpRaZTt3m

File: widget/label.go [hunk 2]
```diff
@@ -114,10 +103,31 @@ func (l *Label) Unbind() {
 	}
```
Comment (fpabl0) [inline widget/label.go:103]: `Unbind` method should be re-written to:
```go
	src := l.textSource
	listen := l.textListener
	if src == nil || listen == nil {
		return
	}

	src.RemoveListener(listen)
	l.textSource = nil
```

**Review by fpabl0 — CHANGES_REQUESTED** [review]
Same change should be done on `Unbind` method.

**Review by fpabl0 — APPROVED** [review]
