### PR TITLE
Make animation runner and Start zero-alloc

### LINKED ISSUE #4445: Animation runner allocates new slices every frame
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When animations are running, the animation runner allocates a new slice of active animations 60 times a second [here](https://github.com/fyne-io/fyne/blob/master/internal/animation/runner.go#L73). This leads to a lot of work for the garbage collector and possibly increased system memory use of Fyne apps.

### How to reproduce

Run any app that has animations. This is not really a bug though but a ticket to track implementing memory optimizations in the animation runner.

### Screenshots

_No response_

### Example code

n/a

### Fyne version

2.4.2

### Go compiler version

n/a

### Operating system and version

n/a

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dweymouth**
### Description:

Fixes #4445

This is like the third try of fixing this but this way is the smallest diff and most logically similar to the preexisting code. The main change is to keep a new slice reference that can re-use the memory allocated for the animations slice that was previously discarded for garbage collection each tick.

Stopping an animation early is still not zero-alloc but it happens rare enough (relative to start and tick) that it shouldn't be a big issue, at least for now.

### Allocs benchmark:

== old code ==
goos: darwin
goarch: arm64
pkg: fyne.io/fyne/v2/internal/animation
BenchmarkRunnerAllocs-8      1843419           650.5 ns/op        80 B/op          1 allocs/op

we allocate once per frame (at 60fps in real-world) (new []*anim slice)

== new code ==

goos: darwin
goarch: arm64
pkg: fyne.io/fyne/v2/internal/animation
BenchmarkRunnerAllocs-8   	 1871389	       635.2 ns/op	       0 B/op	       0 allocs/op

We do not allocate at all on an individual frame of animations. We are also a tiny bit faster per frame, which is fairly negligible in the benchmark (allocating a slice *is* fast after all), but in real-world should mean less garbage and less GC triggers when it runs longer

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/animation/runner.go [hunk 1]
```diff
@@ -23,9 +24,19 @@ func (r *Runner) Start(a *fyne.Animation) {
 
 	if !r.runnerStarted {
 		r.runnerStarted = true
+		if r.animations == nil {
```
Comment (andydotxyz) [inline internal/animation/runner.go:27]: I think it could avoid duplication if moved up 4 lines? (Before the outer if)

**Review by andydotxyz — COMMENTED** [review]
A clever approach thanks, just a comment on the duplication inline.

File: internal/animation/runner.go (hunk 1 above)
Comment (dweymouth) [reply internal/animation/runner.go:27]: One is for initializing `r.animations` and the other for `r.pendingAnimations` though. I could create a helper function if you think it's cleaner, invoked like `r.animations = initIfNil(r.animations)`?

Comment (ccoVeille) [reply internal/animation/runner.go:27]: I think both will be fine. So please choose the one you prefer.

I just raised a point it could have been moved out

Another solution is a function where you pass a 

```
func initL(l *[]anim) {
if l == nil {
l= make....
}
}
```

Then you call initL(r.animations) then same for r.pendingAnimations

But maybe I missed something

Comment (Jacalz) [reply internal/animation/runner.go:27]: I think it is fine as it is. It is not much in the way of duplication

**Comment by dweymouth** [comment]
Any further thoughs?

**Comment by Jacalz** [comment]
Sorry, I've been away over the weekend. I can have a look tomorrow

File: internal/animation/runner.go [hunk 2]
```diff
@@ -12,6 +12,7 @@ type Runner struct {
 	animationMutex    sync.RWMutex
 	animations        []*anim
 	pendingAnimations []*anim
+	nextAnimations    []*anim // used by runner goroutine only
```
Comment (Jacalz) [inline internal/animation/runner.go:15]: This seems a bit strange naming wise. Pending and next seem like two synonyms for the same thing?

**Review by Jacalz — CHANGES_REQUESTED** [review]
Thanks. I have a little problem with the clash between next and pending not really making sense and making the code harder to follow. Also, I think this really needs a benchmark to show that it makes a difference.

PS: This is not zero-alloc in a strict sense. I'd rather that it uses a buffer to hopefully avoid allocating as often; if possible.

File: internal/animation/runner.go (hunk 1 above)
Comment (andydotxyz) [reply internal/animation/runner.go:27]: Sorry I missed that it was not identical

File: internal/animation/runner.go (hunk 2 above)
Comment (dweymouth) [reply internal/animation/runner.go:15]: `pendingAnimations` is the animations that have been `Start`ed during a single tick and haven't been picked up by the runner goroutine yet.

`nextAnimations` is basically "the pre-allocated slice that will be used by the runner goroutine on the next tick to become the new `animations` slice. Yeah the naming is a bit awkward, if you have a better suggestions I'm open to any!

**Comment by dweymouth** [comment]
> Thanks. I have a little problem with the clash between next and pending not really making sense and making the code harder to follow. Also, I think this really needs a benchmark to show that it makes a difference.
> 
> PS: This is not zero-alloc in a strict sense. I'd rather that it uses a buffer to hopefully avoid allocating as often; if possible.

Added a benchmark to show that we are now allocating nothing per frame of animations. You are correct that it is not *technically* zero-alloc but it is amortized zero-alloc since we only need to allocate if we've accumulated more running animations than could fit in the existing allocated slice memory (and then we won't allocate anymore unless the number of concurrent animations exceeds *that* slice's capacity)

File: internal/animation/runner.go (hunk 2 above)
Comment (dweymouth) [reply internal/animation/runner.go:15]: It can also be thought of as "the slice for accumulating the animations that will run in the next frame"

Comment (Jacalz) [reply internal/animation/runner.go:15]: Hmm. Yeah, I don't quite know how to name it but I think we need something better than what is there currently. Anyone reading the code for the first time will likely be confused.

Comment (dweymouth) [reply internal/animation/runner.go:15]: How about a descriptive comment?

Comment (dweymouth) [reply internal/animation/runner.go]: @Jacalz I added descriptive comments to all the slice declarations - hopefully that should make it understandable :)

**Review by Jacalz — APPROVED** [review]
Thanks. The extra comments and minor naming change helped a lot :)
