### PR TITLE
Fix the theme override for padding (and other static values)

### LINKED ISSUE #5019: Theme Override container cannot be used to override layout paddings
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The standard layouts all use the deprecated `theme.Padding()` to look up the padding value which does not pick up the overrides if the layout is used in a container or internally within a widget in an override container.

### How to reproduce

create a theme override container with a theme that overrides padding, and put a container with a layout inside that theme override container

### Screenshots

_No response_

### Example code

it's trivial from a code audit of the layout package to see where the problem is

### Fyne version

2.5.0

### Go compiler version

n/a

### Operating system and version

all

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by andydotxyz**
In theory some areas of code could be simplified - but that relies on there being no miss-use of the thread/fyne.Do.
So I have left all the widget/theme handling as-is for now and we can simplify it down the road once multiple threads are completely not supported any more.

Fixes #5019

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/theme/render.go [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+// PushRenderingTheme is used by the ThemeOverride container to stack the current theme during rendering
+// and calculations.
+func PushRenderingTheme(th fyne.Theme) {
+	themeStack = append(themeStack, th)
+}
+
+// PopRenderingTheme is used by the ThemeOverride container to remove an overridden theme during rendering
+// and calculations.
+func PopRenderingTheme() {
+	themeStack = themeStack[:len(themeStack)-1]
```
Comment (dweymouth) [inline internal/theme/render.go:29]:
```suggestion
	themeStack[len(themeStack)-1] = nil
	themeStack = themeStack[:len(themeStack)-1]
```
