### PR TITLE
Only refresh scroll chrome when scroller is resized

### LINKED ISSUE #5456: Tree and Table widgets refresh full content on any scroll or resize
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The Tree and Table widgets currently refresh the entire contents whenever they are scrolled or resized, regardless of whether new elements appear in the viewport or not. This is inefficient, though with the 2.5.x driver implementation it was not severe enough to be a bottleneck at least on modern systems. But with #5422, where we are currently processing scroll / mouse drag events from the OS as fast as they arrive, it causes severe lagging when scrolling or resizing a Tree or Table (visible in fyne demo). This does not happen with List, which has been optimized to only refresh the necessary rows.

### How to reproduce

Run fyne_demo on the #5422 branch. Scroll the tree or table, on a Macbook with the trackpad (which seems to deliver scroll events much faster than 60 fps), or resize the split container containing the Tree, also with the Macbook trackpad.

### Screenshots

_No response_

### Example code

fyne_demo

### Fyne version

develop

### Go compiler version

n/a

### Operating system and version

MacOS

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by andydotxyz**
Progresses #5456

### Checklist:

- [ ] Tests included.<- fewer refreshes, same test results :)
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by dweymouth** [comment]
This is a good change (though haven't tested it yet) but just noting that it doesn't fix #5456 - the root cause there is the widgets themselves. e.g. here in Tree, it refreshes the entire content in the OffsetUpdated callback from the scroller: https://github.com/fyne-io/fyne/blob/develop/widget/tree.go#L491 (and similarly in table)

File: widget/widget.go [hunk 1]
```diff
@@ -112,16 +111,14 @@ func (w *BaseWidget) Hide() {
...
-		impl := w.super()
-		if impl == nil {
-			return
-		}
+	impl := w.super()
+	if impl == nil {
+		return
+	}
 
-		w.themeCache = nil
```
Comment (Jacalz) [inline widget/widget.go:121]: This change does not look like it belongs here?

**Review by Jacalz — CHANGES_REQUESTED** [review]
Thanks. Looking really good. Just a small change I think you accidentally left in there (or due to being based on the wrong commit compared to develop).

File: widget/widget.go (hunk 1 above)
Comment (andydotxyz) [reply widget/widget.go:121]: The commit comment "Widget.Refresh running thread handling code was not great for potential loop scenarios" explains it I think...

Comment (andydotxyz) [reply widget/widget.go:121]: The added bonus being that you the long log of thread warnings from the test driver that were being complained about is gone.

Comment (Jacalz) [reply widget/widget.go:121]: Ah, sorry

**Review by Jacalz — APPROVED** [review]

File: internal/widget/scroller.go [hunk 2]
```diff
@@ -489,7 +493,19 @@ func (s *Scroll) Resize(sz fyne.Size) {
...
 
 	s.Base.Resize(sz)
-	s.Refresh()
+	s.refreshBars()
+}
+
+// SetOffset will update the location of the content of this scroll container.
+//
+// Since: 2.6
+func (s *Scroll) SetOffset(p fyne.Position) {
```
Comment (dweymouth) [inline internal/widget/scroller.go:502]: Should this perhaps be named `ScrollToOffset` to match the naming of `ScrollToBottom` etc, and also the `ScrollToOffset` that exists in List and GridWrap?

Comment (andydotxyz) [reply internal/widget/scroller.go:502]: Thanks, good eye.

**Review by Jacalz — APPROVED** [review]

**Review by dweymouth — APPROVED** [review]
