### PR TITLE
Android: listContentURI: Fix crash caused by permission denial

### LINKED ISSUE #6117: Android: storage.List(uri) call results in crash when permission has expired
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

This line runs fine on my Android device right after selecting a folder with `dialog.ShowFolderOpen`:

```go
filelist, err := storage.List(uri)
```

But when I store the folder URI (in the app preferences) and try opening the folder again after an app restart, it crashes because of a missing permission:

```
02-18 15:39:20.403  1702  1987 W ContentProviderHelper: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{213a2b6 5506:com.goodtemperapps.markdownviewer/u0a639} (pid=5506, uid=10639) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
02-18 15:39:20.415  5506 17072 F .markdownviewer: java_vm_ext.cc:616] JNI DETECTED ERROR IN APPLICATION: JNI GetObjectClass called with pending exception java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{213a2b6 5506:com.goodtemperapps.markdownviewer/u0a639} (pid=5506, uid=10639) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
```

I expect that the function returns `err != nil` in such a case.

### How to reproduce

1. Pick folder with `dialog.ShowFolderOpen`.
2. Read content with `storage.List(uri)`.
3. Store `uri` in preferences.
4. Restart app.
5. Load preferences.
6. Call `storage.List(uri)`.

### Screenshots

_No response_

### Example code

I'll try to add a minimal app to reproduce this crash.

### Fyne version

develop branch

### Go compiler version

go1.25.7

### Operating system and version

Arch Linux

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by MaxGyver83**
### Description:

Fix crash that happens after calling `storage.List(uri)` for a URI whose read permission has expired (on Android).

Fixes #6117.

It would be cool if `storage.List(uri)` would set `err != nil` in such a case. Maybe we can pass a pointer to an int for error codes when calling `char* listContentURI(uintptr_t jni_env, uintptr_t ctx, char* uriCstr)` (and other C functions)!? Or we return `null` instead of `""` if an error happens. Or we set `char *` to an error message?

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [ ] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Good catch on adding safety here.

Changing the method signature between Go and C is generally a bad idea because the tool / library dependency is currently too tight and you'd end up tying the Fyne CLI to specific versions of the toolkit.

Perhaps the returned string or other parameter could include some sort of sentinel to identify the error case?

**Comment by MaxGyver83** [comment]
> Perhaps the returned string or other parameter could include some sort of sentinel to identify the error case?

`listContentURI` could return `ERROR: xxx` (using the error message from Android for `xxx`). `folder_android.go` seems to be the only place where this is used. There, we could check if the string starts with `ERROR:` and return an error then and return the file/URI list otherwise.

Of course, this is a little bit hacky because (in theory) a folder could contain a file named `ERROR: Permission Denial: opening provider ...`. And then `listURI` would return an error by mistake. Do you think this acceptable? Do you want me to send a commit for this? Or a separate PR after this one is merged?

**Comment by andydotxyz** [comment]
To avoid the naming collusion perhaps the string can contain a character that no file can ever include like 0x00? (Though that specific one may not work as the C code in between might terminate the string).

**Comment by MaxGyver83** [comment]
> To avoid the naming collusion perhaps the string can contain a character that no file can ever include like 0x00? (Though that specific one may not work as the C code in between might terminate the string).

Yes, 0x00 won't work in C. Meanwhile I think it's okay to simply return `ERROR: xxx` in an error case. I didn't consider that this function doesn't return simple filenames but URIs (separated by `|`), p.e. `content://com.android.externalstorage.documents/tree/primary%3Axxx.md|content://com.android.externalstorage.documents/tree/...`.

Do you agree that returning `ERROR: xxx` is unambiguous then?

**Comment by MaxGyver83** [comment]
> Yes, 0x00 won't work in C. Meanwhile I think it's okay to simply return `ERROR: xxx` in an error case. I didn't consider that this function doesn't return simple filenames but URIs (separated by `|`), p.e. `content://com.android.externalstorage.documents/tree/primary%3Axxx.md|content://com.android.externalstorage.documents/tree/...`.
> 
> Do you agree that returning `ERROR: xxx` is unambiguous then?

I have rebased this branch and added a second commit that lets `listURI` return an error with error message if listing the content fails.

File: internal/driver/mobile/folder_android.go [hunk 1]
```diff
@@ -63,7 +63,12 @@ func listURI(uri fyne.URI) ([]fyne.URI, error) {
 		return nil
 	})
 
-	parts := strings.Split(C.GoString(str), "|")
+	result := C.GoString(str)
+	if strings.HasPrefix(result, "ERROR:") {
+		return nil, errors.New(result)
```
Comment (andydotxyz) [inline internal/driver/mobile/folder_android.go]: I think this means the error message will start with ERROR: which it shouldn't - can you strip that out? (just indexing the string would do it)

**Review by andydotxyz — CHANGES_REQUESTED** [review]

File: internal/driver/mobile/folder_android.go (hunk 1 above)
Comment (MaxGyver83) [reply internal/driver/mobile/folder_android.go]: Sure! Changed in e091681.

Comment (andydotxyz) [reply internal/driver/mobile/folder_android.go]: Thanks. Please try to avoid force-push after reviews have begun btw

**Review by andydotxyz — APPROVED** [review]
Excellent thanks

File: internal/driver/mobile/folder_android.go (hunk 1 above)
Comment (MaxGyver83) [reply internal/driver/mobile/folder_android.go]: Alright!
