### PR TITLE
Fix issues with release regarding scrolling wrapped rich text content

### LINKED ISSUE #4201: RichText Scroll Height incorrect with Scroll enabled and content wrapped.
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Using any `widget.NewRichText` and setting `Wrapping` to `fyne.TextWrapWord` (or Break).
Then text content long enough to wrap.
Notice it does not scroll all the way to the end.

The basic `MinSize` works (when scroll turned off) so the math is in there OK somewhere but the scroll+wrap cases are not handled correctly.

### How to reproduce

As above, notice scroll is too short to reach bottom.

### Screenshots

_No response_

### Example code

As above

### Fyne version

2.4.0-rc1

### Go compiler version

1.18.4

### Operating system and version

macOS 13.4

### Additional Information

New at the late stages of 2.4 development when wrap+truncate was added

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #4201

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: widget/richtext_objects.go [hunk 1]
```diff
@@ -494,27 +485,39 @@ func (r *richImage) MinSize() fyne.Size {
...
+	gap := s.Width - r.r.min.Width
+
+	switch r.r.align {
+	case fyne.TextAlignCenter:
+		r.r.img.Move(fyne.NewPos(gap/2, 0))
+	case fyne.TextAlignTrailing:
+		r.r.img.Move(fyne.NewPos(gap, 0))
+	default:
+		r.r.img.Move(fyne.NewPos(0, 0))
+	}
```
Comment (Jacalz) [inline widget/richtext_objects.go:514]: Just a small suggestion:
```go
	gap := float32(0)

	switch r.r.align {
	case fyne.TextAlignCenter:
		gap = (s.Width - r.r.min.Width) / 2
	case fyne.TextAlignTrailing:
		gap = s.Width - r.r.min.Width
	}

	r.r.img.Move(fyne.NewPos(gap, 0))
```

**Review by Jacalz — APPROVED** [review]
I'll approve this but please consider my suggestion inline before merging :)

**Review by Jacalz — APPROVED** [review]
