### PR TITLE
Fixing semantics of test canvas resize

### LINKED ISSUE #5548: `SoftwareCanvas` resize only works properly if it's the last step
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Following up on the suggestion from Discord to report this here... If i take the following code:

```go
width := 1024
height := 758

myCanvas := playground.NewSoftwareCanvas()

clockText := canvas.NewText(time.Now().Format("15:04:05"), color.White)
clockText.TextSize = 150
clockText.Alignment = fyne.TextAlignCenter

clockContainer := container.NewCenter(clockText)

myCanvas.SetContent(clockContainer)
myCanvas.Resize(fyne.Size{Width: width, Height: height})

img := myCanvas.Capture()
```

And save the result as an image, I get the expected result:

Image

But if I move `myCanvas.Resize(fyne.Size{Width: width, Height: height})` directly after `myCanvas := playground.NewSoftwareCanvas()`, the result will be wrong:

Image

### How to reproduce

1. Copy my provided example code
2. `go run .`
3. See that the resulting `clock.png` has the wrong resolution, it should be 1024x758.
4. Put `myCanvas.Resize(fyne.Size{Width: width, Height: height})` under `myCanvas.SetContent(clockContainer)`.
5. Notice that the image is rendered properly.

### Screenshots

_No response_

### Example code

```go
package main

import (
	"fmt"
	"image"
	"image/color"
	"image/png"
	"os"
	"time"

	"fyne.io/fyne"
	"fyne.io/fyne/canvas"
	"fyne.io/fyne/container"
	"fyne.io/fyne/tools/playground"
)

func main() {
	width := 1024
	height := 758

	myCanvas := playground.NewSoftwareCanvas()
	myCanvas.Resize(fyne.Size{Width: width, Height: height})

	clockText := canvas.NewText(time.Now().Format("15:04:05"), color.White)
	clockText.TextSize = 150
	clockText.Alignment = fyne.TextAlignCenter

	clockContainer := container.NewCenter(clockText)

	myCanvas.SetContent(clockContainer)

	img := myCanvas.Capture()

	saveImage(img, "clock.png")
}

func saveImage(img image.Image, filename string) {
	f, err := os.Create(filename)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer f.Close()

	err = png.Encode(f, img)
	if err != nil {
		fmt.Println(err)
		return
	}
}
```

### Fyne version

v2.5.4

### Go compiler version

1.24.0

### Operating system and version

Arch Linux amd64

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #5548

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: widget/tree.go [hunk 1]
```diff
@@ -766,6 +766,9 @@ func (r *treeContentRenderer) Objects() []fyne.CanvasObject {
 
 func (r *treeContentRenderer) Refresh() {
 	r.refreshForID(r.treeContent.nextRefreshID)
+	for _, s := range r.separators {
```
Comment (dweymouth) [inline widget/tree.go:769]: Why was this needed? I think this will lead to RefreshItem, and maybe scrolling, refreshing all separators always, which shouldn't be needed.

Comment (andydotxyz) [reply widget/tree.go:769]: Without it the resize after changing theme was picking up bad separators.

It seemed like a logical change because the `Refresh` of the content was being called and the items were being refreshed - so shouldn't the separators?

Comment (andydotxyz) [reply widget/tree.go:769]: (You can see that List has essentially the same - when the content `Refresh()` is called we loop through the separators and refresh them)

**Comment by andydotxyz** [comment]
This change uncovered a bug in both tree and list refreshing (theme change then resize) which I think I have fixed appropriately...

File: widget/tree.go (hunk 1 above)
Comment (dweymouth) [reply widget/tree.go:769]: OK - may be something that can be optimized later since it should only be needed for a full Refresh, and not RefreshItem, etc which will still go through this path. But as you point out it's the same as List for now

File: widget/list.go [hunk 2]
```diff
@@ -761,6 +761,10 @@ func (l *listLayout) updateList(newOnly bool) {
 		for _, vis := range l.visible {
 			l.setupListItem(vis.item, vis.id, l.list.focused && l.list.currentFocus == vis.id)
 		}
+
+		// a full refresh means drain the pool of excess old items as well
```
Comment (dweymouth) [inline widget/list.go:765]: Can we elaborate on the why here - that the old items may have an old theme applied? I can imagine this piece of code, and the current comment, becoming cryptic with time since it's not obvious why we'd be draining the pool. Also would be useful if we revisit this some time later with smarter refreshing to avoid having to do this.

Comment (andydotxyz) [reply widget/list.go:765]: When we call Refresh it is iterating visible items to refresh them.
But the items in the cache are being left in old theme.
Is the sentence there just needing more "why" in it?

File: widget/tree.go (hunk 1 above)
Comment (andydotxyz) [reply widget/tree.go:769]: Good point. I'm not too worried as a separator refresh is so minimal :)

File: widget/list.go (hunk 2 above)
Comment (dweymouth) [reply widget/list.go:765]: yeah I think the code comment needs the info about the old theme - so someone coming to this code later on after this PR is long forgotten knows why it was added

Comment (andydotxyz) [reply widget/list.go]: OK thanks, I hope the update helps

File: widget/tree.go (hunk 1 above)
Comment (Jacalz) [reply widget/tree.go:769]: I think we should open an issue to make sure we don't forget to do that optimization in the future

File: widget/list.go [hunk 3]
```diff
@@ -761,6 +761,10 @@ func (l *listLayout) updateList(newOnly bool) {
 		for _, vis := range l.visible {
 			l.setupListItem(vis.item, vis.id, l.list.focused && l.list.currentFocus == vis.id)
 		}
+
+		// a full refresh may change theme, we should drain the pool of unused items instead of refreshing them.
+		for l.itemPool.Get() != nil {
```
Comment (Jacalz) [inline widget/list.go:766]: I don't understand why this is the case. Is it not defeating the purpose of the pool if we do this for each refresh?

Comment (andydotxyz) [reply widget/list.go:766]: The pool does not exist to make refresh fast it is to make scroll fast...
When `Refresh()` is called we have to re-draw all of the list items whether they are in the pool or not. So either a) drain the pool and don't refresh them or b) Redraw all the items not currently on screen.

I went with a - but b would be OK too if you have a strong feeling.

Comment (Jacalz) [reply widget/list.go:766]: Makes sense. Let's go with this approach for now

**Review by Jacalz — APPROVED** [review]
