### PR TITLE
Fix issue where long or tall images could jump on load

### LINKED ISSUE #1266: Image with ImageFillContain seen stretched before correcting for aspect.
### Describe the bug:
 Image first shows as stretched to fill canvas. After a short pause (probably processing time) the image is re-displayed corrected for aspect.

### To Reproduce:
Run this code with local image

package main

import (
	"fmt"
	"imaging"
	"os"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/canvas"
)

func main() {
	myApp := app.New()
	w := myApp.NewWindow("Image")
	w.Resize(fyne.NewSize(600, 600)) // problem for all sizes tried

	// Open JPEG file and get io.Reader

	fileName := os.Args[1]
	file, err := os.Open(fileName)
	if err != nil {
		fmt.Printf("Error opening file %s\n", fileName)
		return
	}

	// Set the AutroOrientation option for decoding.
	// We need to use imaging,Decode because it checks for and corrects for orientation data.
	// If present this is held in an EXIF tag. image.Decode() follows the standard
	// JPEG library and assumes file will be soley JFIF and correctly orientated.
        // Using imaging package to get round this.

	opt := imaging.AutoOrientation(true)  // create option for imaging.Decode()
	img, err := imaging.Decode(file, opt) // decoded file as image.Image

	if err != nil {
		fmt.Printf("Error decoding image %s\nError %v\n", fileName, err)
		return
	}

	image := canvas.NewImageFromImage(img)
	image.FillMode = canvas.ImageFillContain
	w.SetContent(image)
	w.ShowAndRun()
}

### Device (please complete the following information):
 - OS: "Linux Ubuntu"
 - Version: "18.04.5 LTS (Bionic Beaver)"
 - Go version: "go1.15 linux/amd64"
 - Fyne version: "v1.3.3-3-g6c9ed1b5"]

### PR DESCRIPTION
**Pull request by andydotxyz**
Issue was that we were reading aspect before setting it on the first frame.
Fixes #1266

### Checklist:

- [ ] Tests included. <- this was a rendering glitch, you can load the reproduction code to test, but it's not seen in test code
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/painter/gl/draw.go [hunk 1]
```diff
@@ -56,13 +56,21 @@ func (p *glPainter) rectCoords(size fyne.Size, pos fyne.Position, frame fyne.Siz
...
 	}
 
+	aspect := float32(0)
+	if img, ok := o.(*canvas.Image); ok {
+		aspect = painter.GetAspect(img)
+		if aspect == 0 {
+			fyne.LogError("Missing aspect ratio for loaded image", nil)
+			aspect = 1 // fallback, should not occur
+		}
+	}
```
Comment (stuartmscott) [inline internal/painter/gl/draw.go:73]: Should the zero check and fallback be moved outside of the type check and cast?
```suggestion
	if img, ok := o.(*canvas.Image); ok {
		aspect = painter.GetAspect(img)
	}
	if aspect == 0 {
		fyne.LogError("Missing aspect ratio for loaded image", nil)
		aspect = 1 // fallback, should not occur
	}
```

Comment (andydotxyz) [reply internal/painter/gl/draw.go:73]: Not in this case - see how 0 was passed in many times as a valid parameter.
0 is just not OK for images

Comment (stuartmscott) [reply internal/painter/gl/draw.go:73]: Ack

**Review by stuartmscott — APPROVED** [review]
