### PR TITLE
Fix content position in dialog layout

### LINKED ISSUE #6181: Layout issue with fyne.TextWordWrap
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When `fyne.TextWrapWord` is used on a custom dialog, the window does not display correctly and will sometimes display erratically unless `Refresh` is called on the dialog.  . Not displaying correctly means the background will not fill the container and the size of the form is not consistent on consecutive executions.

Image
Image

### How to reproduce

Run the below code leaving the `Refresh` commented out.
**NOTE:** This has only been tested on Linux running KDE6.

## Expected Results
This is the result after Refresh is called or if the parent window is resized:

Image

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/widget"
	"golang.org/x/image/colornames"
)

func main() {
	test2 := app.New()
	mainWindow := test2.NewWindow("Test 2")

	mainWindow.SetContent(
		widget.NewButton("click me", func() {
			customDialog := dialog.NewCustom("test window", "ok", myCustomForm(), mainWindow)
			customDialog.Show()
			//customDialog.Refresh() // Background and other window sizing was not displaying correctly
		}),
	)
	mainWindow.Resize(fyne.NewSize(700, 700))

	mainWindow.ShowAndRun()
}

func myCustomForm() fyne.CanvasObject {

	wrappedLabel1 := widget.NewLabel("This is extra long text to display on a label for word wrapping to create an example of the issue.")
	wrappedLabel1.Wrapping = fyne.TextWrapWord

	wrappedLabel2 := widget.NewLabel("This is extra long text to display on a label for word wrapping to create an example of the issue.")
	wrappedLabel2.Wrapping = fyne.TextWrapWord

	wrappedLabel3 := widget.NewLabel("This is extra long text to display on a label for word wrapping to create an example of the issue.")
	wrappedLabel3.Wrapping = fyne.TextWrapWord

	otherControls := container.NewPadded(
		container.NewVBox(
			container.NewHBox(widget.NewLabel("Entry 1:"), widget.NewEntry()),
			wrappedLabel1,

			container.NewHBox(widget.NewLabel("Entry2:"), widget.NewEntry()),
			wrappedLabel2,

			container.NewHBox(widget.NewLabel("Entry3:"), widget.NewEntry()),
			widget.NewLabel("Discriptive label with longer text to bulk the window a little"),
			wrappedLabel3,

			widget.NewButton("Test button 1", nil),
			widget.NewButton("Test button 2", nil),
			widget.NewButton("Test button 3", nil),
		),
	)

	background := canvas.NewVerticalGradient(colornames.Darkblue, colornames.Darkcyan)

	return container.NewStack(background, otherControls)

}
```

### Fyne version

2.7.3

### Go compiler version

1.26

### Operating system and version

Kubuntu 25.10 : Linux dellg16 6.17.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan  9 17:01:16 UTC 2026 x86_64 GNU/Linux

## Graphics Driver
Using nvidia open 590 driver

## Other:
Discussed with Andy on Discord

### PR DESCRIPTION
**Pull request by typenoob**
### Description:

Just move `content`'s layout after `button`'s layout because `content` needs `button`'s position to calculate its end position.

Fixes #6181

This issue is easily observed when using a wrapped label in a custom dialog, so I've added a test for that.

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: dialog/custom_test.go [hunk 1]
```diff
@@ -163,3 +163,23 @@ func TestCustom_SetIcon(t *testing.T) {
...
+	test.NewTempApp(t)
+	w := test.NewTempWindow(t, canvas.NewRectangle(color.Transparent))
+	w.Resize(fyne.NewSize(200, 300))
+
+	label := widget.NewLabel("iiiiiiiiiimmmmmmmmmm")
+	label.Wrapping = fyne.TextWrapWord
+	d := NewCustom("Title", "OK", label, w)
+	d.Show()
+
+	p := d.win
```
Comment (andydotxyz) [inline dialog/custom_test.go]: Shouldn't this just be "d.Resize()"?

**Review by andydotxyz — COMMENTED** [review]
Thanks for taking a crack at this

File: dialog/custom_test.go (hunk 1 above)
Comment (typenoob) [reply dialog/custom_test.go]: d.Resize() sets the popup's size, which is incorrect for our case.
The correct approach is to use d.win.Content.Resize() to set the content's size.
How about using that?

**Comment by typenoob** [comment]
The test is better now because it compares the two content layout to verify consistency. 
(With the old code in [dialog/base.go](https://github.com/fyne-io/fyne/pull/6212/changes#diff-44ff150ae90e134ed0f0bc3740ea44355971514a7d6861c387a429df46d020cd), the button's position should appear correct in the second result, but that could mask an underlying layout flaw that occurs during the first calculation).

**Review by dweymouth — APPROVED** [review]
