### PR TITLE
fix: allow apptabs to store state while transitioning tabs

### LINKED ISSUE #2135: container: Tab animation is too slow vertically and starts too high
### Describe the bug:

I initially noted this in wormhole-gui when using the mobile branch. There I see that the tab animation starts way too high on the screen an then  slowly falls down to where it should be. That happens a bit too fast in the code example below to be noticeable enough, but it can be seen when resizing the window (the animation var does not stay with the tab).

### To Reproduce:
Steps to reproduce the behaviour:
1. Resize window with tab bar at the bottom
2. Or: Start application with tab bar at the bottom.

### Screenshots:

The refresh rate on the gif is a bit too slow to see the full effect:
falling-tabs

The example code resizing:
falling-tabs-example

### Example code:
```go
// Package main loads a very basic Hello World graphical application.
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	tabs := container.NewAppTabs(container.NewTabItem("Test", hello))
	tabs.SetTabLocation(container.TabLocationBottom)

	w.SetContent(tabs)
	w.Resize(fyne.NewSize(200, 600))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** 5.11.9
 - **Go version:** 1.16.2
 - **Fyne version:** 2.0.2

### PR DESCRIPTION
**Pull request by AnkushJadhav**
### Description:
Added an internal field to AppTabs that stores the state when a tab change is happening, thereby allowing animations only on valid tab changes.
This is a port of #2187 for release 2.0.3.

Fixes #2135 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by AnkushJadhav** [comment]
@andydotxyz The flicker on tab switching was due to #1952 , which has been fixed on develop. I have implemented a lesser elegant solution in this PR, which avoids the flicker.

File: container/apptabs.go [hunk 1]
```diff
@@ -89,7 +90,7 @@ func (c *AppTabs) CreateRenderer() fyne.WidgetRenderer {
 	c.BaseWidget.ExtendBaseWidget(c)
 	r := &appTabsRenderer{line: canvas.NewRectangle(theme.ShadowColor()),
 		underline: canvas.NewRectangle(theme.PrimaryColor()), container: c}
-	r.updateTabs()
+	r.updateTabs(c.isTransitioning)
```
Comment (andydotxyz) [inline container/apptabs.go:93]: When creating a renderer isn't this always false?

File: container/apptabs.go [hunk 2]
```diff
@@ -422,22 +425,30 @@ func (r *appTabsRenderer) moveSelection() {
...
 
-	if r.animation != nil {
-		r.animation.Stop()
-	}
-	r.animation = canvas.NewPositionAnimation(r.underline.Position(), underlinePos, canvas.DurationShort, func(p fyne.Position) {
-		r.underline.Move(p)
-		canvas.Refresh(r.underline)
-		if p == underlinePos {
-			r.animation = nil
+	if withAnimation {
```
Comment (andydotxyz) [inline container/apptabs.go:428]: If this was !withAnimation then we could handle the non-animated case and return, returning the main code to the least indentation.
This is our style but also makes it easier to merge back to develop after release.

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Thanks so much, you found the problem I could not!
Just a couple of small things inline if that's OK and I think we're ready.

File: container/apptabs.go (hunk 1 above)
Comment (AnkushJadhav) [reply container/apptabs.go:93]: Yes, `c.isTransitioning` would ideally always be `false` at this point. Would it be better if I explicitly set it as false?

File: container/apptabs.go (hunk 2 above)
Comment (AnkushJadhav) [reply container/apptabs.go]: That makes sense, updated the PR.

**Review by Jacalz — APPROVED** [review]
Nice work. Thank you very much for the fixes :+1:

**Review by andydotxyz — APPROVED** [review]
Great thanks
