### PR TITLE
Fix widget renderer leak from cache never being cleaned

### LINKED ISSUE #4903: Memory leak from widget renderers never being destroyed
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

widget.Table will CreateCell every time when table.Refresh() called.
detail below `How to reproduce`

### How to reproduce

1. testing code
```go
func main() {
	myApp := app.New()

	myWindow := myApp.NewWindow("test")
	myWindow.Resize(fyne.NewSize(1000, 500))
	rows := [][]string{}
	for i := 0; i < 100; i++ {
		rows = append(rows, make([]string, 100))
		for j := 0; j < 100; j++ {
			rows[i][j] = fmt.Sprintf("%d:%d", i, j)
		}
	}

	table := widget.NewTable(func() (rows int, cols int) {
		return 100, 100
	}, func() fyne.CanvasObject {
		log.Println("Create Cell: ", time.Now().UnixNano())
		return widget.NewLabel("")
	}, func(id widget.TableCellID, object fyne.CanvasObject) {
		l := object.(*widget.Label)
		l.SetText(rows[id.Row][id.Col])
	})
	myWindow.SetContent(table)

	go refreshLoop(table)
	myWindow.ShowAndRun()

}

func refreshLoop(table *widget.Table) {
	tick := time.NewTicker(time.Millisecond * 10)
	defer tick.Stop()
	for _ = range tick.C {
		table.Refresh()
	}
}

```
2. you will see the memory increasing and `Create Cell: xxxxx` printing constantly.
3. tracking chain: 
- table.Refresh()
- t.t.templateSize()
- t.CreateCell()
- template.MinSize()
- cache.Renderer(l.super())
- renderers[wid] = rinfo

4. it will allways cache a new `widget.Label` into `renderers`. Consequently, no gc reach.
5. pprof heap tree
```shell
(pprof) tree
Showing nodes accounting for 118.15MB, 97.88% of 120.71MB total
Dropped 26 nodes (cum <= 0.60MB)
Showing top 80 nodes out of 107
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                           40.51MB   100% |   fyne.io/fyne/v2/widget.(*textRenderer).Refresh
   31.51MB 26.10% 26.10%    40.51MB 33.56%                | fyne.io/fyne/v2/widget.(*RichText).cachedSegmentVisual
                                               9MB 22.22% |   fyne.io/fyne/v2/widget.(*TextSegment).Visual
----------------------------------------------------------+-------------
                                              16MB   100% |   fyne.io/fyne/v2/widget.NewLabel
      16MB 13.26% 39.36%       16MB 13.26%                | fyne.io/fyne/v2/widget.NewLabelWithStyle
----------------------------------------------------------+-------------
                                           17.25MB   100% |   fyne.io/fyne/v2/widget.NewRichTextWithText
      11MB  9.11% 48.48%    17.25MB 14.29%                | fyne.io/fyne/v2/widget.NewRichText
                                            6.25MB 36.22% |   fyne.io/fyne/v2/widget.(*RichText).updateRowBounds
----------------------------------------------------------+-------------
                                            8.85MB   100% |   fyne.io/fyne/v2/internal/painter.loadMeasureFont
    8.85MB  7.33% 55.81%     8.85MB  7.33%                | github.com/go-text/typesetting/opentype/loader.(*Loader).findTableBuffer
----------------------------------------------------------+-------------
                                            8.50MB   100% |   fyne.io/fyne/v2/widget.(*TextSegment).Visual
    8.50MB  7.04% 62.85%     8.50MB  7.04%                | fyne.io/fyne/v2/canvas.NewText
----------------------------------------------------------+-------------
                                            6.50MB   100% |   fyne.io/fyne/v2/widget.(*RichText).CreateRenderer
    6.50MB  5.39% 68.23%     6.50MB  5.39%                | fyne.io/fyne/v2/canvas.NewRectangle
----------------------------------------------------------+-------------
                                           23.75MB   100% |   fyne.io/fyne/v2/widget.(*Label).CreateRenderer
    6.50MB  5.39% 73.62%    23.75MB 19.68%                | fyne.io/fyne/v2/widget.NewRichTextWithText
                                           17.25MB 72.63% |   fyne.io/fyne/v2/widget.NewRichText
----------------------------------------------------------+-------------
                                           92.61MB 97.37% |   fyne.io/fyne/v2/widget.(*Label).MinSize
                                           13.64MB 14.35% |   fyne.io/fyne/v2/widget.(*BaseWidget).MinSize
                                            1.50MB  1.58% |   fyne.io/fyne/v2/widget.(*BaseWidget).Resize
                                            0.50MB  0.53% |   fyne.io/fyne/v2/widget.(*BaseWidget).Refresh
    5.46MB  4.52% 78.14%    95.11MB 78.80%                | fyne.io/fyne/v2/internal/cache.Renderer
                                           88.66MB 93.21% |   fyne.io/fyne/v2/widget.(*Label).CreateRenderer
                                           13.14MB 13.82% |   fyne.io/fyne/v2/widget.(*Table).CreateRenderer
                                               1MB  1.05% |   fyne.io/fyne/v2/internal/cache.(*expiringCache).setAlive
----------------------------------------------------------+-------------
                                           19.64MB   100% |   fyne.io/fyne/v2/widget.(*RichText).updateRowBounds
       5MB  4.14% 82.28%    19.64MB 16.27%                | fyne.io/fyne/v2/widget.(*RichText).updateRowBounds.func1
                                           13.14MB 66.91% |   fyne.io/fyne/v2.MeasureText
                                            1.50MB  7.64% |   fyne.io/fyne/v2/widget.lineBounds
----------------------------------------------------------+-------------
                                            3.19MB   100% |   fyne.io/fyne/v2/internal/async.(*CanvasObjectQueue).Out
    3.19MB  2.65% 84.93%     3.19MB  2.65%                | sync.(*poolChain).pushHead
----------------------------------------------------------+-------------
                                           64.91MB   100% |   fyne.io/fyne/v2/widget.(*Label).CreateRenderer
       3MB  2.49% 87.41%    64.91MB 53.77%                | fyne.io/fyne/v2/widget.(*RichText).CreateRenderer
                                           42.51MB 65.49% |   fyne.io/fyne/v2/widget.(*textRenderer).Refresh
                                           12.90MB 19.87% |   fyne.io/fyne/v2/widget.(*RichText).updateRowBounds
                                            6.50MB 10.02% |   fyne.io/fyne/v2/canvas.NewRectangle
----------------------------------------------------------+-------------
                                               3MB   100% |   fyne.io/fyne/v2/internal/async.(*CanvasObjectQueue).In
       3MB  2.49% 89.90%        3MB  2.49%                | fyne.io/fyne/v2/internal/async.init.func1
----------------------------------------------------------+-------------
                                           42.51MB 92.39% |   fyne.io/fyne/v2/widget.(*RichText).CreateRenderer
                                            3.50MB  7.61% |   fyne.io/fyne/v2/widget.(*BaseWidget).Refresh
       2MB  1.66% 91.56%    46.01MB 38.12%                | fyne.io/fyne/v2/widget.(*textRenderer).Refresh
                                           40.51MB 88.05% |   fyne.io/fyne/v2/widget.(*RichText).cachedSegmentVisual
                                            2.50MB  5.43% |   fyne.io/fyne/v2/widget.(*TextSegment).Update
                                               1MB  2.17% |   fyne.io/fyne/v2/canvas.Refresh
----------------------------------------------------------+-------------
                                            1.69MB   100% |   fyne.io/fyne/v2/internal/painter.loadMeasureFont
    1.69MB  1.40% 92.95%     1.69MB  1.40%                | github.com/go-text/typesetting/opentype/api/font/cff.parseIndexContent
----------------------------------------------------------+-------------
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.lineBounds
    1.50MB  1.24% 94.20%     1.50MB  1.24%                | fyne.io/fyne/v2/widget.splitLines
----------------------------------------------------------+-------------
                                            1.06MB   100% |   fyne.io/fyne/v2/internal/painter.loadMeasureFont
    1.06MB  0.87% 95.07%     1.06MB  0.87%                | github.com/go-text/typesetting/opentype/tables.ParseBaseArray
----------------------------------------------------------+-------------
                                               1MB   100% |   fyne.io/fyne/v2/internal/cache.Renderer
       1MB  0.83% 95.90%        1MB  0.83%                | fyne.io/fyne/v2/internal/cache.(*expiringCache).setAlive
----------------------------------------------------------+-------------
    0.84MB  0.69% 96.59%     0.84MB  0.69%                | github.com/goccy/go-json/internal/decoder.init.0
----------------------------------------------------------+-------------
                                            1.55MB   100% |   fyne.io/fyne/v2/internal/painter.loadMeasureFont
    0.55MB  0.46% 97.05%     1.55MB  1.29%                | github.com/go-text/typesetting/opentype/tables.ParseGlyf
----------------------------------------------------------+-------------
    0.50MB  0.41% 97.47%    13.65MB 11.30%                | main.main
                                           13.14MB 96.33% |   fyne.io/fyne/v2/internal/driver/glfw.(*window).SetContent
----------------------------------------------------------+-------------
                                            1.06MB 67.91% |   fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree
                                            1.06MB 67.91% |   fyne.io/fyne/v2/internal/driver.walkObjectTree.func1
                                            0.50MB 32.09% |   fyne.io/fyne/v2/internal/driver/common.(*Canvas).Refresh
    0.50MB  0.41% 97.88%     1.56MB  1.29%                | fyne.io/fyne/v2/internal/driver.walkObjectTree
                                            1.06MB 67.91% |   fyne.io/fyne/v2/internal/driver.walkObjectTree.func1
----------------------------------------------------------+-------------
                                            1.50MB   100% |   github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwSetWindowSize
         0     0% 97.88%     1.50MB  1.24%                | _cgoexp_16379c6f66fe_goWindowSizeCB
                                            1.50MB   100% |   github.com/go-gl/glfw/v3.3/glfw.goWindowSizeCB
----------------------------------------------------------+-------------
                                           13.14MB   100% |   fyne.io/fyne/v2/widget.(*RichText).updateRowBounds.func1
         0     0% 97.88%    13.14MB 10.89%                | fyne.io/fyne/v2.MeasureText
                                           13.14MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).RenderedTextSize
----------------------------------------------------------+-------------
                                            2.50MB   100% |   fyne.io/fyne/v2/widget.(*TextSegment).Update
         0     0% 97.88%     2.50MB  2.07%                | fyne.io/fyne/v2/canvas.(*Text).Refresh
                                            2.50MB   100% |   fyne.io/fyne/v2/canvas.Refresh
----------------------------------------------------------+-------------
                                            2.50MB 71.43% |   fyne.io/fyne/v2/canvas.(*Text).Refresh
                                               1MB 28.57% |   fyne.io/fyne/v2/widget.(*textRenderer).Refresh
         0     0% 97.88%     3.50MB  2.90%                | fyne.io/fyne/v2/canvas.Refresh
                                            3.50MB   100% |   fyne.io/fyne/v2/internal/driver/common.(*Canvas).Refresh
----------------------------------------------------------+-------------
                                               3MB   100% |   fyne.io/fyne/v2/internal/driver/common.(*Canvas).Refresh
         0     0% 97.88%        3MB  2.49%                | fyne.io/fyne/v2/internal/async.(*CanvasObjectQueue).In
                                               3MB   100% |   fyne.io/fyne/v2/internal/async.init.func1
----------------------------------------------------------+-------------
                                            3.19MB   100% |   fyne.io/fyne/v2/internal/driver/common.(*Canvas).FreeDirtyTextures
         0     0% 97.88%     3.19MB  2.65%                | fyne.io/fyne/v2/internal/async.(*CanvasObjectQueue).Out
                                            3.19MB   100% |   sync.(*poolChain).pushHead
----------------------------------------------------------+-------------
                                            1.06MB   100% |   fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree
         0     0% 97.88%     1.06MB  0.88%                | fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree
                                            1.06MB   100% |   fyne.io/fyne/v2/internal/driver.walkObjectTree
----------------------------------------------------------+-------------
                                            1.06MB   100% |   fyne.io/fyne/v2/internal/driver.walkObjectTree
         0     0% 97.88%     1.06MB  0.88%                | fyne.io/fyne/v2/internal/driver.walkObjectTree.func1
                                            1.06MB   100% |   fyne.io/fyne/v2/internal/driver.walkObjectTree
----------------------------------------------------------+-------------
                                            3.19MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1
         0     0% 97.88%     3.19MB  2.65%                | fyne.io/fyne/v2/internal/driver/common.(*Canvas).FreeDirtyTextures
                                            3.19MB   100% |   fyne.io/fyne/v2/internal/async.(*CanvasObjectQueue).Out
----------------------------------------------------------+-------------
                                            3.50MB   100% |   fyne.io/fyne/v2/canvas.Refresh
         0     0% 97.88%     3.50MB  2.90%                | fyne.io/fyne/v2/internal/driver/common.(*Canvas).Refresh
                                               3MB 85.71% |   fyne.io/fyne/v2/internal/async.(*CanvasObjectQueue).In
                                            0.50MB 14.29% |   fyne.io/fyne/v2/internal/driver.walkObjectTree
----------------------------------------------------------+-------------
                                            1.06MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1
         0     0% 97.88%     1.06MB  0.88%                | fyne.io/fyne/v2/internal/driver/common.(*Canvas).WalkTrees
                                            1.06MB   100% |   fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree
----------------------------------------------------------+-------------
                                            1.06MB   100% |   fyne.io/fyne/v2/internal/driver/common.(*Canvas).WalkTrees
         0     0% 97.88%     1.06MB  0.88%                | fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree
                                            1.06MB   100% |   fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree
----------------------------------------------------------+-------------
                                           13.14MB   100% |   fyne.io/fyne/v2.MeasureText
         0     0% 97.88%    13.14MB 10.89%                | fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).RenderedTextSize
                                           13.14MB   100% |   fyne.io/fyne/v2/internal/painter.RenderedTextSize
----------------------------------------------------------+-------------
                                            3.70MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1
         0     0% 97.88%     3.70MB  3.06%                | fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame
                                            3.70MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow
----------------------------------------------------------+-------------
                                            3.70MB 86.91% |   fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame
                                            0.56MB 13.09% |   fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext
         0     0% 97.88%     4.25MB  3.52%                | fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow
                                            4.25MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext
----------------------------------------------------------+-------------
                                            4.25MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext
         0     0% 97.88%     4.25MB  3.52%                | fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1
                                            3.19MB 75.11% |   fyne.io/fyne/v2/internal/driver/common.(*Canvas).FreeDirtyTextures
                                            1.06MB 24.89% |   fyne.io/fyne/v2/internal/driver/common.(*Canvas).WalkTrees
----------------------------------------------------------+-------------
         0     0% 97.88%     4.25MB  3.52%                | fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1
                                            3.70MB 86.91% |   fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame
                                            0.56MB 13.09% |   fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext
----------------------------------------------------------+-------------
                                            1.50MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*window).processResized
         0     0% 97.88%     1.50MB  1.24%                | fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).Resize
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.(*BaseWidget).Resize
----------------------------------------------------------+-------------
                                           13.14MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*window).SetContent
         0     0% 97.88%    13.14MB 10.89%                | fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).SetContent
                                           13.14MB   100% |   fyne.io/fyne/v2/widget.(*BaseWidget).MinSize
----------------------------------------------------------+-------------
                                            4.25MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow
                                            0.56MB 13.09% |   fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1
         0     0% 97.88%     4.25MB  3.52%                | fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext
                                            4.25MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1
                                            0.56MB 13.09% |   fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow
----------------------------------------------------------+-------------
                                           13.14MB   100% |   main.main
         0     0% 97.88%    13.14MB 10.89%                | fyne.io/fyne/v2/internal/driver/glfw.(*window).SetContent
                                           13.14MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).SetContent
----------------------------------------------------------+-------------
                                            1.50MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*window).resized
         0     0% 97.88%     1.50MB  1.24%                | fyne.io/fyne/v2/internal/driver/glfw.(*window).processResized
                                            1.50MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).Resize
----------------------------------------------------------+-------------
                                            1.50MB   100% |   github.com/go-gl/glfw/v3.3/glfw.goWindowSizeCB
         0     0% 97.88%     1.50MB  1.24%                | fyne.io/fyne/v2/internal/driver/glfw.(*window).resized
                                            1.50MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*window).processResized
----------------------------------------------------------+-------------
                                           13.14MB   100% |   fyne.io/fyne/v2/internal/painter.measureText
         0     0% 97.88%    13.14MB 10.89%                | fyne.io/fyne/v2/internal/painter.CachedFontFace
                                           13.14MB   100% |   fyne.io/fyne/v2/internal/painter.loadMeasureFont
----------------------------------------------------------+-------------
                                           13.14MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).RenderedTextSize
         0     0% 97.88%    13.14MB 10.89%                | fyne.io/fyne/v2/internal/painter.RenderedTextSize
                                           13.14MB   100% |   fyne.io/fyne/v2/internal/painter.measureText
----------------------------------------------------------+-------------
                                           13.14MB   100% |   fyne.io/fyne/v2/internal/painter.CachedFontFace
         0     0% 97.88%    13.14MB 10.89%                | fyne.io/fyne/v2/internal/painter.loadMeasureFont
                                            8.85MB 67.31% |   github.com/go-text/typesetting/opentype/loader.(*Loader).findTableBuffer
                                            1.69MB 12.84% |   github.com/go-text/typesetting/opentype/api/font/cff.parseIndexContent
                                            1.55MB 11.81% |   github.com/go-text/typesetting/opentype/tables.ParseGlyf
                                            1.06MB  8.03% |   github.com/go-text/typesetting/opentype/tables.ParseBaseArray
----------------------------------------------------------+-------------
                                           13.14MB   100% |   fyne.io/fyne/v2/internal/painter.RenderedTextSize
         0     0% 97.88%    13.14MB 10.89%                | fyne.io/fyne/v2/internal/painter.measureText
                                           13.14MB   100% |   fyne.io/fyne/v2/internal/painter.CachedFontFace
----------------------------------------------------------+-------------
                                            1.50MB   100% |   fyne.io/fyne/v2/internal/widget.(*Scroll).Resize
         0     0% 97.88%     1.50MB  1.24%                | fyne.io/fyne/v2/internal/widget.(*Base).Resize
                                            1.50MB   100% |   fyne.io/fyne/v2/internal/widget.(*scrollContainerRenderer).Layout
----------------------------------------------------------+-------------
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.(*tableRenderer).Layout
         0     0% 97.88%     1.50MB  1.24%                | fyne.io/fyne/v2/internal/widget.(*Scroll).Resize
                                            1.50MB   100% |   fyne.io/fyne/v2/internal/widget.(*Base).Resize
----------------------------------------------------------+-------------
                                            1.50MB   100% |   fyne.io/fyne/v2/internal/widget.(*Base).Resize
         0     0% 97.88%     1.50MB  1.24%                | fyne.io/fyne/v2/internal/widget.(*scrollContainerRenderer).Layout
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.(*tableCells).Resize
----------------------------------------------------------+-------------
                                           13.14MB 96.34% |   fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).SetContent
                                            0.50MB  3.66% |   fyne.io/fyne/v2/widget.(*Label).MinSize
         0     0% 97.88%    13.64MB 11.30%                | fyne.io/fyne/v2/widget.(*BaseWidget).MinSize
                                           13.64MB   100% |   fyne.io/fyne/v2/internal/cache.Renderer
----------------------------------------------------------+-------------
                                           36.51MB 35.80% |   fyne.io/fyne/v2/widget.(*tableRenderer).Refresh
                                            2.50MB  2.45% |   fyne.io/fyne/v2/widget.(*RichText).Refresh
                                            1.50MB  1.47% |   fyne.io/fyne/v2/widget.(*tableCells).Resize
                                            1.50MB  1.47% |   fyne.io/fyne/v2/widget.(*Label).Refresh
         0     0% 97.88%   101.97MB 84.48%                | fyne.io/fyne/v2/widget.(*BaseWidget).Refresh
                                          100.47MB 98.53% |   fyne.io/fyne/v2/widget.(*tableRenderer).Refresh
                                           38.01MB 37.27% |   fyne.io/fyne/v2/widget.(*tableCellsRenderer).Refresh
                                            3.50MB  3.43% |   fyne.io/fyne/v2/widget.(*textRenderer).Refresh
                                            0.50MB  0.49% |   fyne.io/fyne/v2/internal/cache.Renderer
----------------------------------------------------------+-------------
                                            1.50MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).Resize
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.(*Label).Resize
         0     0% 97.88%     1.50MB  1.24%                | fyne.io/fyne/v2/widget.(*BaseWidget).Resize
                                            1.50MB   100% |   fyne.io/fyne/v2/internal/cache.Renderer
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.(*tableRenderer).Layout
----------------------------------------------------------+-------------
                                           88.66MB   100% |   fyne.io/fyne/v2/internal/cache.Renderer
         0     0% 97.88%    88.66MB 73.45%                | fyne.io/fyne/v2/widget.(*Label).CreateRenderer
                                           64.91MB 73.21% |   fyne.io/fyne/v2/widget.(*RichText).CreateRenderer
                                           23.75MB 26.79% |   fyne.io/fyne/v2/widget.NewRichTextWithText
----------------------------------------------------------+-------------
                                              27MB 29.00% |   fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshHeaders
                                           26.96MB 28.95% |   fyne.io/fyne/v2/widget.(*Table).templateSize
                                              26MB 27.93% |   fyne.io/fyne/v2/widget.(*tableRenderer).Refresh
                                           13.14MB 14.12% |   fyne.io/fyne/v2/widget.(*Table).CreateRenderer
         0     0% 97.88%    93.11MB 77.14%                | fyne.io/fyne/v2/widget.(*Label).MinSize
                                           92.61MB 99.46% |   fyne.io/fyne/v2/internal/cache.Renderer
                                            0.50MB  0.54% |   fyne.io/fyne/v2/widget.(*BaseWidget).MinSize
----------------------------------------------------------+-------------
                                            4.50MB   100% |   fyne.io/fyne/v2/widget.(*Label).SetText
         0     0% 97.88%     4.50MB  3.73%                | fyne.io/fyne/v2/widget.(*Label).Refresh
                                               3MB 66.67% |   fyne.io/fyne/v2/widget.(*RichText).Refresh
                                            1.50MB 33.33% |   fyne.io/fyne/v2/widget.(*BaseWidget).Refresh
----------------------------------------------------------+-------------
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshForID.func1
         0     0% 97.88%     1.50MB  1.24%                | fyne.io/fyne/v2/widget.(*Label).Resize
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.(*BaseWidget).Resize
----------------------------------------------------------+-------------
                                            4.50MB   100% |   fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshForID
         0     0% 97.88%     4.50MB  3.73%                | fyne.io/fyne/v2/widget.(*Label).SetText
                                            4.50MB   100% |   fyne.io/fyne/v2/widget.(*Label).Refresh
----------------------------------------------------------+-------------
                                               3MB   100% |   fyne.io/fyne/v2/widget.(*Label).Refresh
         0     0% 97.88%        3MB  2.49%                | fyne.io/fyne/v2/widget.(*RichText).Refresh
                                            2.50MB 83.33% |   fyne.io/fyne/v2/widget.(*BaseWidget).Refresh
                                            0.50MB 16.67% |   fyne.io/fyne/v2/widget.(*RichText).updateRowBounds
----------------------------------------------------------+-------------
                                           12.90MB 65.65% |   fyne.io/fyne/v2/widget.(*RichText).CreateRenderer
                                            6.25MB 31.81% |   fyne.io/fyne/v2/widget.NewRichText
                                            0.50MB  2.55% |   fyne.io/fyne/v2/widget.(*RichText).Refresh
         0     0% 97.88%    19.64MB 16.27%                | fyne.io/fyne/v2/widget.(*RichText).updateRowBounds
                                           19.64MB   100% |   fyne.io/fyne/v2/widget.(*RichText).updateRowBounds.func1
----------------------------------------------------------+-------------
                                           13.14MB   100% |   fyne.io/fyne/v2/internal/cache.Renderer
         0     0% 97.88%    13.14MB 10.89%                | fyne.io/fyne/v2/widget.(*Table).CreateRenderer
                                           13.14MB   100% |   fyne.io/fyne/v2/widget.(*Label).MinSize
----------------------------------------------------------+-------------
                                               5MB 55.56% |   fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshHeaders
                                               4MB 44.44% |   fyne.io/fyne/v2/widget.(*tableRenderer).Refresh
         0     0% 97.88%        9MB  7.46%                | fyne.io/fyne/v2/widget.(*Table).createHeader
                                               9MB   100% |   fyne.io/fyne/v2/widget.NewLabel
----------------------------------------------------------+-------------
                                           33.96MB   100% |   fyne.io/fyne/v2/widget.(*tableRenderer).Refresh
         0     0% 97.88%    33.96MB 28.14%                | fyne.io/fyne/v2/widget.(*Table).templateSize
                                           26.96MB 79.38% |   fyne.io/fyne/v2/widget.(*Label).MinSize
                                               7MB 20.62% |   fyne.io/fyne/v2/widget.NewLabel
----------------------------------------------------------+-------------
                                            2.50MB 83.33% |   fyne.io/fyne/v2/widget.(*textRenderer).Refresh
                                            0.50MB 16.67% |   fyne.io/fyne/v2/widget.(*TextSegment).Visual
         0     0% 97.88%        3MB  2.49%                | fyne.io/fyne/v2/widget.(*TextSegment).Update
                                            2.50MB 83.33% |   fyne.io/fyne/v2/canvas.(*Text).Refresh
----------------------------------------------------------+-------------
                                               9MB   100% |   fyne.io/fyne/v2/widget.(*RichText).cachedSegmentVisual
         0     0% 97.88%        9MB  7.46%                | fyne.io/fyne/v2/widget.(*TextSegment).Visual
                                            8.50MB 94.45% |   fyne.io/fyne/v2/canvas.NewText
                                            0.50MB  5.55% |   fyne.io/fyne/v2/widget.(*TextSegment).Update
----------------------------------------------------------+-------------
                                            1.50MB   100% |   fyne.io/fyne/v2/internal/widget.(*scrollContainerRenderer).Layout
         0     0% 97.88%     1.50MB  1.24%                | fyne.io/fyne/v2/widget.(*tableCells).Resize
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.(*BaseWidget).Refresh
----------------------------------------------------------+-------------
                                           38.01MB   100% |   fyne.io/fyne/v2/widget.(*BaseWidget).Refresh
         0     0% 97.88%    38.01MB 31.49%                | fyne.io/fyne/v2/widget.(*tableCellsRenderer).Refresh
                                           38.01MB   100% |   fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshForID
----------------------------------------------------------+-------------
                                           38.01MB   100% |   fyne.io/fyne/v2/widget.(*tableCellsRenderer).Refresh
         0     0% 97.88%    38.01MB 31.49%                | fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshForID
                                           32.01MB 84.21% |   fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshHeaders
                                            4.50MB 11.84% |   fyne.io/fyne/v2/widget.(*Label).SetText
                                            1.50MB  3.95% |   fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshForID.func2
----------------------------------------------------------+-------------
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshForID.func2
         0     0% 97.88%     1.50MB  1.24%                | fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshForID.func1
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.(*Label).Resize
----------------------------------------------------------+-------------
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshForID
         0     0% 97.88%     1.50MB  1.24%                | fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshForID.func2
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshForID.func1
----------------------------------------------------------+-------------
                                           32.01MB   100% |   fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshForID
         0     0% 97.88%    32.01MB 26.51%                | fyne.io/fyne/v2/widget.(*tableCellsRenderer).refreshHeaders
                                              27MB 84.37% |   fyne.io/fyne/v2/widget.(*Label).MinSize
                                               5MB 15.63% |   fyne.io/fyne/v2/widget.(*Table).createHeader
----------------------------------------------------------+-------------
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.(*BaseWidget).Resize
         0     0% 97.88%     1.50MB  1.24%                | fyne.io/fyne/v2/widget.(*tableRenderer).Layout
                                            1.50MB   100% |   fyne.io/fyne/v2/internal/widget.(*Scroll).Resize
----------------------------------------------------------+-------------
                                          100.47MB   100% |   fyne.io/fyne/v2/widget.(*BaseWidget).Refresh
         0     0% 97.88%   100.47MB 83.24%                | fyne.io/fyne/v2/widget.(*tableRenderer).Refresh
                                           36.51MB 36.33% |   fyne.io/fyne/v2/widget.(*BaseWidget).Refresh
                                           33.96MB 33.80% |   fyne.io/fyne/v2/widget.(*Table).templateSize
                                              26MB 25.88% |   fyne.io/fyne/v2/widget.(*Label).MinSize
                                               4MB  3.98% |   fyne.io/fyne/v2/widget.(*Table).createHeader
----------------------------------------------------------+-------------
                                               9MB 56.25% |   fyne.io/fyne/v2/widget.(*Table).createHeader
                                               7MB 43.75% |   fyne.io/fyne/v2/widget.(*Table).templateSize
         0     0% 97.88%       16MB 13.26%                | fyne.io/fyne/v2/widget.NewLabel
                                              16MB   100% |   fyne.io/fyne/v2/widget.NewLabelWithStyle
----------------------------------------------------------+-------------
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.(*RichText).updateRowBounds.func1
         0     0% 97.88%     1.50MB  1.24%                | fyne.io/fyne/v2/widget.lineBounds
                                            1.50MB   100% |   fyne.io/fyne/v2/widget.splitLines
----------------------------------------------------------+-------------
         0     0% 97.88%        1MB  0.83%                | github.com/go-gl/glfw/v3.3/glfw.(*Window).SetSize
                                               1MB   100% |   github.com/go-gl/glfw/v3.3/glfw.(*Window).SetSize.func1
----------------------------------------------------------+-------------
                                               1MB 66.67% |   github.com/go-gl/glfw/v3.3/glfw.(*Window).SetSize
         0     0% 97.88%     1.50MB  1.24%                | github.com/go-gl/glfw/v3.3/glfw.(*Window).SetSize.func1
                                            1.50MB   100% |   github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwSetWindowSize
----------------------------------------------------------+-------------
                                            1.50MB   100% |   github.com/go-gl/glfw/v3.3/glfw.(*Window).SetSize.func1
         0     0% 97.88%     1.50MB  1.24%                | github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwSetWindowSize
                                            1.50MB   100% |   _cgoexp_16379c6f66fe_goWindowSizeCB
----------------------------------------------------------+-------------
                                            1.50MB   100% |   _cgoexp_16379c6f66fe_goWindowSizeCB
         0     0% 97.88%     1.50MB  1.24%                | github.com/go-gl/glfw/v3.3/glfw.goWindowSizeCB
                                            1.50MB   100% |   fyne.io/fyne/v2/internal/driver/glfw.(*window).resized
----------------------------------------------------------+-------------

```

### Screenshots

_No response_

### Example code

see `how to reproduce`.

### Fyne version

2.4.5

### Go compiler version

1.22.3

### Operating system and version

macOS 13.1

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dweymouth**
### Description:

Calls the cache clean task in the main loop, which was previously not called due to a bug. Also periodically walks inactive windows to mark the canvasForObject cache entries as alive, to prevent freezes from cleaning the canvas cache in inactive windows.

Fixes #4903 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/driver/glfw/loop.go [hunk 1]
```diff
@@ -65,24 +65,40 @@ func runOnMainWithWait(f func(), wait bool) {
...
 		// because when a window becomes visible, it could be
 		// showing old content without a dirty flag set to true.
 		// Do the clear if and only if the window is visible.
-		if closing || !visible || !canvas.CheckDirtyAndClear() {
+		if !w.visible || !canvas.CheckDirtyAndClear() {
+			// Window hidden or not being redrawn, mark canvasForObject
+			// cache alive if it hasn't been done recently
+			// n.b. we need to make sure threshold is a bit *after*
+			// time.Now() - CacheDuration()
+			threshold := time.Now().Add(-cache.CacheDuration()).Add(1 * time.Second)
```
Comment (Jacalz) [inline internal/driver/glfw/loop.go:86]: I think it is a bit clearer to do `.Sub().Add()` or even the other way around?

File: internal/driver/glfw/window_desktop.go [hunk 2]
```diff
@@ -399,6 +402,14 @@ func (w *window) mouseScrolled(viewport *glfw.Window, xoff float64, yoff float64
 	w.processMouseScrolled(xoff, yoff)
 }
 
+func (w *window) lastWalked() time.Time {
+	return w.lastWalkedTime
+}
```
Comment (Jacalz) [inline internal/driver/glfw/window_desktop.go:407]: Do we really need this as a function if it only is internal field?

**Review by Jacalz — CHANGES_REQUESTED** [review]
I can't comment on the effectiveness of this but I left a few suggestions inline. Thanks for looking at this. Great to have a leak squashed. Is this a workaround or is the underlying issue still there? If it is there, we should open an issue and track that it ought to be solved some other way in the future.

File: internal/driver/glfw/window_desktop.go (hunk 2 above)
Comment (dweymouth) [reply internal/driver/glfw/window_desktop.go:407]: Probably not, I did it as a function to protect it from accidental changes from another package (basically to make it read-only), but since it's all internal code anyway I guess it's premature access control

File: internal/driver/glfw/loop.go (hunk 1 above)
Comment (Jacalz) [reply internal/driver/glfw/loop.go]: Hmm. That's strange. Do we get strange behaviour if we do `.Add(time.Second - cache.CacheDuration())`?

File: internal/driver/glfw/window_desktop.go (hunk 2 above)
Comment (Jacalz) [reply internal/driver/glfw/window_desktop.go:407]: Yeah, I think there are many other internal fields that we don't have getters for so it seems more consistent to not add one more. I think we might also want to remove `.windows()` from the driver now that we don't have the locking there etc.

File: internal/cache/base.go [hunk 3]
```diff
@@ -8,8 +8,8 @@ import (
 )
 
 var (
-	cacheDuration     = 1 * time.Minute
```
Comment (Jacalz) [inline internal/cache/base.go:11]: I kind of preferred the old function to expose it but it doesn't matter much as this is about naming. I think we ought to remove global variables to some extent in the future honestly. I also don't know in which capacity the `FYNE_CACHE` env var is used. Removing it would allow us to have these as constants instead which I feel is better. Anyway, sorry for my rant.

My main problem with exposing this is that `cache.CacheDuration` stutters a bit. It should likely either be `cache.Duration` or `cache.CleanDuration`. I think the latter is better.

**Review by Jacalz — CHANGES_REQUESTED** [review]

File: internal/driver/glfw/window_desktop.go (hunk 2 above)
Comment (Jacalz) [reply internal/driver/glfw/window_desktop.go:407]: Did you mark this as resolved by accident? I don't see it being fixed

File: internal/cache/base.go (hunk 3 above)
Comment (dweymouth) [reply internal/cache/base.go:11]: Renamed it to `cache.ValidDuration` since it's really a measure of how long a cache entry stays valid after last access

File: internal/driver/glfw/loop.go (hunk 1 above)
Comment (dweymouth) [reply internal/driver/glfw/loop.go]: That works fine, switched to it

**Review by Jacalz — APPROVED** [review]
I think Andy has a lot more experience with the internal caches so it might be good to get a +1 from him as well but I think it looks good 👍

**Comment by dweymouth** [comment]
I'm going to merge this now so that it will get more widespread testing (everyone testing on develop), and if there are any more issues we can address them or roll back if needed
