### PR TITLE
Keep track of windows closing without removing context

### LINKED ISSUE #1604: SIGSEGV Sometimes When Closing a Program by Clicking a Button
### Describe the bug:
I've noticed that sometimes my program faults with "[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x7fdae2aa6fc4]". It doesn't happen every time, though, so I'm not sure exactly where it is going wrong, full error is here: https://hastebin.com/efiyuxofag.go

### To Reproduce:
Steps to reproduce the behaviour:
* Run any Fyne program on my system which closes the window by clicking a button widget, it will sometimes need to be ran lots of times until I can reproduce the exact error message.

### Example Code

```
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/container"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/widget"
	"fmt"
)


func showConfirm(title, question string, callback func(bool)) {
	a := app.New()
	w := a.NewWindow(title)
	yes := widget.NewButton("Yes", func() {
		callback(true)
		w.Close()
	})
	yes.Importance = widget.HighImportance
	w.SetContent(container.NewVBox(
		widget.NewLabel(question),
		container.NewHBox(layout.NewSpacer(),
			widget.NewButton("No", func() {
				callback(false)
				w.Close()
			}), yes,
			layout.NewSpacer())))
	w.ShowAndRun()
}

func main() {
	showConfirm("MyTitle", "Are you sure?", func(b bool) {
		if b {
			fmt.Println("Confirmed")
		}
	})
}
```

### Device (please complete the following information):
 - OS: Ubuntu Linux
 - Version: 20.04
 - Go version: 1.12.1
 - Fyne version: 0ca05dc12c03b8873d2f22caa6ce4c28988b3886

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #1604

### Checklist:

- [x] Tests included. <- existing tests OK, could not find a way to replicate in tests as it was random / racey
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/driver/glfw/window.go [hunk 1]
```diff
@@ -423,10 +424,11 @@ func (w *window) Hide() {
 }
 
 func (w *window) Close() {
-	if w.viewport == nil {
+	if w.closing {
 		return
 	}
 
+	w.closing = true
 	w.viewport.SetShouldClose(true)
```
Comment (stuartmscott) [inline internal/driver/glfw/window.go:432]: Should this still be protected by a nil check?
```suggestion
	if v := w.viewport; v != nil {
		v.SetShouldClose(true)
	}
```

File: internal/driver/glfw/window.go [hunk 2]
```diff
@@ -273,7 +274,7 @@ func (w *window) fitContent() {
 		return
 	}
 
-	if w.viewport == nil {
+	if w.viewport == nil || w.closing {
```
Comment (stuartmscott) [inline internal/driver/glfw/window.go:277]: consider adding `w.isClosing()` which could encapsulate these two tests and be used in several call sites in this file

File: internal/driver/glfw/window.go (hunk 1 above)
Comment (andydotxyz) [reply internal/driver/glfw/window.go:432]: I don't think so - previously viewport was set to nil to show it was closed, now it is only nil before the window appears.
I guess it couldn't hurt to use the suggested helper at the top instead though.

**Review by stuartmscott — APPROVED** [review]
