### PR TITLE
Markdown renderer: Support links in bold and italic text

### LINKED ISSUE #5576: Markdown formatting removes links
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Formatting seems to break links inside of markdown, they also appear to have an extra space in front

### How to reproduce

Run the attached example code and notice the formatted code does not contain working links

### Screenshots

Image

### Example code

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("demo")

	md := `
# Header

## Sub header with a [link](https://fyne.io)

Regular text with a [link](https://fyne.io) works

**Bold doesn't work with a [link](https://fyne.io)**

*Italic doesn't work with a [link](https://fyne.io)*
`

	w.SetContent(widget.NewRichTextFromMarkdown(md))

	w.ShowAndRun()
}

```

### Fyne version

2.5.4

### Go compiler version

go1.23.6 linux/amd64

### Operating system and version

Arch Linux

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by MaxGyver83**
### Description:

In order to support this, a `Style` field is added to the `HyperlinkSegment` struct.

Fixes #5576 partially.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style and have Since: line.

### To be discussed

- Some tests fail but they fail without this PR, too.
- Can it harm that `forceIntoText` isn't called anymore?

### CODE REVIEW

File: widget/richtext_objects.go [hunk 1]
```diff
@@ -115,6 +115,9 @@ type HyperlinkSegment struct {
 	//
 	// Since: 2.4
 	OnTapped func() `json:"-"`
+
+	// Since 2.8
+	Style RichTextStyle
```
Comment (andydotxyz) [inline widget/richtext_objects.go]: Shouldn't this just be TextStyle?

Comment (MaxGyver83) [reply widget/richtext_objects.go]: Oh, yes, TextStyle is all we need. I'll change it.

**Review by andydotxyz — APPROVED** [review]
Excellent, thanks so much
