### PR TITLE
Fixes #4935; Show disabled app tabs as disabled in popup menu

### LINKED ISSUE #4935: Disabled app tabs can still be selected in popup menu
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

An app tab can be disabled, which are then greyed out and the user can normally no longer select hem.

However, when the app tabs do not fit into the current window, some are shown in a popup menu. The popup menu also shows the disabled app tabs and the user can still select them there. 

### How to reproduce

1. Show app tabs with at least one disabled tab
2. Resize the windows manually to force some app tabs to be shown as popup
3. Select a disabled tab from the popup menu  

### Screenshots

_No response_

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("TabContainer Widget")
	tabs := container.NewAppTabs(
		container.NewTabItem("Tab 1", widget.NewLabel("Hello")),
		container.NewTabItem("Tab 2", widget.NewLabel("World!")),
	)
	tabs.DisableIndex(1)
	w.SetContent(tabs)
	w.Resize(fyne.Size{Width: 400, Height: 200})
	w.ShowAndRun()
}
```

### Fyne version

2.4.4

### Go compiler version

1.22.2

### Operating system and version

Ubuntu 22.04.4 LTS

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ErikKalkoken**
### Description:

When there is not enough space to draw all app tabs on screen, some are shown in a popup menu.

Currently disabled tabs are shown as normal menu items in the popup menu, which allows the user to select them.

This change disables menu items in the popup menu for any disabled tab, so they can no longer be selected by the user.

Fixes #4935 

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

N/A

### CODE REVIEW

File: container/apptabs.go [hunk 1]
```diff
@@ -330,13 +330,19 @@ func (r *appTabsRenderer) buildOverflowTabsButton() (overflow *widget.Button) {
...
+			ti := r.appTabs.Items[i]
+			mi := fyne.NewMenuItem(ti.Text, func() {
 				r.appTabs.SelectIndex(index)
 				if r.appTabs.popUpMenu != nil {
 					r.appTabs.popUpMenu.Hide()
 					r.appTabs.popUpMenu = nil
 				}
-			}))
+			})
+			// Fixes #4935
```
Comment (toaster) [inline container/apptabs.go:341]: Don’t add comments referring fixed issues, please.
They have no value.

**Review by toaster — CHANGES_REQUESTED** [review]
Nice work! Just one small thing: please remove the comment referencing the fixed issue. The code is self-explanatory and the tests show the consequences.

File: container/apptabs.go (hunk 1 above)
Comment (ErikKalkoken) [reply container/apptabs.go]: Thank you for the quick review. I removed the comment.

**Review by toaster — APPROVED** [review]
Nice work! Thank you very much!
