### PR TITLE
Fix/1374

### LINKED ISSUE #1374: Table Renders Cells Beyond Limit
The table in fyne_demo has 500 x 150 cells, but is rendered with nearly double that.

Screen Shot 2020-10-08 at 4 22 23 PM

### PR DESCRIPTION
**Pull request by andydotxyz**
### Description:
Various graphical glitches resolved in Table.

Fixes #1374, #1375 

### Checklist:

- [ ] Tests included. <- the redraw code should be tested - except in the test infra it does not happen (different order of events)
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: widget/table.go [hunk 1]
```diff
@@ -226,6 +226,14 @@ func (c *tableCells) CreateRenderer() fyne.WidgetRenderer {
 	return &tableCellsRenderer{cells: c, pool: &syncPool{}, visible: make(map[cellID]fyne.CanvasObject)}
 }
 
+func (c *tableCells) Resize(s fyne.Size) {
+	if s == c.size {
+		return
+	}
+	c.BaseWidget.Resize(s)
```
Comment (stuartmscott) [inline widget/table.go:233]: Not sure if this is needed - it checks the size is different (which is done above on line 230), updates the size, and calls Layout (which does nothing in tableCells). Besides locking, I don't see why this call is needed, am I missing something?

File: widget/table.go [hunk 2]
```diff
@@ -35,8 +35,8 @@ type Table struct {
 // The first returns the data size in rows and columns, second parameter is a function that returns cell
 // template objects that can be cached and the third is used to apply data at specified data location to the
 // passed template CanvasObject.
-func NewTable(len func() (int, int), create func() fyne.CanvasObject, update func(int, int, fyne.CanvasObject)) *Table {
-	t := &Table{Length: len, CreateCell: create, UpdateCell: update, SelectedRow: -1, SelectedColumn: -1}
+func NewTable(length func() (int, int), create func() fyne.CanvasObject, update func(int, int, fyne.CanvasObject)) *Table {
```
Comment (stuartmscott) [inline widget/table.go:38]: Thanks

File: widget/table.go (hunk 1 above)
Comment (andydotxyz) [reply widget/table.go:233]: It was just a best practice I thought - we have overridden BaseWidget so we propagate.
That function could do other things in the future.

**Review by stuartmscott — APPROVED** [review]
