### PR TITLE
Fixing false assumptions about wasm threads

### LINKED ISSUE #5616: Panic on wasm with 2.6.0-beta1
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Widgets that take a while to set up cause this race condition on wasm.

```
panic: syscall/js: call of Value.Call on null
wasm_exec.js:22 
wasm_exec.js:22 goroutine 1 [running]:
wasm_exec.js:22 syscall/js.Value.Call({{}, 0x7ff8000000000002, 0x0}, {0x19ca0b, 0x8}, {0x1433b38, 0x4, 0x4})
wasm_exec.js:22 	/usr/lib/go/src/syscall/js/js.go:438 +0x3f
wasm_exec.js:22 github.com/fyne-io/gl-js.Viewport(...)
wasm_exec.js:22 	/home/hayden/Development/Go/pkg/mod/github.com/fyne-io/gl-js@v0.1.0/gl_webgl_wasm.go:824
wasm_exec.js:22 fyne.io/fyne/v2/internal/painter/gl.(*xjsContext).Viewport(0x12b1140, 0x0, 0x0, 0xf00, 0x4d6)
wasm_exec.js:22 	/home/hayden/Development/Go/src/github.com/hkparker/fyne/internal/painter/gl/gl_wasm.go:238 +0x4
wasm_exec.js:22 fyne.io/fyne/v2/internal/painter/gl.(*painter).SetOutputSize(0x15aa700, 0xf00, 0x4d6)
wasm_exec.js:22 	/home/hayden/Development/Go/src/github.com/hkparker/fyne/internal/painter/gl/painter.go:103 +0x6
wasm_exec.js:22 fyne.io/fyne/v2/internal/driver/glfw.updateGLContext(0x1400fc0)
wasm_exec.js:22 	/home/hayden/Development/Go/src/github.com/hkparker/fyne/internal/driver/glfw/loop.go:228 +0x1d
wasm_exec.js:22 fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
wasm_exec.js:22 	/home/hayden/Development/Go/src/github.com/hkparker/fyne/internal/driver/glfw/loop.go:197 +0xa
wasm_exec.js:22 fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0x1400fc0, 0x1433cc0)
wasm_exec.js:22 	/home/hayden/Development/Go/src/github.com/hkparker/fyne/internal/driver/glfw/window.go:899 +0x18
wasm_exec.js:22 fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0x15e3d90, 0x1400fc0)
wasm_exec.js:22 	/home/hayden/Development/Go/src/github.com/hkparker/fyne/internal/driver/glfw/loop.go:191 +0x4
wasm_exec.js:22 fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame(0x15e3d90)
wasm_exec.js:22 	/home/hayden/Development/Go/src/github.com/hkparker/fyne/internal/driver/glfw/loop.go:89 +0x1b
wasm_exec.js:22 fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0x15e3d90)
wasm_exec.js:22 	/home/hayden/Development/Go/src/github.com/hkparker/fyne/internal/driver/glfw/loop.go:167 +0x76
wasm_exec.js:22 fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0x15e3d90)
wasm_exec.js:22 	/home/hayden/Development/Go/src/github.com/hkparker/fyne/internal/driver/glfw/driver.go:162 +0x6
wasm_exec.js:22 fyne.io/fyne/v2/app.(*fyneApp).Run(0x15e3e40)
wasm_exec.js:22 	/home/hayden/Development/Go/src/github.com/hkparker/fyne/app/app.go:72 +0xf
wasm_exec.js:22 fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0x1400fc0)
wasm_exec.js:22 	/home/hayden/Development/Go/src/github.com/hkparker/fyne/internal/driver/glfw/window.go:221 +0xc
wasm_exec.js:22 main.main()
wasm_exec.js:22 	/home/hayden/Development/Go/src/github.com/hkparker/fyne-dev/main.go:82 +0x3a
```

### How to reproduce

`fyne serve` the example code and click the button while looking at the javascript console

### Screenshots

_No response_

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"time"
)

type slowLabel struct {
	widget.Label
}

func newSlowLabel(str string) *slowLabel {
	sl := &slowLabel{
		Label: widget.Label{Text: str},
	}
	sl.ExtendBaseWidget(sl)

	return sl
}

func (sl *slowLabel) MinSize() fyne.Size {
	time.Sleep(50 * time.Millisecond)
	return sl.Label.MinSize()
}

func main() {
	a := app.New()
	w := a.NewWindow("crash")

	var mainContent fyne.CanvasObject
	mainContent = container.NewVBox(
		newSlowLabel("click this button to crash"),
		widget.NewButton("Crash", func() {
			w.SetContent(mainContent)
		}))

	w.SetContent(mainContent)

	w.ShowAndRun()
}
```

### Fyne version

develop

### Go compiler version

go 1.24.1 linux/amd64

### Operating system and version

Arch Linux / Chrome

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by andydotxyz**
Update wasm to actually track goroutines.
Plus fix a context-in-context issue with glfw/gl on desktop+web

Fixes #5616

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/driver/glfw/loop.go [hunk 1]
```diff
@@ -188,26 +190,25 @@ func (d *gLDriver) destroyWindow(w *window, index int) {
...
+	}
 
-		// mark that we have walked the window and don't
-		// need to walk it again to mark caches alive
-		w.lastWalkedTime = time.Now()
-	})
+	// mark that we have walked the window and don't
+	// need to walk it again to mark caches alive
+	w.lastWalkedTime = time.Now()
+	w.lastWalkedTime = time.Now()
```
Comment (dweymouth) [inline internal/driver/glfw/loop.go:211]: This duplicate line must have been accidental?

File: internal/driver/glfw/loop.go [hunk 2]
```diff
@@ -188,26 +190,25 @@ func (d *gLDriver) destroyWindow(w *window, index int) {
 func (d *gLDriver) repaintWindow(w *window) bool {
```
Comment (dweymouth) [inline internal/driver/glfw/loop.go:190]: It seems like the contract for this function changed so that the caller is now responsible for calling it with GL context? I think there may be one call path where this isn't the case (window.Resize -> platformResize)

Comment (andydotxyz) [reply internal/driver/glfw/loop.go:190]: Thanks for that - I misread main and context run helpers!

**Comment by andydotxyz** [comment]
Thanks @dweymouth - should all be sorted now.

**Review by dweymouth — APPROVED** [review]
