### PR TITLE
Reduce CPU consumption of Entry cursor by around 80%

### LINKED ISSUE #1946: Focused text entry consumes 40%-80% of CPU in my app
### Describe the bug:
I have several forms where text entries can take and lose focus. I noticed that when entry is focused (even without entering any text) the CPU consumption seriously increases.

### Screenshots

Screenshot 2021-02-12 at 11 28 17
Screenshot 2021-02-12 at 11 28 48

### To Reproduce:
Use any app that contains text entries.

### Reproducing conditions:
Platform: `OS X 11.1`
Go version: `go1.15.7 darwin/amd64`
Fyne version: `v2.0.0`

**Note:** This problem is not reproduced with Fyne v1.4.1.

### PR DESCRIPTION
**Pull request by andydotxyz**
### Description:
Reduce CPU load by around 80% by fading over only 1/5th the time.
Also avoid re-calculating MinSize when the visible content has not changed.

Fixes #1946, #4156

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by dweymouth — CHANGES_REQUESTED** [review]

File: widget/entry.go [hunk 1]
```diff
@@ -474,6 +485,14 @@ func (e *Entry) Redo() {
 	e.Refresh()
 }
 
+func (e *Entry) Refresh() {
+	e.propertyLock.Lock()
+	e.minCache = nil
+	e.propertyLock.Unlock()
+
+	e.BaseWidget.Refresh()
+}
```
Comment (Jacalz) [inline widget/entry.go:494]: I'm not saying that it need to be done now or should be done, but maybe it would make sense to have some kind of `MinSize` cache built in to the basewidget? I suppose it is something we might want to do for all widgets more or less (unless the computation is very cheap).

File: widget/entry.go [hunk 2]
```diff
@@ -96,6 +96,7 @@ type Entry struct {
 	binder          basicBinder
 	conversionError error
 	lastChange      time.Time
+	minCache        *fyne.Size
```
[the remark this answers is not in the document]
Comment (Jacalz) [reply widget/entry.go:99]: I suppose the default 0,0 value might be fine as a not-set value because Entry never gets that small, right?

File: widget/entry.go (hunk 1 above)
Comment (andydotxyz) [reply widget/entry.go:494]: I did propose the BaseWidget inclusion some time back but there was pushback for a reason I cannot recall.
Let's get it in here and see how useful it is and it could be pulled up without impact later.

File: widget/entry.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (andydotxyz) [reply widget/entry.go]: Thanks, updated

**Review by dweymouth — APPROVED** [review]

File: widget/entry.go (hunk 1 above)
Comment (Jacalz) [reply widget/entry.go]: It might be worth exploring again. Either as part of the base widget or as some kind of ready cache-system that developers can add to their widgets (maybe using `async.Size` internally?). We should at least look at caching MinSize in more widgets :)

**Comment by dweymouth** [comment]
This should be pulled into v2.4.5 if possible as it's another huge optimization, but like the one for animation runner, it may need minor reworking to not use `async.Size` and just use a regular fyne.Size with locking instead

**Comment by Jacalz** [comment]
It might be worth just waiting for v2.5.0 if the changes are as big as they are

**Comment by dweymouth** [comment]
> It might be worth just waiting for v2.5.0 if the changes are as big as they are

I think it might just be undoing the last commit https://github.com/fyne-io/fyne/pull/4560/commits/42ab4dde88610c031a44a330e71e329bd1e936e7

Plus, if the new threading model is landed in 2.5, which is the current plan, async.Size may not even be needed anymore as widgets can assume their API calls would arrive from a single thread

**Comment by dweymouth** [comment]
This is a *huge* optimization for any Fyne app where the user spends any non-trivial amount of time in text entry. I think we really should get it in 2.4.5
