### PR TITLE
Fix/3887

### LINKED ISSUE #3887: Entry with data binding misses keystrokes or panics on fast input
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I'm using a Barcode-Scanner to input data into an "widget.NewEntryWithData". If the Data is long, and has about a 12ms delay between keystrokes, the input either gets cut or fyne panics.

The length of the string that is needed to hang the application seems to depend on the performance of the computer.
On slower machines I have seen this bug with string length of 10.

A normal Entry (without data binding) works as expected.

### How to reproduce

1. run example code
2. focus input
3. use Barcode scanner (or simulate it with something like xdotool)
4. Panic

```
panic: runtime error: slice bounds out of range [6:5]

goroutine 15 [running]:
fyne.io/fyne/v2/widget.(*RichText).insertAt(0xc0001942c0, 0x6, {0xc000535f20, 0x1})
        /home/alex/go/pkg/mod/fyne.io/fyne/v2@v2.3.4/widget/richtext.go:236 +0x390
fyne.io/fyne/v2/widget.(*Entry).TypedRune(0xc0001ba1c0, 0x72)
        /home/alex/go/pkg/mod/fyne.io/fyne/v2@v2.3.4/widget/entry.go:747 +0x1a5
fyne.io/fyne/v2/internal/driver/glfw.(*window).processCharInput.func1()
        /home/alex/go/pkg/mod/fyne.io/fyne/v2@v2.3.4/internal/driver/glfw/window.go:786 +0x25
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
        /home/alex/go/pkg/mod/fyne.io/fyne/v2@v2.3.4/internal/driver/common/window.go:35 +0x3e
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        /home/alex/go/pkg/mod/fyne.io/fyne/v2@v2.3.4/internal/driver/glfw/window.go:946 +0x136
exit status 2
```

### Screenshots

_No response_

### Example code

```go
package main

import (
        "fyne.io/fyne/v2/app"
        "fyne.io/fyne/v2/container"
        "fyne.io/fyne/v2/data/binding"
        "fyne.io/fyne/v2/widget"
)

func main() {
        myApp := app.New()
        window := myApp.NewWindow("Test")
        sb := binding.NewString()
        c := container.NewVBox(
                widget.NewEntryWithData(sb),
                widget.NewLabelWithData(sb),
        )
        window.SetContent(
                c,
        )
        window.ShowAndRun()
}
```

### Fyne version

2.3.4 and 2.3.5

### Go compiler version

1.20.3 and 1.20.5

### Operating system and version

Linux (6.1), Windows 10 and Windows 11

### Additional Information

On Linux (with X11) you can simulate fast input with:
```sh
go run . & sleep 5; xdotool type "thisisareallylongstringthatmostlikelykillsyourappandorwontappearinitsentirety0123456789"
```

### PR DESCRIPTION
**Pull request by andydotxyz**
### Description:
Fix race conditions and the data setting echo causing panic and/or loss of input when fast-typing on bound entry.

This points to a potential bigger issue of binding set echoes, which I have entered as a new issue #4061.

Fixes #3887 and #3774

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: widget/entry.go [hunk 1]
```diff
@@ -1178,7 +1169,7 @@ func (e *Entry) updateCursorAndSelection() {
 }
 
 func (e *Entry) updateFromData(data binding.DataItem) {
-	if data == nil {
+	if data == nil || e.lastChange.After(time.Now().Add(-bindIgnoreDelay)) {
```
Comment (Jacalz) [inline widget/entry.go:1172]:
```suggestion
	if data == nil || e.lastChange.After(time.Now().Sub(bindIgnoreDelay)) {
```

**Review by Jacalz — CHANGES_REQUESTED** [review]
This is looking very good. I just have one minor comment inline

File: widget/entry.go [hunk 2]
```diff
@@ -17,8 +18,9 @@ import (
 )
 
 const (
-	multiLineRows = 3
-	wordSeparator = "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"
+	bindIgnoreDelay = time.Millisecond * 100 // ignore incoming DataItem fire after we have called Set
```
Comment (dweymouth) [inline widget/entry.go:21]: Would this end up ignoring data updates from user code that happen more frequently than 100 ms?

Comment (andydotxyz) [reply widget/entry.go:21]: It's not ignoring changes faster than 100ms - it is ignoring external updates for a widget being edited by the user, for 10th sec.
I'm not sure if that is what you meant, but given a typical user typing speed this seemed reasonable.

It is possible that this will fail to register correctly if you modify the entry and then 50ms later a remote source changes the data, for these minute corner cases, and for code cleanliness, I opened the other ticket where we should try and find a solution that is not time-based but will be much further reaching.

**Review by Jacalz — APPROVED** [review]
