### PR TITLE
Use the right cache scope for overridden font resources

### LINKED ISSUE #4937: Wrong font rendering when overriding theme
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When one uses a theme for overriding which differs with some font metrics (yet unknown to me) from the main theme, the fonts are rendered wrong.

I discovered this when trying to change the hyperlink theme override test to use `test.Theme()` (default test theme) and `test.newTheme()` (ugly test theme) to remove its dependency from the production theme.

The test fails when doing so and further research revealed that the text was rendered differently.

### How to reproduce

Change the hyperlink theme override test in `widget/hyperlink_test.go` like so:
```diff
func TestHyperlink_ThemeOverride(t *testing.T) {
	_ = test.NewApp()
	defer test.NewApp()
-	test.ApplyTheme(t, internalTest.LightTheme(theme.DefaultTheme()))
+	test.ApplyTheme(t, test.Theme())

	hyperlink := &Hyperlink{Text: "Test"}
	bg := canvas.NewRectangle(color.Gray{Y: 0xc0})
	w.Resize(hyperlink.MinSize())

	light := w.Canvas().Capture()
-	test.ApplyTheme(t, test.Theme())
+	test.ApplyTheme(t, test.NewTheme())
	hyperlink.Refresh()
	ugly := w.Canvas().Capture()
	assertPixelsMatch(t, false, ugly, light)

-	cache.OverrideTheme(hyperlink, internalTest.LightTheme(theme.DefaultTheme()))
+	cache.OverrideTheme(hyperlink, test.Theme())
	hyperlink.Refresh()
	override := w.Canvas().Capture()
	assertPixelsMatch(t, true, override, light)
}
```

The test will then fail. One could use `AssertImageMatches` to get image files of the captured images or write a small test app to have it on screen.

### Screenshots

_No response_

### Example code

-

### Fyne version

develop

### Go compiler version

1.22.1

### Operating system and version

macOS 14.5

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #4937

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/painter/font.go [hunk 1]
```diff
@@ -111,21 +111,29 @@ func CachedFontFace(style fyne.TextStyle, source fyne.Resource, fontDP float32,
 		return val.(*FontCacheItem)
 	}
 
-	val, ok := fontCache.Load(style)
+	scope := ""
+	if o != nil { // for overridden themes get the cache key right
+		scope = cache.WidgetScopeID(o)
+	}
```
Comment (toaster) [inline internal/painter/font.go:117]: FYI: Moving the `nil` check into `WidgetScopeID` would simplify the callers.
