### PR TITLE
Ensure text and SVG textures re-rasterize when window is dragged to new monitor

### LINKED ISSUE #5323: Text strings become blurry when dragging window from low DPI to high DPI monitor
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

New in 2.5.3: Text that was first rendered on a low DPI monitor doesn't re-render when the window moves to a high DPI monitor, instead the GPU just rescales the pre-existing texture(?), resulting in blurriness.

SVG rasterizations also seem to be affected, though the root cause may be different

### How to reproduce

launch a Fyne app on a low DPI monitor, then drag it to a high DPI monitor

### Screenshots

_No response_

### Example code

fyne_demo

### Fyne version

2.5.3

### Go compiler version

n/a

### Operating system and version

ARM Mac, though probably all affected

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dweymouth**
### Description:
A regression in 2.5.3 resulted in text and SVG rasterizations not re-rasterizing when the window was moved between monitors, resulting in blurriness if the window went from low DPI to high DPI.

Fixes #5323 

### Checklist:

- [ ] Tests included. -- Tested manually
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/driver/glfw/window_wasm.go [hunk 1]
```diff
@@ -474,7 +475,11 @@ func (w *window) rescaleOnMain() {
 		scale.ToFyneCoordinate(w.canvas, w.width),
 		scale.ToFyneCoordinate(w.canvas, w.height))
 	w.canvas.Resize(scaledFull)
-	return
+
+	// Ensure textures re-rasterize at the new scale
+	cache.DeleteTextTexturesFor(w.canvas)
+	w.canvas.content.Refresh()
+	//return
```
Comment (Jacalz) [inline internal/driver/glfw/window_wasm.go:482]: I think committing commented out code goes against our contribution guide. I guess that applies to the code below as well?

**Review by Jacalz — COMMENTED** [review]
I can't quite comment on the approach but I left a minor comment inline.

File: internal/driver/glfw/window_wasm.go (hunk 1 above)
Comment (dweymouth) [reply internal/driver/glfw/window_wasm.go]: Done. I suppose the git history will always have the commented-out lines if we ever need to switch back (I have no idea why it was commented-out in the first place)

**Review by andydotxyz — APPROVED** [review]
Thanks for fixing this oversight
